# -*- coding: utf-8 -*-
ADDITIONAL_EXERCISES = [
    # 28. Standard Push-up (AI Supported)
    {
        'id': 28,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'pushup',
        'name': 'Standard Push-up',
        'name_en': 'Standard Push-up',
        'name_ru': 'Классические отжимания',
        'name_kk': 'Классикалық еденнен сығылу',
        'target_muscles': 'Pectoralis Major, Triceps Brachii, Anterior Deltoids',
        'target_muscles_en': 'Pectoralis Major, Triceps, Anterior Deltoids',
        'target_muscles_ru': 'Большая грудная, трицепс, передняя дельта',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті, трицепс, алдыңғы дельта',
        'secondary_muscles_en': 'Core, Serratus Anterior',
        'secondary_muscles_ru': 'Мышцы кора, передняя зубчатая',
        'secondary_muscles_kk': 'Кор бұлшықеттері, алдыңғы тісті бұлшықет',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight',
        'equipment_ru': 'Свой вес',
        'equipment_kk': 'Өз салмағы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Upper-body horizontal pressing movement evaluating chest depth, elbow flare angle, and straight-line plank posture.',
        'description_en': 'Horizontal pressing benchmark evaluating chest depth, scapular control, and plank core integrity.',
        'description_ru': 'Фундаментальное упражнение для развития мышц груди, плечевого пояса и стабильности корпуса.',
        'description_kk': 'Кеуде бұлшықеттерін, иық белдеуін және дененің жалпы тұрақтылығын дамытатын негізгі жаттығу.',
        'starting_position_en': 'High plank position, hands placed slightly wider than shoulder-width, fingers spread, glutes and core tight.',
        'starting_position_ru': 'Упор лежа на прямых руках, ладони чуть шире плеч, тело образует прямую линию от макушки до пяток.',
        'starting_position_kk': 'Қолға сүйеніп жату қалпы, алақан иықтан сәл кеңірек, дене бастан өкшеге дейін түзу сызық түзеді.',
        'instructions_en': '1. Keep your head neutral and gaze at the floor.\n2. Lower your chest toward the floor by bending elbows back at a 45° angle.\n3. Descend until chest is 2-3 cm from the floor.\n4. Push the floor away forcefully to return to full arm extension.',
        'instructions_ru': '1. Держите шею нейтрально, взгляд направлен в пол.\n2. Опускайте грудь к полу, сгибая локти под углом 45 градусов к телу.\n3. Опуститесь до касания пола грудью или 2-3 см от него.\n4. Мощно вытолкните себя вверх до полного выпрямления рук.',
        'instructions_kk': '1. Мойынды түзу ұстап, еденге қараңыз.\n2. Шынтақты денеге 45 градус бұрышпен бүгіп, кеудені еденге қарай түсіріңіз.\n3. Кеуде еденнен 2-3 см қалғанша төмендеңіз.\n4. Қолды толық жазып, еденнен жоғары қарай күшпен итеріліңіз.',
        'breathing_en': 'Inhale on the way down; exhale as you push away from the ground.',
        'breathing_ru': 'Вдох при опускании вниз; выдох при подъеме вверх.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; жоғары көтерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Sagging lower back, flared elbows at 90°, craning neck downward, incomplete lockout.',
        'common_mistakes_ru': 'Провисание таза в пояснице, разведение локтей на 90 градусов в стороны, задирание головы, неполная амплитуда.',
        'common_mistakes_kk': 'Белдің төмен түсіп салбырауы, шынтақтың 90 градусқа жан-жаққа ашылуы, мойынды созу, қолды толық жазбау.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Floor / Shin Level',
        'camera_height_ru': 'На уровне пола / голени',
        'camera_height_kk': 'Еден / балтыр деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Full body in plank from head to toe must be in frame',
        'body_visibility_ru': 'Все тело в планке от макушки до носков должно быть видно',
        'body_visibility_kk': 'Бастан аяқтың ұшына дейін толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera horizontally at ground level 2.5m away to monitor elbow angle and hip neutrality.',
        'camera_instructions_ru': 'Поставьте телефон на пол сбоку на расстоянии 2.5 метров, чтобы камера видела всю линию тела от головы до пяток.',
        'camera_instructions_kk': 'Телефонды бүйір жағынан еденге 2.5 метр қашықтыққа қойыңыз, камера дененің толық түзулігін көруі тиіс.',
        'youtube_id': 'IODxDxX7oi4',
        'video_url': 'https://www.youtube.com/watch?v=IODxDxX7oi4',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': True,
    },
    # 29. Barbell / Bodyweight Squat (AI Supported)
    {
        'id': 29,
        'category_id': 19,
        'category_name': 'Quadriceps',
        'slug': 'squat',
        'name': 'Barbell / Bodyweight Squat',
        'name_en': 'Barbell / Bodyweight Squat',
        'name_ru': 'Приседания со штангой / с собственным весом',
        'name_kk': 'Штангамен / өз салмағымен отырып-тұру',
        'target_muscles': 'Quadriceps, Glutes, Core',
        'target_muscles_en': 'Quadriceps, Gluteus Maximus, Core Stabilizers',
        'target_muscles_ru': 'Квадрицепс, большая ягодичная, мышцы кора',
        'target_muscles_kk': 'Квадрицепс, үлкен бөксе бұлшықеті, кор',
        'secondary_muscles_en': 'Hamstrings, Calves, Erector Spinae',
        'secondary_muscles_ru': 'Бицепс бедра, икры, разгибатели спины',
        'secondary_muscles_kk': 'Санның артқы жағы, балтыр, арқа бұлшықеттері',
        'equipment': 'Barbell / Bodyweight',
        'equipment_en': 'Bodyweight / Barbell',
        'equipment_ru': 'Свой вес / Штанга',
        'equipment_kk': 'Өз салмағы / Штанга',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Lower-body foundational compound movement evaluating knee flexion depth, hip displacement, and spinal neutrality.',
        'description_en': 'Foundational multi-joint lower body movement developing leg strength, hip mobility, and pelvic stability.',
        'description_ru': 'Базовое многосуставное упражнение для развития силы ног, подвижности тазобедренных суставов и стабильности корпуса.',
        'description_kk': 'Аяқ күшін, жамбас буынының қозғалғыштығын және дене тұрақтылығын дамытуға арналған негізгі жаттығу.',
        'starting_position_en': 'Stand with feet shoulder-width apart, toes pointed 15-30 degrees outward. Chest upright, eyes forward.',
        'starting_position_ru': 'Встаньте ровно, стопы на ширине плеч, носки слегка развернуты наружу (15-30°). Спина прямая, взгляд вперед.',
        'starting_position_kk': 'Түзу тұрыңыз, аяқ иық енінде, аяқтың ұшы 15-30° сыртқа қарай. Арқа түзу, алға қараңыз.',
        'instructions_en': '1. Inhale deeply into your abdomen and brace your core.\n2. Initiate descent by hinging at the hips and bending the knees simultaneously.\n3. Lower down under control until hips descend parallel to or below knee line.\n4. Drive powerfully through the midfoot to return to lockout.',
        'instructions_ru': '1. Сделайте глубокий вдох в живот и напрягите мышцы кора.\n2. Начните движение с одновременного отведения таза назад и сгибания коленей.\n3. Опуститесь под контролем до параллели бедер с полом или чуть ниже.\n4. Мощно оттолкнитесь серединой стопы и вернитесь в исходное положение.',
        'instructions_kk': '1. Ішке терең тыныс алып, кор бұлшықеттерін қатайтыңыз.\n2. Жамбасты артқа қарай жылжытып, тізені бүгуді қатар бастаңыз.\n3. Сан еденге параллель болғанша немесе төменірек баяу отырыңыз.\n4. Табанның ортасымен күшпен итеріліп, бастапқы қалыпқа оралыңыз.',
        'breathing_en': 'Inhale on the eccentric descent; exhale forcefully past the sticking point on ascent.',
        'breathing_ru': 'Вдох при движении вниз; мощный выдох при подъеме после преодоления мертвой точки.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; жоғары көтерілгенде күшпен тыныс шығарыңыз.',
        'common_mistakes_en': 'Knees collapsing inward (valgus), heels lifting off floor, excessive forward torso lean, incomplete depth.',
        'common_mistakes_ru': 'Сведение коленей внутрь (вальгус), отрыв пяток от пола, чрезмерный наклон корпуса вперед, недостаточная глубина.',
        'common_mistakes_kk': 'Тізенің ішке қарай майысуы, өкшенің еденнен көтерілуі, дененің алға тым қатты еңкеюі, толық отырмау.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Hip/Knee Height',
        'camera_height_ru': 'На уровне бедер/коленей',
        'camera_height_kk': 'Жамбас/тізе деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full body from head to feet must be visible',
        'body_visibility_ru': 'Все тело с головы до стоп должно быть в кадре',
        'body_visibility_kk': 'Бастан аяққа дейін толық дене көрінуі керек',
        'camera_instructions_en': 'Place phone securely sideways so hip crease and knees are clearly captured by AI.',
        'camera_instructions_ru': 'Установите телефон сбоку на уровне коленей/бедер, чтобы ИИ четко отслеживал угол сгибания коленей и наклон спины.',
        'camera_instructions_kk': 'Телефонды бүйір жағынан тізе/жамбас деңгейіне қойыңыз, ЖИ тізе бүгілу бұрышы мен арқа түзулігін анық көруі тиіс.',
        'youtube_id': 'aclH2T8NY5I',
        'video_url': 'https://www.youtube.com/watch?v=aclH2T8NY5I',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': True,
    },
    # 30. Dumbbell Bicep Curl (AI Supported)
    {
        'id': 30,
        'category_id': 10,
        'category_name': 'Biceps',
        'slug': 'bicep_curl',
        'name': 'Dumbbell Bicep Curl',
        'name_en': 'Dumbbell Bicep Curl',
        'name_ru': 'Сгибание рук с гантелями на бицепс',
        'name_kk': 'Гантельмен бицепске қолды бүгу',
        'target_muscles': 'Biceps Brachii, Brachialis',
        'target_muscles_en': 'Biceps Brachii (Short & Long head), Brachialis',
        'target_muscles_ru': 'Двуглавая мышца плеча (бицепс), плечевая мышца',
        'target_muscles_kk': 'Қолдың екі басты бұлшықеті (бицепс), иық бұлшықеті',
        'secondary_muscles_en': 'Brachioradialis, Forearm Flexors',
        'secondary_muscles_ru': 'Плечелучевая мышца, сгибатели запястья',
        'secondary_muscles_kk': 'Иық-кәрі жілік бұлшықеті, білек сгибательдері',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells',
        'equipment_ru': 'Гантели',
        'equipment_kk': 'Гантельдер',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Isolated upper-limb flexion movement monitoring upper-arm stillness, elbow drift, and torso momentum compensation.',
        'description_en': 'Classic isolation movement building peak bicep hypertrophy and elbow flexion power.',
        'description_ru': 'Изолированное упражнение для максимального сокращения и гипертрофии двуглавой мышцы плеча.',
        'description_kk': 'Бицепстің күшін арттыруға және оны толық қатайтуға арналған оқшауланған жаттығу.',
        'starting_position_en': 'Stand tall with feet hip-width apart. Hold dumbbells at sides with arms fully extended and palms neutral.',
        'starting_position_ru': 'Встаньте прямо, стопы на ширине таза. Гантели по бокам в вытянутых руках, ладони направлены к корпусу.',
        'starting_position_kk': 'Түзу тұрыңыз, аяқ жамбас енінде. Гантельдер дене жанында еркін созылған қолдарда, алақан ішке қараған.',
        'instructions_en': '1. Keep your upper arms pinned stationary to your sides.\n2. Curl the dumbbells upward while supinating your wrists (turning palms up).\n3. Squeeze biceps hard at the peak of contraction.\n4. Lower with a controlled 2-3 second eccentric descent.',
        'instructions_ru': '1. Зафиксируйте локти по бокам корпуса без смещения вперед.\n2. Сгибайте руки в локтях, разворачивая кисти ладонями вверх (супинация).\n3. Задержитесь и прожмите бицепс в верхней точке на 1 секунду.\n4. Подконтрольно опустите гантели в течение 2-3 секунд.',
        'instructions_kk': '1. Шынтақты денеге жабыстырып, қозғалтпай ұстаңыз.\n2. Алақанды жоғары қарай бұра отырып (супинация), гантельдерді жоғары көтеріңіз.\n3. Ең жоғарғы нүктеде бицепсті 1 секунд қатайтыңыз.\n4. Гантельдерді 2-3 секунд ішінде баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale as you curl the dumbbells up; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при сгибании вверх; вдох при плавном опускании вниз.',
        'breathing_kk': 'Жоғары көтергенде тыныс шығарыңыз; баяу түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Swinging torso for momentum, elbows drifting forward, dropping weight without eccentric control.',
        'common_mistakes_ru': 'Раскачивание корпусом (читинг), увод локтей вперед или назад, бросание веса вниз без сопротивления.',
        'common_mistakes_kk': 'Денемен екпін беру (читинг), шынтақты алға немесе артқа жылжыту, салмақты бақылаусыз тез тастай салу.',
        'camera_angle_en': 'Front or Side View',
        'camera_angle_ru': 'Спереди или под углом 45°',
        'camera_angle_kk': 'Алдыңғы немесе 45° бұрыштан',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Upper body and arms must be fully visible',
        'body_visibility_ru': 'Верхняя часть тела и руки должны быть полностью видны',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі мен қолдар толық көрінуі керек',
        'camera_instructions_en': 'Position camera at chest height. Ensure both elbows and shoulders are clearly framed.',
        'camera_instructions_ru': 'Расположите камеру на уровне груди прямо перед собой, чтобы ИИ оценивал неподвижность локтей.',
        'camera_instructions_kk': 'Камераны кеуде деңгейіне қойыңыз, ЖИ шынтақтардың қозғалмай тұрғанын нақты бақылауы керек.',
        'youtube_id': 'ykJmrZ5v0Oo',
        'video_url': 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
        'ideal_rom_degrees': 120.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': True,
    },
    # 31. Overhead Shoulder Press (AI Supported)
    {
        'id': 31,
        'category_id': 6,
        'category_name': 'Shoulders',
        'slug': 'shoulder_press',
        'name': 'Overhead Shoulder Press',
        'name_en': 'Overhead Shoulder Press',
        'name_ru': 'Армейский жим стоя / Жим гантелей над головой',
        'name_kk': 'Гантельді / штанганы бастан асыра көтеру',
        'target_muscles': 'Anterior Deltoids, Lateral Deltoids, Triceps',
        'target_muscles_en': 'Anterior & Lateral Deltoids, Triceps Brachii',
        'target_muscles_ru': 'Передняя и средняя дельта, трицепс',
        'target_muscles_kk': 'Алдыңғы және ортаңғы дельталар, трицепс',
        'secondary_muscles_en': 'Upper Trapezius, Core Stabilizers',
        'secondary_muscles_ru': 'Верх трапеции, зубчатые мышцы, кор',
        'secondary_muscles_kk': 'Жоғарғы трапеция, кор тұрақтандырғыштары',
        'equipment': 'Dumbbells / Barbell',
        'equipment_en': 'Dumbbells / Barbell',
        'equipment_ru': 'Гантели / Штанга',
        'equipment_kk': 'Гантельдер / Штанга',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Vertical overhead pressing movement evaluating overhead lockout, bilateral symmetry, and lumbar hyperextension.',
        'description_en': 'Primary vertical pressing strength builder for total shoulder development and overhead scapular stability.',
        'description_ru': 'Базовое вертикальное жимовое упражнение для силы плечевого пояса и стабильности лопаток.',
        'description_kk': 'Иық белдеуінің күшін және жауырын тұрақтылығын арттыруға арналған негізгі вертикаль жим жаттығуы.',
        'starting_position_en': 'Stand with feet shoulder-width apart, holding weights at shoulder level with knuckles pointing upward, glutes engaged.',
        'starting_position_ru': 'Стопы на ширине плеч, гантели/штанга на уровне плеч, пресс и ягодицы напряжены для фиксации поясницы.',
        'starting_position_kk': 'Аяқ иық енінде, гантельдер иық деңгейінде, белді түзу ұстау үшін бөксе мен кор бұлшықеттері қатайтылған.',
        'instructions_en': '1. Brace core and avoid overarching your lower back.\n2. Press the weight vertically overhead in a smooth path until arms lock out.\n3. Bring biceps close to ears at top lockout.\n4. Lower smoothly back to collarbone level under control.',
        'instructions_ru': '1. Напрягите кор, исключите прогиб в пояснице.\n2. Выжмите вес строго вверх над головой до полного выпрямления рук.\n3. В верхней точке бицепсы находятся на одной линии с ушами.\n4. Плавно верните снаряд к плечам по той же траектории.',
        'instructions_kk': '1. Корды қатайтып, белдің шамадан тыс бүгілуіне жол бермеңіз.\n2. Салмақты қолдар толық жазылғанша бастан асыра тік жоғары көтеріңіз.\n3. Жоғарғы нүктеде бицепстер құлақпен бір сызықта болуы тиіс.\n4. Салмақты иық деңгейіне баяу түсіріңіз.',
        'breathing_en': 'Exhale as you press the weight overhead; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при жиме вверх; вдох при подконтрольном опускании.',
        'breathing_kk': 'Жоғары көтергенде тыныс шығарыңыз; төмен түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Hyper-extending lower back, pressing forward instead of overhead, asymmetrical lockout.',
        'common_mistakes_ru': 'Сильный прогиб в пояснице, выжимание веса вперед вместо положения над головой, асимметричный жим.',
        'common_mistakes_kk': 'Белдің шамадан тыс қайқаюы, салмақты бастан асырмай алға қарай итеру, қолдардың біркелкі жазылмауы.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.5 - 3.2 meters',
        'camera_distance_ru': '2.5 - 3.2 метра',
        'camera_distance_kk': '2.5 - 3.2 метр',
        'body_visibility_en': 'Full upper body and full overhead arm reach must be in frame',
        'body_visibility_ru': 'Верхняя часть тела и вытянутые вверх руки должны полностью помещаться в кадр',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі мен жоғары көтерілген қолдар толық көрінуі керек',
        'camera_instructions_en': 'Position camera directly facing you at chest height so full overhead arm extension is framed.',
        'camera_instructions_ru': 'Установите камеру спереди на уровне груди на расстоянии 3 метров, чтобы верхняя точка вытянутых рук была в кадре.',
        'camera_instructions_kk': 'Камераны алдыңыздан кеуде деңгейіне 3 метр қашықтыққа қойыңыз, қолдар толық жазылғанда кадрдан шығып кетпеуі керек.',
        'youtube_id': '2yjwHevKmT0',
        'video_url': 'https://www.youtube.com/watch?v=2yjwHevKmT0',
        'ideal_rom_degrees': 165.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': True,
    },
    # 32. Standard Pull-up (AI Supported)
    {
        'id': 32,
        'category_id': 3,
        'category_name': 'Lats',
        'slug': 'pullup',
        'name': 'Standard Pull-up',
        'name_en': 'Standard Pull-up',
        'name_ru': 'Подтягивания на перекладине',
        'name_kk': 'Турникке тартылу',
        'target_muscles': 'Latissimus Dorsi, Teres Major, Biceps',
        'target_muscles_en': 'Latissimus Dorsi, Rhomboids, Biceps Brachii',
        'target_muscles_ru': 'Широчайшие мышцы спины, ромбовидные, бицепс',
        'target_muscles_kk': 'Арқаның жалпақ бұлшықеттері, ромб тәрізді, бицепс',
        'secondary_muscles_en': 'Lower Trapezius, Forearms, Core',
        'secondary_muscles_ru': 'Трапеция, предплечья, кор',
        'secondary_muscles_kk': 'Трапеция, білек, кор',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight / Pull-up Bar',
        'equipment_ru': 'Свой вес / Перекладина',
        'equipment_kk': 'Өз салмағы / Турник',
        'difficulty': 'Advanced',
        'difficulty_en': 'Advanced',
        'difficulty_ru': 'Продвинутый',
        'difficulty_kk': 'Жоғары',
        'description': 'The gold standard bodyweight vertical pulling movement testing relative back strength and scapular depression.',
        'description_en': 'Vertical pulling gold standard evaluating lat recruitment, scapular depression, and core stability.',
        'description_ru': 'Золотой стандарт вертикальной тяги для развития широчайших мышц спины и силы хвата.',
        'description_kk': 'Арқаның жалпақ бұлшықеттері мен қол күшін дамытатын вертикаль тартудың негізгі жаттығуы.',
        'starting_position_en': 'Hang from the bar with an overhand grip slightly wider than shoulder-width. Arms fully extended.',
        'starting_position_ru': 'Вис на перекладине прямым хватом чуть шире плеч, руки полностью выпрямлены, тело неподвижно.',
        'starting_position_kk': 'Турникте иықтан сәл кеңірек ұстап еркін салбырап тұрыңыз, қолдар толық жазылған.',
        'instructions_en': '1. Retract and depress your shoulder blades.\n2. Drive elbows down toward your hips while pulling chest to the bar.\n3. Pull until your chin clearly clears the bar.\n4. Lower with full control back to a complete dead hang.',
        'instructions_ru': '1. Начните движение со сведения и опускания лопаток вниз.\n2. Направляйте локти вниз к талии, подтягивая грудь к перекладине.\n3. Подтягивайтесь до тех пор, пока подбородок не окажется выше перекладины.\n4. Плавно опуститесь в исходное положение полного виса.',
        'instructions_kk': '1. Жауырыныңызды төмен қарай жиырып қозғалысты бастаңыз.\n2. Шынтақты төмен бағыттап, кеудеңізді турникке қарай тартыңыз.\n3. Иегіңіз турниктен асқанша жоғары көтеріліңіз.\n4. Баяу толық созылған қалыпқа дейін төмен түсіңіз.',
        'breathing_en': 'Exhale as you pull upward; inhale as you lower yourself under control.',
        'breathing_ru': 'Выдох при подтягивании вверх; вдох при плавном опускании вниз.',
        'breathing_kk': 'Жоғары тартылғанда тыныс шығарыңыз; төмен түскенде тыныс алыңыз.',
        'common_mistakes_en': 'Kipping legs, half repetitions, rounded shoulders at top, failure to reach full lockout at bottom.',
        'common_mistakes_ru': 'Рывки ногами (киппинг), неполная амплитуда, задирание плеч к ушам, отсутствие полного виса внизу.',
        'common_mistakes_kk': 'Аяқпен сермеп көтерілу (киппинг), жартылай тартылу, иықты құлаққа жақындату, төменде қолды толық жазбау.',
        'camera_angle_en': 'Back View or Side View',
        'camera_angle_ru': 'Вид сзади или сбоку',
        'camera_angle_kk': 'Артқы немесе бүйір көрініс',
        'camera_height_en': 'Chest / Mid-Body Height',
        'camera_height_ru': 'На уровне груди / корпуса',
        'camera_height_kk': 'Кеуде / дене деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Pull-up bar and full torso must be clearly visible',
        'body_visibility_ru': 'Турник и корпус атлета должны полностью помещаться в кадр',
        'body_visibility_kk': 'Турник пен атлеттің денесі толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera behind or slightly angled to the side to analyze scapular symmetry.',
        'camera_instructions_ru': 'Установите камеру сзади или сбоку на расстоянии 3 метров для точной оценки симметрии лопаток.',
        'camera_instructions_kk': 'Жауырын симметриясын бақылау үшін камераны артыңыздан 3 метр қашықтыққа қойыңыз.',
        'youtube_id': 'eGo4IYlb45g',
        'video_url': 'https://www.youtube.com/watch?v=eGo4IYlb45g',
        'ideal_rom_degrees': 140.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': True,
    }
]
