# -*- coding: utf-8 -*-
import json
import os

from categories_data import CATEGORIES
from exercises_part1 import EXERCISES_PART1
from exercises_part1_back import EXERCISES_BACK
from exercises_part2 import EXERCISES_PART2
from exercises_part3 import EXERCISES_PART3
from exercises_part4_core import EXERCISES_CORE
from exercises_part4_legs import EXERCISES_LEGS
from exercises_part5 import EXERCISES_PART5
from additional_exercises import ADDITIONAL_EXERCISES

# Additional rich exercises to complete full 60+ catalog across all equipment & categories
EXTRA_EXERCISES = [
    # Chest
    {
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'resistance_band_pushup',
        'name': 'Resistance Band Push-up',
        'name_en': 'Resistance Band Push-up',
        'name_ru': 'Отжимания с фитнес-резинкой',
        'name_kk': 'Резеңке таспамен сығылу',
        'target_muscles': 'Pectoralis Major, Triceps',
        'target_muscles_en': 'Pectoralis Major, Triceps Brachii',
        'target_muscles_ru': 'Большая грудная, трицепс',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті, трицепс',
        'secondary_muscles_en': 'Core, Anterior Deltoids',
        'secondary_muscles_ru': 'Мышцы кора, передняя дельта',
        'secondary_muscles_kk': 'Кор, алдыңғы дельта',
        'equipment': 'Resistance Bands',
        'equipment_en': 'Resistance Band',
        'equipment_ru': 'Фитнес-резинка',
        'equipment_kk': 'Резеңке таспа',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Accommodating resistance push-up increasing lockout chest tension.',
        'description_en': 'Accommodating resistance push-up increasing pectoral lockout tension.',
        'description_ru': 'Отжимания с дополнительным нарастающим сопротивлением резиновой ленты в верхней точке.',
        'description_kk': 'Жоғарғы нүктеде кеудеге түсетін салмақты арттыратын резеңкемен сығылу.',
        'starting_position_en': 'Loop resistance band across upper back and hold ends under palms in high plank.',
        'starting_position_ru': 'Накиньте резинку на верх спины, прижмите концы ладонями к полу в упоре лежа.',
        'starting_position_kk': 'Резеңкені арқаға кигізіп, екі ұшын алақанмен еденге басып планкаға тұрыңыз.',
        'instructions_en': '1. Lower chest under control to floor against reducing band tension.\n2. Drive powerfully upward through increasing band resistance to full lockout.\n3. Keep core rigid throughout.',
        'instructions_ru': '1. Плавно опуститесь к полу.\n2. Мощно выжмите себя вверх против возрастающего сопротивления ленты.\n3. Держите корпус ровно.',
        'instructions_kk': '1. Кеудені еденге баяу түсіріңіз.\n2. Резеңке қарсылығына қарсы жоғары қарай күшпен итеріліңіз.\n3. Денені түзу ұстаңыз.',
        'breathing_en': 'Inhale down; exhale powerfully on press.',
        'breathing_ru': 'Вдох вниз; мощный выдох вверх.',
        'breathing_kk': 'Төменде тыныс алыңыз; жоғарыда тыныс шығарыңыз.',
        'common_mistakes_en': 'Sagging hips, letting band slip off back.',
        'common_mistakes_ru': 'Провисание таза, соскальзывание ленты.',
        'common_mistakes_kk': 'Белдің салбырауы, резеңкенің сырғып кетуі.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Floor Level',
        'camera_height_ru': 'На уровне пола',
        'camera_height_kk': 'Еден деңгейінде',
        'camera_distance_en': '2.5 meters',
        'camera_distance_ru': '2.5 метра',
        'camera_distance_kk': '2.5 метр',
        'body_visibility_en': 'Full body plank profile in frame',
        'body_visibility_ru': 'Тело в планке полностью в кадре',
        'body_visibility_kk': 'Планкадағы толық дене көрінуі керек',
        'camera_instructions_en': 'Position camera horizontally at ground level.',
        'camera_instructions_ru': 'Установите камеру на полу сбоку.',
        'camera_instructions_kk': 'Камераны еденге бүйір жақтан қойыңыз.',
        'youtube_id': 'IODxDxX7oi4',
        'video_url': 'https://www.youtube.com/watch?v=IODxDxX7oi4',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    # Back / Lats
    {
        'category_id': 2,
        'category_name': 'Back',
        'slug': 'seated_cable_row',
        'name': 'Seated Cable Row',
        'name_en': 'Seated Cable Row',
        'name_ru': 'Горизонтальная тяга блока к поясу сидя',
        'name_kk': 'Отырып блокты белге тарту',
        'target_muscles': 'Rhomboids, Latissimus Dorsi, Traps',
        'target_muscles_en': 'Rhomboids, Latissimus Dorsi, Middle Trapezius',
        'target_muscles_ru': 'Ромбовидные, широчайшие, средняя трапеция',
        'target_muscles_kk': 'Ромб тәрізді, жалпақ бұлшықеттер, трапеция',
        'secondary_muscles_en': 'Biceps Brachii, Posterior Deltoids',
        'secondary_muscles_ru': 'Бицепсы, задние дельты',
        'secondary_muscles_kk': 'Бицепстер, артқы дельталар',
        'equipment': 'Cables',
        'equipment_en': 'Seated Cable Row Machine',
        'equipment_ru': 'Блочный тренажер горизонтальной тяги',
        'equipment_kk': 'Көлденең блокты тарту тренажеры',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Horizontal cable row building mid-back thickness, posture, and scapular retraction.',
        'description_en': 'Horizontal pulling machine exercise developing dense mid-back musculature and scapular retraction.',
        'description_ru': 'Базовое движение на блоке для развития толщины середины спины и ровной осанки.',
        'description_kk': 'Арқаның ортаңғы бөлігін қалыңдатуға және жауырынды жиыруға арналған жаттығу.',
        'starting_position_en': 'Sit with feet on footrests, knees slightly bent, back straight, holding V-handle with arms extended.',
        'starting_position_ru': 'Сядьте, упритесь стопами в подставки, колени чуть согнуты. Спина прямая, руки вытянуты вперед.',
        'starting_position_kk': 'Тіреуішке аяқты қойып отырыңыз, тізе сәл бүгілген. Арқа түзу, қол алға созылған.',
        'instructions_en': '1. Pull handle into lower abdomen while driving elbows back.\n2. Retract shoulder blades firmly and pause 1 second.\n3. Release slowly forward to a full lat stretch without excessive forward rounding.',
        'instructions_ru': '1. Тяните рукоять к низу живота, уводя локти назад.\n2. Мощно сведите лопатки и удержите 1 секунду.\n3. Плавно вернитесь вперед до растяжения широчайших.',
        'instructions_kk': '1. Шынтақты артқа бағыттап, тұтқаны іштің төменгі жағына тартыңыз.\n2. Жауырынды 1 секунд жиырып ұстаңыз.\n3. Қолды баяу алға созып бастапқы қалыпқа қайтыңыз.',
        'breathing_en': 'Exhale on the pull; inhale as weight extends forward.',
        'breathing_ru': 'Выдох при тяге к себе; вдох при возврате вперед.',
        'breathing_kk': 'Өзіңізге тартқанда тыныс шығарыңыз; алға жібергенде тыныс алыңыз.',
        'common_mistakes_en': 'Rocking excessively back and forth with lower back, shrugging shoulders up.',
        'common_mistakes_ru': 'Сильная раскачка корпусом вперед-назад, подъем плеч к ушам.',
        'common_mistakes_kk': 'Денемен алға-артқа қатты шайқалу, иықты көтеру.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.5 meters',
        'camera_distance_ru': '2.5 метра',
        'camera_distance_kk': '2.5 метр',
        'body_visibility_en': 'Torso, machine, and cable path must be framed',
        'body_visibility_ru': 'Корпус, тренажер и трос в кадре',
        'body_visibility_kk': 'Дене, тренажер және трос анық көрінуі керек',
        'camera_instructions_en': 'Position camera from the side to check upright spine neutrality.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля неподвижности поясницы.',
        'camera_instructions_kk': 'Белдің түзулігін бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'GZbfZ033f74',
        'video_url': 'https://www.youtube.com/watch?v=GZbfZ033f74',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    # Shoulders
    {
        'category_id': 6,
        'category_name': 'Shoulders',
        'slug': 'arnold_press',
        'name': 'Dumbbell Arnold Press',
        'name_en': 'Dumbbell Arnold Press',
        'name_ru': 'Жим Арнольда с гантелями',
        'name_kk': 'Арнольд жимі (гантельмен)',
        'target_muscles': 'Anterior & Lateral Deltoids',
        'target_muscles_en': 'Anterior & Lateral Deltoids',
        'target_muscles_ru': 'Передняя и средняя дельтовидные мышцы',
        'target_muscles_kk': 'Алдыңғы және ортаңғы дельталар',
        'secondary_muscles_en': 'Triceps Brachii, Upper Traps',
        'secondary_muscles_ru': 'Трицепс, верх трапеции',
        'secondary_muscles_kk': 'Трицепс, жоғарғы трапеция',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells & Bench',
        'equipment_ru': 'Гантели и скамья',
        'equipment_kk': 'Гантельдер және орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Rotational overhead shoulder press hitting all 3 deltoid heads through continuous rotation.',
        'description_en': 'Rotational overhead shoulder press hitting anterior and lateral deltoid heads.',
        'description_ru': 'Жимовое упражнение с вращением кистей для комплексной проработки всех пучков дельт.',
        'description_kk': 'Қолды айналдыра көтеретін иықтың барлық бөліктерін дамытатын жаттығу.',
        'starting_position_en': 'Sit with dumbbells at chest height, palms facing toward you (supinated), elbows tucked in.',
        'starting_position_ru': 'Сядьте, гантели перед грудью, ладони развернуты к себе, локти прижаты к корпусу.',
        'starting_position_kk': 'Отырып, гантельдерді кеуде алдында ұстаңыз, алақан өзіңізге қараған.',
        'instructions_en': '1. Press dumbbells upward while rotating wrists outwards 180 degrees.\n2. At top lockout, palms face forward.\n3. Reverse rotation smoothly on descent back to starting position.',
        'instructions_ru': '1. Выжимайте гантели вверх, одновременно разворачивая кисти наружу на 180°.\n2. В верхней точке ладони смотрят вперед.\n3. Плавно вернитесь вниз с обратным разворотом кистей.',
        'instructions_kk': '1. Гантельдерді жоғары көтере отырып, білекті 180 градусқа сыртқа бұрыңыз.\n2. Жоғарғы нүктеде алақан алға қарайды.\n3. Бастапқы қалыпқа баяу қайтыңыз.',
        'breathing_en': 'Exhale on the upward rotational press; inhale on descent.',
        'breathing_ru': 'Выдох при жиме вверх; вдох при опускании.',
        'breathing_kk': 'Жоғары көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Jerking dumbbells, overarching lower back, rotating too late at the top.',
        'common_mistakes_ru': 'Резкие рывки, сильный прогиб в пояснице, запоздалый разворот кистей.',
        'common_mistakes_kk': 'Жұлқып көтеру, белді қайқайту, білекті кеш бұру.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.5 meters',
        'camera_distance_ru': '2.5 метра',
        'camera_distance_kk': '2.5 метр',
        'body_visibility_en': 'Upper body, arms, and overhead reach in frame',
        'body_visibility_ru': 'Верхняя часть тела и руки над головой в кадре',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі мен көтерілген қолдар көрінуі керек',
        'camera_instructions_en': 'Position camera directly in front to observe bilateral wrist rotation symmetry.',
        'camera_instructions_ru': 'Установите камеру спереди для контроля синхронности вращения кистей.',
        'camera_instructions_kk': 'Екі қолдың бірдей айналуын көру үшін камераны алдыңыздан қойыңыз.',
        'youtube_id': '2yjwHevKmT0',
        'video_url': 'https://www.youtube.com/watch?v=2yjwHevKmT0',
        'ideal_rom_degrees': 160.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    # Quadriceps & Legs
    {
        'category_id': 19,
        'category_name': 'Quadriceps',
        'slug': 'goblet_squat',
        'name': 'Dumbbell Goblet Squat',
        'name_en': 'Dumbbell Goblet Squat',
        'name_ru': 'Гоблет-приседания с гантелью / гирей',
        'name_kk': 'Гоблет-отыру (гантельмен / гирмен)',
        'target_muscles': 'Quadriceps, Glutes, Core',
        'target_muscles_en': 'Quadriceps, Glutes, Core Stabilizers',
        'target_muscles_ru': 'Квадрицепсы, ягодицы, кор',
        'target_muscles_kk': 'Квадрицепстер, бөксе, кор',
        'secondary_muscles_en': 'Adductors, Calves',
        'secondary_muscles_ru': 'Приводящие, икры',
        'secondary_muscles_kk': 'Жанастырушы, балтыр',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbell / Kettlebell',
        'equipment_ru': 'Гантель / гиря',
        'equipment_kk': 'Гантель / гир',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Front-loaded squat teaching upright torso mechanics and deep hip mobility.',
        'description_en': 'Front-loaded squat variation reinforcing upright torso mechanics and deep hip mobility.',
        'description_ru': 'Отличное упражнение для отработки глубокого приседа с вертикальной спиной и подвижности таза.',
        'description_kk': 'Арқаны тік ұстап терең отыруды үйрететін тиімді жаттығу.',
        'starting_position_en': 'Hold dumbbell vertically against chest with both hands under bell. Feet shoulder-width, toes turned out 15°.',
        'starting_position_ru': 'Удерживайте гантель вертикально обеими руками у груди. Стопы на ширине плеч, носки развернуты на 15°.',
        'starting_position_kk': 'Гантельді екі қолмен кеуде тұсында тік ұстаңыз. Аяқ иық енінде, ұшы 15° сыртқа.',
        'instructions_en': '1. Sit down between knees, keeping chest tall and elbows inside knees at bottom.\n2. Descend until thighs pass parallel.\n3. Drive through midfoot to stand up tall.',
        'instructions_ru': '1. Опускайтесь вниз между коленями, держа спину вертикально.\n2. Присядьте до параллели или глубже.\n3. Оттолкнитесь стопами и вернитесь вверх.',
        'instructions_kk': '1. Арқаны тік ұстап, тізелер арасына қарай отырыңыз.\n2. Сан параллельден төмен түскенше отырыңыз.\n3. Табанмен итеріліп, тік тұрыңыз.',
        'breathing_en': 'Inhale down; exhale up.',
        'breathing_ru': 'Вдох вниз; выдох вверх.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; көтерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Rounding upper back, letting elbows flare outside knees, rising onto toes.',
        'common_mistakes_ru': 'Скругление спины, завал на носки, сведение коленей.',
        'common_mistakes_kk': 'Арқаны бүкірейту, өкшені көтеру, тізені ішке майыстыру.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Hip Height',
        'camera_height_ru': 'На уровне бедер',
        'camera_height_kk': 'Жамбас деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full body from head to feet in frame',
        'body_visibility_ru': 'Все тело в полный рост в кадре',
        'body_visibility_kk': 'Бастан аяққа дейін толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side to check upright spine and knee depth.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля вертикали спины и глубины приседа.',
        'camera_instructions_kk': 'Арқа түзулігі мен отыру тереңдігін көру үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'aclH2T8NY5I',
        'video_url': 'https://www.youtube.com/watch?v=aclH2T8NY5I',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    # Leg Extension Machine
    {
        'category_id': 19,
        'category_name': 'Quadriceps',
        'slug': 'leg_extension_machine',
        'name': 'Leg Extension Machine',
        'name_en': 'Leg Extension Machine',
        'name_ru': 'Разгибание ног в тренажере сидя',
        'name_kk': 'Тренажерде отырып аяқты жазу (квадрицепс)',
        'target_muscles': 'Quadriceps (Rectus Femoris, Vastus Lateralis)',
        'target_muscles_en': 'Quadriceps (Direct Isolation)',
        'target_muscles_ru': 'Квадрицепсы (изолированная нагрузка)',
        'target_muscles_kk': 'Квадрицепстер (оқшауланған күш)',
        'secondary_muscles_en': 'Tibialis Anterior',
        'secondary_muscles_ru': 'Передняя большеберцовая мышца',
        'secondary_muscles_kk': 'Алдыңғы асықты жілік бұлшықеті',
        'equipment': 'Machines',
        'equipment_en': 'Leg Extension Machine',
        'equipment_ru': 'Тренажер для разгибания ног',
        'equipment_kk': 'Аяқты жазу тренажеры',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Pure isolated knee extension focusing high tension on quadriceps teardrop and rectus femoris.',
        'description_en': 'Pure isolated knee extension focusing high tension on all 4 quadriceps heads.',
        'description_ru': 'Изолированное упражнение на тренажере для детальной прорисовки и накачки квадрицепсов.',
        'description_kk': 'Квадрицепсті оқшаулап қатайтуға және пішінін айқындауға арналған тренажер жаттығуы.',
        'starting_position_en': 'Sit with back against pad, knees aligned with machine pivot point. Shin pad rests just above ankles.',
        'starting_position_ru': 'Сядьте, плотно прижав спину к подушке. Колени на оси вращения тренажера. Валик на нижней части голени.',
        'starting_position_kk': 'Арқаны нық басып отырыңыз. Тізе тренажер осімен бір сызықта. Тіреуіш толарсақ үстінде.',
        'instructions_en': '1. Grip handles on the sides.\n2. Extend legs smoothly until knees are nearly fully extended.\n3. Hold peak contraction for 1 second.\n4. Lower weight under 2-second control without letting stack slam.',
        'instructions_ru': '1. Возьмитесь за боковые рукояти.\n2. Разгибайте ноги вверх силой квадрицепсов.\n3. Зафиксируйте пиковое напряжение вверху на 1 секунду.\n4. Плавно опустите ноги за 2 секунды.',
        'instructions_kk': '1. Бүйірлік тұтқаларды ұстаңыз.\n2. Квадрицепс күшімен аяқты жоғары қарай толық жазыңыз.\n3. Жоғарғы нүктеде 1 секунд қатайтып ұстаңыз.\n4. Баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale on extension; inhale on lowering.',
        'breathing_ru': 'Выдох при разгибании; вдох при опускании.',
        'breathing_kk': 'Жазғанда тыныс шығарыңыз; бүккенде тыныс алыңыз.',
        'common_mistakes_en': 'Kicking weight up with momentum, lifting hips off seat, slamming weights.',
        'common_mistakes_ru': 'Резкие рывки ногами, отрыв таза от сиденья, бросок веса.',
        'common_mistakes_kk': 'Аяқты сермеп көтеру, бөксені орындықтан көтеру, салмақты тастай салу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Knee Height',
        'camera_height_ru': 'На уровне коленей',
        'camera_height_kk': 'Тізе деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Machine, legs, and knee angle in frame',
        'body_visibility_ru': 'Тренажер, ноги и угол коленей в кадре',
        'body_visibility_kk': 'Тренажер, аяқтар және тізе бұрышы көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side to verify full knee extension and steady cadence.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля полного выпрямления ног.',
        'camera_instructions_kk': 'Аяқтың толық жазылуын бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'YyvSfV510ok',
        'video_url': 'https://www.youtube.com/watch?v=YyvSfV510ok',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    # Cardio: Mountain Climbers
    {
        'category_id': 25,
        'category_name': 'Cardio',
        'slug': 'mountain_climbers',
        'name': 'Speed Mountain Climbers',
        'name_en': 'Speed Mountain Climbers',
        'name_ru': 'Упражнение Скалолаз (Mountain Climbers)',
        'name_kk': 'Тауға өрмелеуші жаттығуы (Mountain Climbers)',
        'target_muscles': 'Cardiovascular System, Core, Hip Flexors',
        'target_muscles_en': 'Cardiovascular Endurance, Core, Hip Flexors',
        'target_muscles_ru': 'Сердечно-сосудистая система, кор, сгибатели бедер',
        'target_muscles_kk': 'Жүрек-қан тамырлары, кор, жамбас бұлшықеттері',
        'secondary_muscles_en': 'Shoulders, Quadriceps, Calves',
        'secondary_muscles_ru': 'Плечи, квадрицепсы, икры',
        'secondary_muscles_kk': 'Иық, квадрицепс, балтыр',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight',
        'equipment_ru': 'Свой вес',
        'equipment_kk': 'Өз салмағы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'High-tempo dynamic plank drill firing up heart rate and core stabilizers.',
        'description_en': 'High-intensity dynamic plank exercise boosting cardiovascular conditioning and core endurance.',
        'description_ru': 'Динамическое упражнение в планке для интенсивного сжигания калорий и укрепления пресса.',
        'description_kk': 'Жүрек соғысын жеделдетуге және іш бұлшықеттерін қатайтуға арналған қарқынды планка жаттығуы.',
        'starting_position_en': 'Start in a rigid high plank position with hands under shoulders, glutes tight, neutral head.',
        'starting_position_ru': 'Упор лежа на прямых руках, ладони под плечами, тело образует прямую линию.',
        'starting_position_kk': 'Қолға сүйеніп түзу планкаға тұрыңыз, алақан иық астында, дене түзу.',
        'instructions_en': '1. Drive right knee rapidly forward toward chest without letting hips bounce up.\n2. Quickly switch legs in a running cadence, driving left knee forward as right returns.\n3. Maintain rapid, rhythmic pace while keeping shoulders stable over hands.',
        'instructions_ru': '1. Быстро подтяните правое колено к груди, не задирая таз вверх.\n2. В прыжке смените ноги, подтягивая левое колено к груди.\n3. Сохраняйте быстрый непрерывный беговой ритм, удерживая плечи над ладонями.',
        'instructions_kk': '1. Жамбасты көтермей, оң тізені кеудеге қарай жылдам тартыңыз.\n2. Аяқтарды кезек-кезек ауыстырып, жүгіру ырғағымен сол тізені тартыңыз.\n3. Денені түзу ұстап, қарқынды ырғақты сақтаңыз.',
        'breathing_en': 'Rhythmic continuous breathing synchronized with alternating knee drives.',
        'breathing_ru': 'Ритмичное частое дыхание в такт смене ног.',
        'breathing_kk': 'Аяқ қозғалысымен бірге ырғақты тыныс алыңыз.',
        'common_mistakes_en': 'Piking hips up toward ceiling, bouncing upper body, letting hands slide forward.',
        'common_mistakes_ru': 'Задирание таза вверх домиком, подпрыгивание корпусом, увод плеч назад от ладоней.',
        'common_mistakes_kk': 'Жамбасты жоғары көтеріп кету, денені селкілдету.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Floor Level',
        'camera_height_ru': 'На уровне пола',
        'camera_height_kk': 'Еден деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Full lateral plank profile and running legs must be in frame',
        'body_visibility_ru': 'Тело в планке сбоку и ноги в движении должны быть в кадре',
        'body_visibility_kk': 'Планкадағы толық дене мен аяқ қозғалысы анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera horizontally at ground level to monitor flat back alignment.',
        'camera_instructions_ru': 'Установите камеру на полу сбоку для контроля стабильной высоты таза.',
        'camera_instructions_kk': 'Жамбас биіктігінің тұрақтылығын көру үшін камераны еденге бүйірден қойыңыз.',
        'youtube_id': 'nmwgirgXLYM',
        'video_url': 'https://www.youtube.com/watch?v=nmwgirgXLYM',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 0.8,
        'analysis_supported': False,
    },
    {
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'incline_dumbbell_press',
        'name': 'Incline Dumbbell Bench Press',
        'name_en': 'Incline Dumbbell Bench Press',
        'name_ru': 'Жим гантелей на наклонной скамье',
        'name_kk': 'Көлбеу орындықта гантельдерді сығу',
        'target_muscles': 'Upper Pectoralis, Anterior Deltoid, Triceps',
        'target_muscles_en': 'Upper Pectoralis Major (Clavicular Head)',
        'target_muscles_ru': 'Верхняя часть груди (ключичная головка)',
        'target_muscles_kk': 'Кеуденің жоғарғы бөлігі',
        'secondary_muscles_en': 'Anterior Deltoids, Triceps Brachii',
        'secondary_muscles_ru': 'Передние дельты, трицепс',
        'secondary_muscles_kk': 'Алдыңғы дельталар, трицепс',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells & Incline Bench',
        'equipment_ru': 'Гантели и наклонная скамья',
        'equipment_kk': 'Гантельдер және көлбеу орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Upper pectoral pressing movement developing clavicular chest mass and shoulder stability.',
        'description_en': 'Incline pressing variation heavily loading the upper clavicular head of the pectoralis major.',
        'description_ru': 'Жим под углом 30-45 градусов, акцентирующий нагрузку на верхнюю ключичную часть грудных мышц.',
        'description_kk': 'Кеуде бұлшықетінің жоғарғы бөлігіне негізгі күш түсіретін 30-45 градус көлбеу жим.',
        'starting_position_en': 'Sit on a 30-45 degree incline bench with dumbbells resting on thighs. Kick dumbbells up to shoulder level and retract shoulder blades.',
        'starting_position_ru': 'Сядьте на наклонную скамью (30-45°), закиньте гантели к плечам, сведите лопатки и плотно упритесь стопами в пол.',
        'starting_position_kk': '30-45° көлбеу орындыққа отырып, гантельдерді иық деңгейіне көтеріп, жауырыныңызды жинаңыз.',
        'instructions_en': '1. Inhale and lower dumbbells with control until elbows reach approximately 90 degrees in line with mid-chest.\n2. Exhale and press dumbbells upward along a slight inward arc without clinking weights at the top.\n3. Keep your chest elevated and core braced throughout.',
        'instructions_ru': '1. На вдохе подконтрольно опустите гантели до угла около 90° в локтях.\n2. На выдохе мощно выжмите гантели вверх по плавной дуге.\n3. Не сводите гантели с ударом наверху, сохраняйте напряжение в груди.',
        'instructions_kk': '1. Тыныс алып, гантельдерді шынтақ 90° бұрышқа жеткенше баяу түсіріңіз.\n2. Тыныс шығарып, гантельдерді жоғары қарай күшпен сығыңыз.\n3. Жоғарғы нүктеде гантельдерді соғыстырмай, кеудені қатайтыңыз.',
        'breathing_en': 'Inhale during eccentric lowering; exhale forcefully on concentric upward press.',
        'breathing_ru': 'Вдох при плавном опускании; выдох при мощном жиме вверх.',
        'breathing_kk': 'Төмен түсіргенде тыныс алыңыз; жоғары сыққанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Setting bench angle too high (>45°) shifting load to delts, flaring elbows 90 degrees wide, bouncing weights.',
        'common_mistakes_ru': 'Слишком крутой угол скамьи (>45°), разведение локтей на 90°, отрыв поясницы.',
        'common_mistakes_kk': 'Орындық бұрышын тым тік қою (>45°), шынтақты шамадан тыс ашу, белді көтеру.',
        'camera_angle_en': 'Side View / 45° Front-Side View',
        'camera_angle_ru': 'Вид сбоку / 45° спереди-сбоку',
        'camera_angle_kk': 'Бүйірден / 45° алдыңғы-бүйірден көрініс',
        'camera_height_en': 'Bench Height (0.8 - 1.0 m)',
        'camera_height_ru': 'На уровне скамьи (0.8 - 1.0 м)',
        'camera_height_kk': 'Орындық деңгейінде (0.8 - 1.0 м)',
        'camera_distance_en': '2.5 - 3.0 meters',
        'camera_distance_ru': '2.5 - 3.0 метра',
        'camera_distance_kk': '2.5 - 3.0 метр',
        'body_visibility_en': 'Full torso, elbows, forearms, and dumbbell trajectory visible throughout range',
        'body_visibility_ru': 'Торс, локти, предплечья и траектория гантелей полностью в кадре',
        'body_visibility_kk': 'Кеуде, шынтақтар және гантельдер қозғалысы толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side or 45-degree angle to verify elbow tuck angle and depth without occlusion.',
        'camera_instructions_ru': 'Установите камеру под углом 45 градусов для четкого отслеживания глубины опускания и угла локтей.',
        'camera_instructions_kk': 'Шынтақ бұрышы мен қозғалыс тереңдігін дәл көру үшін камераны 45 градус бұрышқа қойыңыз.',
        'youtube_id': '8iPEnn-ltC8',
        'video_url': 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'cable_fly',
        'name': 'Cable Chest Crossover / Fly',
        'name_en': 'Cable Chest Crossover / Fly',
        'name_ru': 'Сведение рук в кроссовере',
        'name_kk': 'Кроссоверде қолды қосу',
        'target_muscles': 'Pectoralis Major (Sternal & Clavicular)',
        'target_muscles_en': 'Pectoralis Major (Sternal & Clavicular Heads)',
        'target_muscles_ru': 'Большая грудная мышца (стернальная и ключичная части)',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті',
        'secondary_muscles_en': 'Anterior Deltoid, Biceps Brachii (Short Head)',
        'secondary_muscles_ru': 'Передняя дельта, короткая головка бицепса',
        'secondary_muscles_kk': 'Алдыңғы дельта, бицепс',
        'equipment': 'Cables',
        'equipment_en': 'Dual Cable Crossover Machine',
        'equipment_ru': 'Двублочный кроссовер',
        'equipment_kk': 'Қос блокты кроссовер',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Continuous tension isolation exercise providing peak contraction across the sternal chest line.',
        'description_en': 'Cable fly variation maintaining uninterrupted mechanical tension at both peak stretch and full contraction.',
        'description_ru': 'Изолирующее упражнение с постоянным натяжением троса для детальной проработки грудных мышц.',
        'description_kk': 'Кеуде бұлшықетін толық созып және жиыратын блокты оқшаулау жаттығуы.',
        'starting_position_en': 'Set pulleys at shoulder or chest height. Grasp D-handles, step forward into a staggered stance, and lean slightly forward.',
        'starting_position_ru': 'Установите блоки на уровне груди/плеч, возьмите рукояти, сделайте шаг вперед в разножку и наклоните корпус вперед.',
        'starting_position_kk': 'Блоктарды кеуде деңгейіне қойып, тұтқаларды ұстап, бір аяқпен алға қадам жасап тұрыңыз.',
        'instructions_en': '1. Inhale and open arms wide with a slight elbow bend until feeling a deep pectoral stretch.\n2. Exhale and bring handles together in front of chest in a hugging motion.\n3. Squeeze chest hard for 1 second at full contraction.',
        'instructions_ru': '1. На вдохе плавно разведите руки в стороны с легким изгибом в локтях.\n2. На выдохе сведите рукояти перед грудью по широкой дуге.\n3. Задержитесь в точке пикового сокращения на 1 секунду.',
        'instructions_kk': '1. Тыныс алып, шынтақты сәл бүгіп қолды жан-жаққа ашыңыз.\n2. Тыныс шығарып, құшақтау қозғалысымен тұтқаларды алға қосыңыз.\n3. Шыңғы нүктеде 1 секунд кеудені қатты қысыңыз.',
        'breathing_en': 'Inhale on opening; exhale on forceful chest squeeze.',
        'breathing_ru': 'Вдох при разведении; выдох при сведении рук.',
        'breathing_kk': 'Қолды ашқанда тыныс алыңыз; қосқанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Bending elbows into a press, excessive forward rocking momentum, letting shoulders roll forward.',
        'common_mistakes_ru': 'Превращение сведения в жим, раскачивание корпусом, сутулость плеч.',
        'common_mistakes_kk': 'Қозғалысты жимге айналдыру, денені шайқау, иықты алға шығару.',
        'camera_angle_en': 'Front View (0°) or 45° Angle',
        'camera_angle_ru': 'Вид спереди (0°) или под 45°',
        'camera_angle_kk': 'Алдыңғы көрініс (0°) немесе 45° бұрыш',
        'camera_height_en': 'Chest Level (1.2 - 1.4 m)',
        'camera_height_ru': 'На уровне груди (1.2 - 1.4 м)',
        'camera_height_kk': 'Кеуде деңгейінде (1.2 - 1.4 м)',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Both arms, shoulders, chest, and cable handles in full frame',
        'body_visibility_ru': 'Обе руки, плечи, грудь и тросы полностью в кадре',
        'body_visibility_kk': 'Екі қол, иықтар, кеуде және тұтқалар кадрда толық көрінуі керек',
        'camera_instructions_en': 'Position camera in front to capture bilateral arm symmetry and horizontal abduction angle.',
        'camera_instructions_ru': 'Установите камеру спереди для проверки симметрии сведения рук.',
        'camera_instructions_kk': 'Қолдардың бірдей жиырылуын тексеру үшін камераны тура алдыға қойыңыз.',
        'youtube_id': 'taI4XduLpTk',
        'video_url': 'https://www.youtube.com/watch?v=taI4XduLpTk',
        'ideal_rom_degrees': 85.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'category_id': 2,
        'category_name': 'Back',
        'slug': 'straight_arm_pulldown',
        'name': 'Straight-Arm Cable Pulldown',
        'name_en': 'Straight-Arm Cable Pulldown',
        'name_ru': 'Пулловер на верхнем блоке стоя (тяга прямыми руками)',
        'name_kk': 'Тұрып түзу қолмен жоғарғы блокты тарту',
        'target_muscles': 'Latissimus Dorsi, Teres Major',
        'target_muscles_en': 'Latissimus Dorsi, Teres Major, Posterior Deltoid',
        'target_muscles_ru': 'Широчайшие мышцы спины, большая круглая, задняя дельта',
        'target_muscles_kk': 'Арқаның жалпақ бұлшықеттері, үлкен дөңгелек бұлшықет',
        'secondary_muscles_en': 'Triceps (Long Head), Abdominals',
        'secondary_muscles_ru': 'Длинная головка трицепса, прямая мышца живота',
        'secondary_muscles_kk': 'Трицепстің ұзын басы, іш бұлшықеттері',
        'equipment': 'Cables',
        'equipment_en': 'Cable Pulley with Straight or Rope Bar',
        'equipment_ru': 'Верхний блок с прямой или канатной рукоятью',
        'equipment_kk': 'Түзу немесе арқан тұтқалы жоғарғы блок',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Pure lat isolation movement emphasizing humeral extension without biceps fatigue.',
        'description_en': 'Single-joint latissimus dorsi isolation bypassing arm fatigue.',
        'description_ru': 'Изолирующее движение для широчайших без участия сгибателей рук.',
        'description_kk': 'Бицепсті қатыстырмай, арқаның жалпақ бұлшықетін оқшаулап дамытатын тарту.',
        'starting_position_en': 'Stand 1 step back from high pulley, hinge hips slightly back (20°), arms extended overhead holding bar with soft elbows.',
        'starting_position_ru': 'Встаньте в шаге от блока, слегка наклоните корпус вперед (20°), руки выпрямлены вверх на грифе.',
        'starting_position_kk': 'Блоктан 1 қадам артқа тұрып, денені 20° алға еңкейтіп, қолды жоғары созыңыз.',
        'instructions_en': '1. Inhale and allow lats to fully stretch at eye level.\n2. Exhale and drive bar down in a wide arc directly to thighs using lats.\n3. Squeeze lats hard at bottom without bending elbows into a triceps pushdown.',
        'instructions_ru': '1. На вдохе почувствуйте растяжение широчайших мышц вверху.\n2. На выдохе мощно проведите рукоять по широкой дуге к бедрам за счет спины.\n3. Сожмите широчайшие внизу на 1 секунду.',
        'instructions_kk': '1. Тыныс алып, жоғарыда арқа бұлшықеттерінің созылуын сезініңіз.\n2. Тыныс шығарып, тұтқаны доға бойымен санға қарай тартыңыз.\n3. Төменде арқа бұлшықеттерін 1 секунд қатты қатайтыңыз.',
        'breathing_en': 'Inhale on upper stretch; exhale on sweep to hips.',
        'breathing_ru': 'Вдох при подъеме вверх; выдох при тяге к бедрам.',
        'breathing_kk': 'Қолды жоғары көтергенде тыныс алыңыз; төмен тартқанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Bending elbows into a triceps press, using torso swing momentum, overextending lower back.',
        'common_mistakes_ru': 'Сгибание рук в трицепс, раскачивание корпусом, прогиб в пояснице.',
        'common_mistakes_kk': 'Қолды шынтақтан бүгіп трицепске айналдыру, денені сермеу, белді шамадан тыс бүгу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Chest Height (1.2 m)',
        'camera_height_ru': 'На уровне груди (1.2 м)',
        'camera_height_kk': 'Кеуде деңгейінде (1.2 м)',
        'camera_distance_en': '2.5 meters',
        'camera_distance_ru': '2.5 метра',
        'camera_distance_kk': '2.5 метр',
        'body_visibility_en': 'Full lateral torso, arm sweep path, and hips in frame',
        'body_visibility_ru': 'Боковой профиль торса, траектория рук и таз полностью в кадре',
        'body_visibility_kk': 'Дененің бүйір бейнесі, қолдар қозғалысы және жамбас көрінуі керек',
        'camera_instructions_en': 'Position camera from the side to detect elbow stillness and spinal neutrality.',
        'camera_instructions_ru': 'Установите камеру сбоку для проверки неподвижности локтей и угла наклона корпуса.',
        'camera_instructions_kk': 'Шынтақтың қозғалмауын және арқаның түзулігін тексеру үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'CA4wWc_j8jY',
        'video_url': 'https://www.youtube.com/watch?v=CA4wWc_j8jY',
        'ideal_rom_degrees': 80.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'category_id': 3,
        'category_name': 'Biceps',
        'slug': 'preacher_curl',
        'name': 'Preacher Curl',
        'name_en': 'Preacher Curl',
        'name_ru': 'Сгибания на скамье Скотта',
        'name_kk': 'Скотт орындығында бицепсті бүгу',
        'target_muscles': 'Biceps Brachii (Short Head), Brachialis',
        'target_muscles_en': 'Biceps Brachii (Short Head Focus), Brachialis, Brachioradialis',
        'target_muscles_ru': 'Бицепс (короткая внутренняя головка), плечевая мышца',
        'target_muscles_kk': 'Бицепс (ішкі басы), иық бұлшықеті',
        'secondary_muscles_en': 'Forearm Flexors',
        'secondary_muscles_ru': 'Сгибатели предплечья',
        'secondary_muscles_kk': 'Білек бұлшықеттері',
        'equipment': 'Barbells',
        'equipment_en': 'EZ-Bar or Dumbbells & Preacher Bench',
        'equipment_ru': 'EZ-штанга или гантели со скамьей Скотта',
        'equipment_kk': 'EZ-штанга немесе гантельдер және Скотт орындығы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Strict bicep isolation preventing shoulder engagement and body momentum.',
        'description_en': 'Arm-supported bicep isolation maximizing tension on the lower and inner bicep head.',
        'description_ru': 'Строгая изоляция бицепса с фиксацией плеч на наклонной парте Скотта.',
        'description_kk': 'Иықты толық бекітіп, бицепсті оқшаулап дамытатын Скотт орындығындағы бүгу.',
        'starting_position_en': 'Sit with upper chest flush against preacher pad, triceps flat against inclined surface, gripping EZ-bar shoulder-width.',
        'starting_position_ru': 'Сядьте так, чтобы грудь прижималась к парте, а плечи и локти плотно лежали на наклонной подушке.',
        'starting_position_kk': 'Кеуде мен шынтақты көлбеу жастыққа нық тіреп, штанганы иық енімен ұстаңыз.',
        'instructions_en': '1. Inhale and lower bar under steady control until arms are almost fully extended (avoid hyperextension).\n2. Exhale and curl bar up toward shoulders by contracting biceps.\n3. Pause for a peak squeeze at top before lowering.',
        'instructions_ru': '1. На вдохе плавно опустите гриф почти до полного разгибания рук.\n2. На выдохе мощно согните руки в локтях за счет бицепса.\n3. Задержитесь в верхней точке на долю секунды.',
        'instructions_kk': '1. Тыныс алып, қолды толық жазылуға сәл жеткізбей баяу түсіріңіз.\n2. Тыныс шығарып, бицепс күшімен штанганы жоғары көтеріңіз.\n3. Жоғарғы нүктеде бицепсті қатты қатайтыңыз.',
        'breathing_en': 'Inhale during descent; exhale during bicep curl ascent.',
        'breathing_ru': 'Вдох при опускании; выдох при подъеме штанги.',
        'breathing_kk': 'Төмен түсіргенде тыныс алыңыз; жоғары бүккенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Lifting elbows off pad, bouncing out of bottom extension risking tendon strain, rounding shoulders.',
        'common_mistakes_ru': 'Отрыв локтей от парты, резкий рывок из нижней точки, сутулость.',
        'common_mistakes_kk': 'Шынтақты жастықтан көтеру, төменгі нүктеден жұлқып көтеру, арқаны бүкірейту.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Pad Height (0.9 m)',
        'camera_height_ru': 'На уровне парты (0.9 м)',
        'camera_height_kk': 'Парта деңгейінде (0.9 м)',
        'camera_distance_en': '2.0 - 2.5 meters',
        'camera_distance_ru': '2.0 - 2.5 метра',
        'camera_distance_kk': '2.0 - 2.5 метр',
        'body_visibility_en': 'Elbow contact point, forearm range, and head in clear view',
        'body_visibility_ru': 'Точка опоры локтей, траектория предплечий и голова в кадре',
        'body_visibility_kk': 'Шынтақ тірегі, білек қозғалысы және бас анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side to monitor elbow pad adherence and controlled terminal extension.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля фиксации локтей на парте.',
        'camera_instructions_kk': 'Шынтақтың партадан ажырамауын бақылау үшін камераны бүйірге қойыңыз.',
        'youtube_id': 'fIWP-FRFNU0',
        'video_url': 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
        'ideal_rom_degrees': 105.0,
        'normative_cadence_seconds': 2.8,
        'analysis_supported': False,
    },
    {
        'category_id': 4,
        'category_name': 'Triceps',
        'slug': 'skull_crushers',
        'name': 'Barbell Skull Crushers',
        'name_en': 'Barbell Skull Crushers (Lying Triceps Extension)',
        'name_ru': 'Французский жим лежа со штангой',
        'name_kk': 'Жатып французша жим',
        'target_muscles': 'Triceps Brachii (Long & Medial Heads)',
        'target_muscles_en': 'Triceps Brachii (Long, Medial, and Lateral Heads)',
        'target_muscles_ru': 'Трицепс (длинная, медиальная и латеральная головки)',
        'target_muscles_kk': 'Трицепстің барлық үш басы',
        'secondary_muscles_en': 'Anconeus, Forearm Extensors',
        'secondary_muscles_ru': 'Локтевая мышца, разгибатели предплечья',
        'secondary_muscles_kk': 'Шынтақ бұлшықеті, білек бұлшықеттері',
        'equipment': 'Barbells',
        'equipment_en': 'EZ-Bar or Straight Bar & Flat Bench',
        'equipment_ru': 'EZ-гриф или прямой гриф и горизонтальная скамья',
        'equipment_kk': 'EZ-штанга және жазық орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Mass-building triceps movement emphasizing the long head under eccentric stretch.',
        'description_en': 'Classic lying triceps extension maximizing eccentric stretch on the long head of the triceps.',
        'description_ru': 'Базовое изолирующее упражнение для трицепса с глубоким растяжением длинной головки.',
        'description_kk': 'Трицепстің ұзын басын терең созып, күшін арттыратын жатып орындайтын жаттығу.',
        'starting_position_en': 'Lie back on flat bench with EZ-bar held directly over forehead, upper arms angled slightly back (75-80° from horizontal).',
        'starting_position_ru': 'Лягте на горизонтальную скамью, выжмите EZ-гриф, слегка отклоните плечи назад к голове.',
        'starting_position_kk': 'Жазық орындыққа жатып, EZ-штанганы ұстап, шынтақты бастан сәл артқа еңкейтіңіз.',
        'instructions_en': '1. Inhale and hinge at elbows to lower bar smoothly down toward crown of head / hairline.\n2. Keep upper arms completely stationary throughout.\n3. Exhale and extend forearms back to starting lockout using triceps.',
        'instructions_ru': '1. На вдохе согните руки в локтях и опустите гриф к макушке или за голову.\n2. Удерживайте плечевые кости неподвижными.\n3. На выдохе мощно разогните руки в локтях силой трицепсов.',
        'instructions_kk': '1. Тыныс алып, шынтақты бүгіп, штанганы бастың төбесіне қарай баяу түсіріңіз.\n2. Иық сүйектерін қозғалтпай бекітіңіз.\n3. Тыныс шығарып, трицепс күшімен қолды толық жазыңыз.',
        'breathing_en': 'Inhale on lowering toward head; exhale on triceps extension.',
        'breathing_ru': 'Вдох при опускании ко лбу; выдох при разгибании рук.',
        'breathing_kk': 'Төмен түсіргенде тыныс алыңыз; жоғары жазғанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Flaring elbows outward, turning movement into a close-grip bench press, moving upper arms back and forth.',
        'common_mistakes_ru': 'Разведение локтей в стороны, превращение в жим узким хватом, раскачка плечами.',
        'common_mistakes_kk': 'Шынтақты екі жаққа ашу, тар жимге айналдыру, иықты алға-артқа қозғалту.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Bench Height (0.8 - 1.0 m)',
        'camera_height_ru': 'На уровне скамьи (0.8 - 1.0 м)',
        'camera_height_kk': 'Орындық деңгейінде (0.8 - 1.0 м)',
        'camera_distance_en': '2.0 - 2.5 meters',
        'camera_distance_ru': '2.0 - 2.5 метра',
        'camera_distance_kk': '2.0 - 2.5 метр',
        'body_visibility_en': 'Head, elbows, forearms, and bench in side profile',
        'body_visibility_ru': 'Голова, локти, предплечья и скамья в боковом профиле',
        'body_visibility_kk': 'Бас, шынтақтар, білектер және орындық толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera perpendicular to the bench to verify upper arm stillness.',
        'camera_instructions_ru': 'Установите камеру сбоку для отслеживания неподвижности плечевой кости.',
        'camera_instructions_kk': 'Иықтың қозғалмай тұруын қадағалау үшін камераны орындыққа перпендикуляр қойыңыз.',
        'youtube_id': 'd_KZxkY_0cM',
        'video_url': 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.8,
        'analysis_supported': False,
    },
    {
        'category_id': 25,
        'category_name': 'Cardio',
        'slug': 'high_knees',
        'name': 'High Knees',
        'name_en': 'High Knees Running in Place',
        'name_ru': 'Бег на месте с высоким подниманием бедра',
        'name_kk': 'Тізені жоғары көтеріп орнында жүгіру',
        'target_muscles': 'Quadriceps, Hip Flexors, Calves, Cardiovascular System',
        'target_muscles_en': 'Quadriceps, Iliopsoas (Hip Flexors), Gastrocnemius, Cardiovascular Endurance',
        'target_muscles_ru': 'Квадрицепсы, сгибатели бедра, икроножные, сердечно-сосудистая система',
        'target_muscles_kk': 'Квадрицепс, жамбасты бүккіш бұлшықеттер, балтыр, жүрек-қан тамырлар жүйесі',
        'secondary_muscles_en': 'Core, Glutes, Hamstrings',
        'secondary_muscles_ru': 'Мышцы кора, ягодичные',
        'secondary_muscles_kk': 'Кор бұлшықеттері, бөксе',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight Only',
        'equipment_ru': 'Только собственный вес',
        'equipment_kk': 'Өз салмағы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Dynamic high-intensity cardiovascular conditioning drill building hip power and sprint cadence.',
        'description_en': 'High-cadence plyometric running drill elevating heart rate and training hip flexor speed.',
        'description_ru': 'Интенсивное кардио-упражнение для развития частоты шага, укрепления сгибателей бедра и сжигания калорий.',
        'description_kk': 'Жүрек соғысын арттыратын, қадам жиілігін және жамбас күшін дамытатын кардио жаттығу.',
        'starting_position_en': 'Stand tall with feet hip-width apart, arms bent 90° in athletic sprinting posture, chest upright.',
        'starting_position_ru': 'Встаньте ровно, стопы на ширине таза, руки согнуты под 90° в спринтерской позиции, грудь расправлена.',
        'starting_position_kk': 'Тік тұрып, аяқты жамбас енімен қойыңыз, қолдарды 90° бүгіп жүгіру қалпына келтіріңіз.',
        'instructions_en': '1. Drive right knee up explosively to hip height (90° flexion) while pumping left arm forward.\n2. Land softly on ball of foot and immediately drive left knee up as right foot touches.\n3. Maintain rapid, rhythmic cadence keeping torso tall.',
        'instructions_ru': '1. Мощно вынесите правое колено вверх до уровня таза (90°), одновременно работая левой рукой.\n2. Мягко приземлитесь на носок и мгновенно вынесите левое колено вверх.\n3. Держите высокий темп и ровную осанку.',
        'instructions_kk': '1. Оң тізені жамбас деңгейіне (90°) дейін күшпен көтеріп, сол қолмен алға сермеңіз.\n2. Табанның ұшымен жұмсақ түсіп, бірден сол тізені жоғары көтеріңіз.\n3. Денені тік ұстап, жоғары қарқынды сақтаңыз.',
        'breathing_en': 'Rhythmic, deep diaphragmatic breathing synchronized with cadence.',
        'breathing_ru': 'Ритмичное глубокое дыхание в такт шагам.',
        'breathing_kk': 'Қадам ырғағына сай бірқалыпты терең тыныс алу.',
        'common_mistakes_en': 'Leaning torso backward, landing flat-footed on heels, failing to reach 90° knee height.',
        'common_mistakes_ru': 'Отклонение корпуса назад, приземление на пятки, недостаточный подъем коленей.',
        'common_mistakes_kk': 'Денені артқа еңкейту, өкшемен қатты түсу, тізені жеткіліксіз көтеру.',
        'camera_angle_en': 'Front View (0°) or Side View (90°)',
        'camera_angle_ru': 'Вид спереди (0°) или сбоку (90°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°) немесе бүйірден (90°)',
        'camera_height_en': 'Hip / Chest Level (1.0 - 1.2 m)',
        'camera_height_ru': 'На уровне таза / груди (1.0 - 1.2 м)',
        'camera_height_kk': 'Жамбас / кеуде деңгейінде (1.0 - 1.2 м)',
        'camera_distance_en': '2.5 - 3.0 meters',
        'camera_distance_ru': '2.5 - 3.0 метра',
        'camera_distance_kk': '2.5 - 3.0 метр',
        'body_visibility_en': 'Full standing body from head to floor in frame',
        'body_visibility_ru': 'Все тело от головы до пола полностью в кадре',
        'body_visibility_kk': 'Бастан еденге дейінгі бүкіл дене толық көрінуі керек',
        'camera_instructions_en': 'Position camera to capture hip flexion height and landing softness.',
        'camera_instructions_ru': 'Установите камеру так, чтобы видеть высоту подъема коленей и работу стопы.',
        'camera_instructions_kk': 'Тізенің көтерілу биіктігі мен аяқтың жұмсақ түсуін көру үшін камераны орнатыңыз.',
        'youtube_id': 'ZZZoCNMU48U',
        'video_url': 'https://www.youtube.com/watch?v=ZZZoCNMU48U',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 0.6,
        'analysis_supported': False,
    }
]

all_exercises = []
seen_slugs = set()

AI_SUPPORTED_SLUGS = {
    'squat', 'barbell_squat', 'goblet_squat',
    'pushup', 'push_up', 'push-up', 'resistance_band_pushup',
    'pullup', 'pull_up', 'pull-up', 'chinup', 'chin_up',
    'bicep_curl', 'bicep-curl', 'dumbbell_curl', 'barbell_bicep_curl', 'hammer_curl',
    'shoulder_press', 'overhead_press', 'military_press', 'arnold_press',
    'plank', 'forearm_plank', 'side_plank', 'copenhagen_plank',
    'lunge', 'bulgarian_split_squat', 'walking_lunges', 'split_squat',
    'lateral_raise', 'dumbbell_lateral_raise', 'cable_lateral_raise', 'side_lateral_raise'
}

# Combine lists in priority order
for ex_list in [ADDITIONAL_EXERCISES, EXERCISES_PART1, EXERCISES_BACK, EXERCISES_PART2, EXERCISES_PART3, EXERCISES_CORE, EXERCISES_LEGS, EXERCISES_PART5, EXTRA_EXERCISES]:
    for ex in ex_list:
        slug = ex['slug']
        if slug in AI_SUPPORTED_SLUGS:
            ex['analysis_supported'] = True
            ex['analysis_available'] = True
        if slug not in seen_slugs:
            seen_slugs.add(slug)
            all_exercises.append(ex)

# Re-index IDs consecutively
for i, ex in enumerate(all_exercises, start=1):
    ex['id'] = i

print(f'Catalog assembled: {len(CATEGORIES)} categories and {len(all_exercises)} exercises.')

# 1. Output frontend/src/services/exerciseData.ts
ts_content = 'import { Exercise, ExerciseCategory } from \'../types\';\n\nexport const FALLBACK_CATEGORIES: ExerciseCategory[] = ' + json.dumps(CATEGORIES, ensure_ascii=False, indent=2) + ';\n\nexport const FALLBACK_EXERCISES: Exercise[] = ' + json.dumps(all_exercises, ensure_ascii=False, indent=2) + ';\n'

with open('frontend/src/services/exerciseData.ts', 'w', encoding='utf-8') as f_ts:
    f_ts.write(ts_content)
print('Successfully generated frontend/src/services/exerciseData.ts')

# 2. Output supabase/migrations/20260831_expanded_exercise_library.sql
sql_lines = [
    '-- ==============================================================================',
    '-- SPORTX EXPANDED TRILINGUAL EXERCISE LIBRARY MIGRATION',
    '-- File: supabase/migrations/20260831_expanded_exercise_library.sql',
    '-- Description: 26 muscle group categories and complete trilingual exercises',
    '-- ==============================================================================',
    '',
    '-- 1. Ensure Table Schema has All Multi-language & Biomechanics Columns',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS name_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS name_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS name_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS description_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS description_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS description_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS starting_position_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS starting_position_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS starting_position_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS instructions_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS instructions_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS instructions_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS breathing_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS breathing_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS breathing_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS common_mistakes_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS common_mistakes_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS common_mistakes_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS target_muscles_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS target_muscles_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS target_muscles_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS secondary_muscles_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS secondary_muscles_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS secondary_muscles_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS equipment_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS equipment_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS equipment_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS difficulty_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS difficulty_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS difficulty_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_angle_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_angle_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_angle_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_height_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_height_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_height_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_distance_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_distance_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_distance_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS body_visibility_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS body_visibility_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS body_visibility_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_instructions_en TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_instructions_ru TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS camera_instructions_kk TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS youtube_id TEXT;',
    'ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS analysis_supported BOOLEAN DEFAULT FALSE;',
    '',
    '-- 2. Upsert All Categories',
    'INSERT INTO public.exercise_categories (id, name, slug, icon, display_order)',
    'VALUES'
]

cat_values = []
for c in CATEGORIES:
    cat_values.append('    (' + str(c['id']) + ', \'' + c['name'] + '\', \'' + c['slug'] + '\', \'' + c['icon_name'] + '\', ' + str(c['display_order']) + ')')
sql_lines.append(',\n'.join(cat_values))
sql_lines.append('ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, display_order = EXCLUDED.display_order;')
sql_lines.append('')
sql_lines.append('-- 3. Upsert All Exercises')

for ex in all_exercises:
    name_escaped = ex['name'].replace("'", "''")
    name_en = ex.get('name_en', ex['name']).replace("'", "''")
    name_ru = ex.get('name_ru', ex['name']).replace("'", "''")
    name_kk = ex.get('name_kk', ex['name']).replace("'", "''")
    desc_en = ex.get('description_en', ex.get('description', '')).replace("'", "''")
    desc_ru = ex.get('description_ru', ex.get('description', '')).replace("'", "''")
    desc_kk = ex.get('description_kk', ex.get('description', '')).replace("'", "''")
    instr_en = ex.get('instructions_en', ex.get('instructions', '')).replace("'", "''")
    instr_ru = ex.get('instructions_ru', ex.get('instructions', '')).replace("'", "''")
    instr_kk = ex.get('instructions_kk', ex.get('instructions', '')).replace("'", "''")
    target_en = ex.get('target_muscles_en', ex.get('target_muscles', '')).replace("'", "''")
    target_ru = ex.get('target_muscles_ru', ex.get('target_muscles', '')).replace("'", "''")
    target_kk = ex.get('target_muscles_kk', ex.get('target_muscles', '')).replace("'", "''")
    equip_en = ex.get('equipment_en', ex.get('equipment', 'Bodyweight')).replace("'", "''")
    equip_ru = ex.get('equipment_ru', ex.get('equipment', 'Bodyweight')).replace("'", "''")
    equip_kk = ex.get('equipment_kk', ex.get('equipment', 'Bodyweight')).replace("'", "''")
    mistakes_en = ex.get('common_mistakes_en', ex.get('common_mistakes', '')).replace("'", "''")
    mistakes_ru = ex.get('common_mistakes_ru', ex.get('common_mistakes', '')).replace("'", "''")
    mistakes_kk = ex.get('common_mistakes_kk', ex.get('common_mistakes', '')).replace("'", "''")
    yid = ex.get('youtube_id', '') or ''
    vurl = ex.get('video_url', '') or ''
    analysis_supp = 'TRUE' if ex.get('analysis_supported') else 'FALSE'
    
    sql_lines.append('INSERT INTO public.exercises (id, category_id, name, slug, name_en, name_ru, name_kk, description, description_en, description_ru, description_kk, target_muscle, target_muscles_en, target_muscles_ru, target_muscles_kk, equipment, equipment_en, equipment_ru, equipment_kk, difficulty, instructions_en, instructions_ru, instructions_kk, common_mistakes_en, common_mistakes_ru, common_mistakes_kk, youtube_id, video_url, analysis_supported, analysis_available)')
    sql_lines.append('VALUES (' + str(ex['id']) + ', ' + str(ex['category_id']) + ', \'' + name_escaped + '\', \'' + ex['slug'] + '\', \'' + name_en + '\', \'' + name_ru + '\', \'' + name_kk + '\', \'' + desc_en + '\', \'' + desc_en + '\', \'' + desc_ru + '\', \'' + desc_kk + '\', \'' + target_en + '\', \'' + target_en + '\', \'' + target_ru + '\', \'' + target_kk + '\', \'' + equip_en + '\', \'' + equip_en + '\', \'' + equip_ru + '\', \'' + equip_kk + '\', \'' + ex['difficulty'] + '\', \'' + instr_en + '\', \'' + instr_ru + '\', \'' + instr_kk + '\', \'' + mistakes_en + '\', \'' + mistakes_ru + '\', \'' + mistakes_kk + '\', \'' + yid + '\', \'' + vurl + '\', ' + analysis_supp + ', ' + analysis_supp + ')')
    sql_lines.append('ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, name_en = EXCLUDED.name_en, name_ru = EXCLUDED.name_ru, name_kk = EXCLUDED.name_kk, description_en = EXCLUDED.description_en, description_ru = EXCLUDED.description_ru, description_kk = EXCLUDED.description_kk, target_muscles_en = EXCLUDED.target_muscles_en, target_muscles_ru = EXCLUDED.target_muscles_ru, target_muscles_kk = EXCLUDED.target_muscles_kk, instructions_en = EXCLUDED.instructions_en, instructions_ru = EXCLUDED.instructions_ru, instructions_kk = EXCLUDED.instructions_kk, youtube_id = EXCLUDED.youtube_id, video_url = EXCLUDED.video_url, analysis_supported = EXCLUDED.analysis_supported;')
    sql_lines.append('')

with open('supabase/migrations/20260831_expanded_exercise_library.sql', 'w', encoding='utf-8') as f_sql:
    f_sql.write('\n'.join(sql_lines))
print('Successfully generated supabase/migrations/20260831_expanded_exercise_library.sql')
