
CATEGORIES = [
    {'id': 1, 'name': 'Chest', 'name_en': 'Chest', 'name_ru': 'Грудные мышцы', 'name_kk': 'Кеуде бұлшықеттері', 'slug': 'chest', 'icon_name': 'Dumbbell', 'display_order': 1},
    {'id': 2, 'name': 'Back', 'name_en': 'Back', 'name_ru': 'Спина', 'name_kk': 'Арқа', 'slug': 'back', 'icon_name': 'Shield', 'display_order': 2},
    {'id': 3, 'name': 'Lats', 'name_en': 'Lats', 'name_ru': 'Широчайшие мышцы', 'name_kk': 'Жалпақ бұлшықеттер', 'slug': 'lats', 'icon_name': 'Shield', 'display_order': 3},
    {'id': 4, 'name': 'Upper Back', 'name_en': 'Upper Back', 'name_ru': 'Верх спины', 'name_kk': 'Арқаның жоғарғы бөлігі', 'slug': 'upper_back', 'icon_name': 'Shield', 'display_order': 4},
    {'id': 5, 'name': 'Lower Back', 'name_en': 'Lower Back', 'name_ru': 'Поясница', 'name_kk': 'Бел бұлшықеттері', 'slug': 'lower_back', 'icon_name': 'Layers', 'display_order': 5},
    {'id': 6, 'name': 'Shoulders', 'name_en': 'Shoulders', 'name_ru': 'Плечи', 'name_kk': 'Иық', 'slug': 'shoulders', 'icon_name': 'Flame', 'display_order': 6},
    {'id': 7, 'name': 'Front Delts', 'name_en': 'Front Delts', 'name_ru': 'Передние дельты', 'name_kk': 'Алдыңғы дельталар', 'slug': 'front_delts', 'icon_name': 'Flame', 'display_order': 7},
    {'id': 8, 'name': 'Lateral Delts', 'name_en': 'Lateral Delts', 'name_ru': 'Средние дельты', 'name_kk': 'Ортаңғы дельталар', 'slug': 'lateral_delts', 'icon_name': 'Flame', 'display_order': 8},
    {'id': 9, 'name': 'Rear Delts', 'name_en': 'Rear Delts', 'name_ru': 'Задние дельты', 'name_kk': 'Артқы дельталар', 'slug': 'rear_delts', 'icon_name': 'Flame', 'display_order': 9},
    {'id': 10, 'name': 'Biceps', 'name_en': 'Biceps', 'name_ru': 'Бицепс', 'name_kk': 'Бицепс', 'slug': 'biceps', 'icon_name': 'Zap', 'display_order': 10},
    {'id': 11, 'name': 'Triceps', 'name_en': 'Triceps', 'name_ru': 'Трицепс', 'name_kk': 'Трицепс', 'slug': 'triceps', 'icon_name': 'Flame', 'display_order': 11},
    {'id': 12, 'name': 'Forearms', 'name_en': 'Forearms', 'name_ru': 'Предплечья', 'name_kk': 'Білек', 'slug': 'forearms', 'icon_name': 'Target', 'display_order': 12},
    {'id': 13, 'name': 'Traps', 'name_en': 'Traps', 'name_ru': 'Трапеции', 'name_kk': 'Трапеция', 'slug': 'traps', 'icon_name': 'ShieldCheck', 'display_order': 13},
    {'id': 14, 'name': 'Neck', 'name_en': 'Neck', 'name_ru': 'Шея', 'name_kk': 'Мойын', 'slug': 'neck', 'icon_name': 'UserCheck', 'display_order': 14},
    {'id': 15, 'name': 'Abs', 'name_en': 'Abs', 'name_ru': 'Пресс', 'name_kk': 'Іш бұлшықеттері', 'slug': 'abs', 'icon_name': 'Layers', 'display_order': 15},
    {'id': 16, 'name': 'Obliques', 'name_en': 'Obliques', 'name_ru': 'Косые мышцы', 'name_kk': 'Қиғаш бұлшықеттер', 'slug': 'obliques', 'icon_name': 'Layers', 'display_order': 16},
    {'id': 17, 'name': 'Core', 'name_en': 'Core', 'name_ru': 'Кор', 'name_kk': 'Кор', 'slug': 'core', 'icon_name': 'Layers', 'display_order': 17},
    {'id': 18, 'name': 'Glutes', 'name_en': 'Glutes', 'name_ru': 'Ягодицы', 'name_kk': 'Бөксе', 'slug': 'glutes', 'icon_name': 'TrendingUp', 'display_order': 18},
    {'id': 19, 'name': 'Quadriceps', 'name_en': 'Quadriceps', 'name_ru': 'Квадрицепс', 'name_kk': 'Квадрицепс', 'slug': 'quadriceps', 'icon_name': 'Award', 'display_order': 19},
    {'id': 20, 'name': 'Hamstrings', 'name_en': 'Hamstrings', 'name_ru': 'Бицепс бедра', 'name_kk': 'Санның артқы жағы', 'slug': 'hamstrings', 'icon_name': 'Repeat', 'display_order': 20},
    {'id': 21, 'name': 'Adductors', 'name_en': 'Adductors', 'name_ru': 'Приводящие мышцы', 'name_kk': 'Жанастырушы бұлшықеттер', 'slug': 'adductors', 'icon_name': 'Crosshair', 'display_order': 21},
    {'id': 22, 'name': 'Calves', 'name_en': 'Calves', 'name_ru': 'Икры', 'name_kk': 'Балтыр', 'slug': 'calves', 'icon_name': 'Gauge', 'display_order': 22},
    {'id': 23, 'name': 'Tibialis', 'name_en': 'Tibialis', 'name_ru': 'Большеберцовая мышца', 'name_kk': 'Асықты жілік бұлшықеті', 'slug': 'tibialis', 'icon_name': 'Gauge', 'display_order': 23},
    {'id': 24, 'name': 'Full Body', 'name_en': 'Full Body', 'name_ru': 'Все тело', 'name_kk': 'Толық дене', 'slug': 'full_body', 'icon_name': 'Globe', 'display_order': 24},
    {'id': 25, 'name': 'Cardio', 'name_en': 'Cardio', 'name_ru': 'Кардио', 'name_kk': 'Кардио', 'slug': 'cardio', 'icon_name': 'Heart', 'display_order': 25},
    {'id': 26, 'name': 'Mobility', 'name_en': 'Mobility', 'name_ru': 'Мобильность', 'name_kk': 'Ұтқырлық', 'slug': 'mobility', 'icon_name': 'Compass', 'display_order': 26},
]
