# -*- coding: utf-8 -*-
# Part 4 Core: Abs, Obliques, Core, Glutes

EXERCISES_CORE = [
    {
        'id': 20,
        'category_id': 15,
        'category_name': 'Abs',
        'slug': 'hanging_leg_raise',
        'name': 'Hanging Leg Raise',
        'name_en': 'Hanging Leg Raise',
        'name_ru': 'Подъем ног в висе на перекладине',
        'name_kk': 'Турникте аяқты көтеру',
        'target_muscles': 'Rectus Abdominis (Lower Focus), Hip Flexors',
        'target_muscles_en': 'Rectus Abdominis, Iliopsoas',
        'target_muscles_ru': 'Прямая мышца живота (низ пресса), подвздошно-поясничная',
        'target_muscles_kk': 'Тік іш бұлшықеті, мықын-бел бұлшықеті',
        'secondary_muscles_en': 'Obliques, Forearm Grip',
        'secondary_muscles_ru': 'Косые мышцы живота, предплечья',
        'secondary_muscles_kk': 'Қиғаш іш бұлшықеттері, білек',
        'equipment': 'Bodyweight',
        'equipment_en': 'Pull-up Bar',
        'equipment_ru': 'Турник / перекладина',
        'equipment_kk': 'Турник',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Advanced hanging abdominal flexion movement providing full abdominal stretch and posterior pelvic tilt.',
        'description_en': 'High-yield abdominal exercise targeting the lower rectus abdominis via active posterior pelvic tilt.',
        'description_ru': 'Мощное упражнение на пресс с глубоким подкручиванием таза в висе для проработки нижнего отдела пресса.',
        'description_kk': 'Іштің төменгі бұлшықеттерін толық қатайтуға және күшейтуге арналған турниктегі жаттығу.',
        'starting_position_en': 'Hang from bar with overhand grip and legs straight together. Depress shoulder blades and brace core.',
        'starting_position_ru': 'Вис на турнике прямым хватом, ноги вместе и выпрямлены. Лопатки опущены, пресс напряжен.',
        'starting_position_kk': 'Турникте түзу асылып тұрыңыз, аяқтар бірге және созылған. Кор қатайтылған.',
        'instructions_en': '1. Without swinging, raise legs smoothly toward the bar by curling pelvis upward.\n2. Lift feet until parallel to floor (or higher towards the bar).\n3. Squeeze abs firmly at peak contraction for 1 second.\n4. Lower legs under full eccentric control without swinging backward.',
        'instructions_ru': '1. Без раскачки поднимите ноги вверх, подкручивая таз к ребрам.\n2. Поднимите стопы до параллели с полом или выше.\n3. Сожмите пресс на 1 секунду в верхней точке.\n4. Медленно опустите ноги вниз, не допуская обратного раскачивания.',
        'instructions_kk': '1. Тербелмей, жамбасты бүгіп, аяқтарды жоғары қарай көтеріңіз.\n2. Аяқты еденге параллель немесе одан жоғары деңгейге көтеріңіз.\n3. Жоғарғы нүктеде іш бұлшықеттерін 1 секунд қатайтыңыз.\n4. Аяқты баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale as you raise your legs; inhale as you lower them down.',
        'breathing_ru': 'Выдох при подъеме ног вверх; вдох при плавном опускании.',
        'breathing_kk': 'Аяқты көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Using swinging momentum, raising legs solely via hip flexors without curling pelvis, dropping legs fast.',
        'common_mistakes_ru': 'Раскачивание телом, подъем только за счет сгибателей бедра без подкручивания таза, бросок ног вниз.',
        'common_mistakes_kk': 'Денемен тербеліп сермелу, жамбасты бүкпей тек аяқты көтеру, аяқты тез тастай салу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Mid-Torso Height',
        'camera_height_ru': 'На уровне корпуса',
        'camera_height_kk': 'Дене деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full hanging body from bar to toes must be in frame',
        'body_visibility_ru': 'Все тело от перекладины до носков должно быть в кадре',
        'body_visibility_kk': 'Турниктен аяқтың ұшына дейінгі толық дене көрінуі тиіс',
        'camera_instructions_en': 'Position camera sideways to monitor posterior pelvic tilt and lack of swinging momentum.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля подкручивания таза и отсутствия раскачки.',
        'camera_instructions_kk': 'Жамбастың дұрыс бүгілуін көру үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'hdng3Nm1x_E',
        'video_url': 'https://www.youtube.com/watch?v=hdng3Nm1x_E',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 21,
        'category_id': 17,
        'category_name': 'Core',
        'slug': 'forearm_plank',
        'name': 'Forearm Plank',
        'name_en': 'Forearm Plank',
        'name_ru': 'Классическая планка на предплечьях',
        'name_kk': 'Шынтаққа сүйеніп планка тұру',
        'target_muscles': 'Transverse Abdominis, Rectus Abdominis',
        'target_muscles_en': 'Transverse Abdominis, Rectus Abdominis, Core',
        'target_muscles_ru': 'Поперечная мышца живота, прямая мышца, мышцы кора',
        'target_muscles_kk': 'Көлденең іш бұлшықеті, тік іш бұлшықеті, кор',
        'secondary_muscles_en': 'Glutes, Shoulders, Quadriceps',
        'secondary_muscles_ru': 'Ягодицы, плечи, квадрицепсы',
        'secondary_muscles_kk': 'Бөксе, иықтар, квадрицепстер',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight / Mat',
        'equipment_ru': 'Свой вес / коврик',
        'equipment_kk': 'Өз салмағы / төсеніш',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Isometric anti-extension core stability benchmark evaluating whole-body alignment and endurance.',
        'description_en': 'The foundational anti-extension isometric core exercise for spinal stiffness and posture.',
        'description_ru': 'Фундаментальное статическое упражнение против разгибания позвоночника для создания стального кора.',
        'description_kk': 'Омыртқа тұрақтылығын және кор бұлшықеттерін нығайтатын негізгі статикалық жаттығу.',
        'starting_position_en': 'Rest on forearms and toes on floor. Elbows directly under shoulders, forearms parallel. Neutral head position.',
        'starting_position_ru': 'Упор на предплечья и носки. Локти строго под плечами, тело образует прямую струну от головы до пят.',
        'starting_position_kk': 'Шынтақ пен аяқтың ұшына сүйеніп жатыңыз. Шынтақ иық астында, дене бастан өкшеге дейін түзу.',
        'instructions_en': '1. Squeeze glutes and pull navel to spine to lock in a posterior pelvic tilt.\n2. Maintain a rigid straight line connecting ears, shoulders, hips, and heels.\n3. Push the floor away through forearms to avoid sagging between shoulder blades.\n4. Hold for target duration with steady breathing.',
        'instructions_ru': '1. Сожмите ягодицы и подтяните пупок к позвоночнику для фиксации поясницы.\n2. Удерживайте прямую линию: уши, плечи, таз и пятки на одной оси.\n3. Активно выталкивайте грудной отдел вверх, не проваливаясь в лопатках.\n4. Удерживайте планку намеченное время при ровном дыхании.',
        'instructions_kk': '1. Бөксені қатайтып, белді түзу ұстаңыз.\n2. Бас, иық, жамбас және өкшені бір түзу сызық бойында ұстаңыз.\n3. Жауырынның салбырап кетпеуін қадағалап, шынтақпен еденді итеріңіз.\n4. Бірқалыпты тыныс алып, белгіленген уақыт бойы ұстап тұрыңыз.',
        'breathing_en': 'Maintain slow, continuous diaphragmatic breathing without breath-holding.',
        'breathing_ru': 'Ровное глубокое дыхание без задержки воздуха.',
        'breathing_kk': 'Тынысты ұстамай, терең әрі бірқалыпты тыныс алыңыз.',
        'common_mistakes_en': 'Sagging hips into lumbar hyperextension, piking hips up in the air, dropping head downward.',
        'common_mistakes_ru': 'Провисание таза в пояснице, задирание таза вверх домиком, опускание головы вниз.',
        'common_mistakes_kk': 'Белдің төмен түсіп салбырауы, жамбасты жоғары көтеріп кету, басты төмен түсіру.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Floor Level',
        'camera_height_ru': 'На уровне пола',
        'camera_height_kk': 'Еден деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Full lateral body from head to heels must be visible',
        'body_visibility_ru': 'Вся боковая линия тела от макушки до пяток должна быть в кадре',
        'body_visibility_kk': 'Бастан өкшеге дейінгі бүйірлік түзу сызық анық көрінуі керек',
        'camera_instructions_en': 'Position camera on the floor 90° from the side to detect hip height deviations and spine angle.',
        'camera_instructions_ru': 'Поставьте камеру на пол сбоку на 2.5м для точного анализа линии позвоночника и высоты таза.',
        'camera_instructions_kk': 'Омыртқа сызығы мен жамбас биіктігін анықтау үшін камераны бүйір жақтан еденге қойыңыз.',
        'youtube_id': 'ASdvN_XEl_c',
        'video_url': 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
        'ideal_rom_degrees': 180.0,
        'normative_cadence_seconds': 45.0,
        'analysis_supported': False,
    }
]
