# -*- coding: utf-8 -*-
# Part 1 Back: Back, Lats, Upper Back, Lower Back

EXERCISES_BACK = [
    # --- BACK & LATS ---
    {
        'id': 6,
        'category_id': 2,
        'category_name': 'Back',
        'slug': 'barbell_bent_row',
        'name': 'Barbell Bent-Over Row',
        'name_en': 'Barbell Bent-Over Row',
        'name_ru': 'Тяга штанги в наклоне',
        'name_kk': 'Еңкейіп штанганы тарту',
        'target_muscles': 'Latissimus Dorsi, Rhomboids, Mid Trapezius',
        'target_muscles_en': 'Latissimus Dorsi, Rhomboids, Mid-Trapezius',
        'target_muscles_ru': 'Широчайшие мышцы, ромбовидные, средняя трапеция',
        'target_muscles_kk': 'Жалпақ бұлшықеттер, ромб тәрізді, ортаңғы трапеция',
        'secondary_muscles_en': 'Erector Spinae, Biceps, Posterior Deltoids',
        'secondary_muscles_ru': 'Разгибатели спины, бицепсы, задние дельты',
        'secondary_muscles_kk': 'Арқа жазғыштары, бицепстер, артқы дельталар',
        'equipment': 'Barbell',
        'equipment_en': 'Barbell',
        'equipment_ru': 'Штанга',
        'equipment_kk': 'Штанга',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Essential compound horizontal pulling movement building back thickness, spinal rigidity, and pulling power.',
        'description_en': 'Foundational compound horizontal pull building mid-back thickness and posterior chain endurance.',
        'description_ru': 'Базовое горизонтальное тяговое движение для мощного развития толщины спины и широчайших.',
        'description_kk': 'Арқаның қалыңдығы мен күшін арттыруға арналған негізгі горизонталь тарту жаттығуы.',
        'starting_position_en': 'Stand holding barbell with overhand grip. Hinge hips back to 45° torso angle, flat spine, knees slightly soft.',
        'starting_position_ru': 'Стопы на ширине плеч, хват сверху чуть шире плеч. Наклонитесь на 45°, спина прямая, колени слегка согнуты.',
        'starting_position_kk': 'Аяқ иық енінде, штанганы ұстап 45° еңкейіңіз. Арқа түзу, тізе сәл бүгілген.',
        'instructions_en': '1. Drive elbows back toward ceiling, pulling bar smoothly to lower ribcage/navel.\n2. Retract scapulae and squeeze back muscles hard at the top.\n3. Lower bar under control with a 2-second eccentric phase.\n4. Keep spine neutral and avoid jerky upright bouncing.',
        'instructions_ru': '1. Тяните штангу к низу живота, ведя локти вдоль корпуса вверх и назад.\n2. Сведите лопатки и максимально напрягите мышцы спины в верхней точке.\n3. Плавно опустите гриф вниз за 2 секунды до полного растяжения широчайших.\n4. Сохраняйте спину ровной без рывков корпусом.',
        'instructions_kk': '1. Шынтақты артқа қарай бағыттап, штанганы іштің төменгі тұсына тартыңыз.\n2. Жоғарғы нүктеде жауырынды жиырып, арқа бұлшықеттерін қатайтыңыз.\n3. Штанганы 2 секунд ішінде баяу төмен түсіріңіз.\n4. Арқаны түзу ұстап, селкілдемей орындаңыз.',
        'breathing_en': 'Exhale as you pull the bar up; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при тяге к поясу; вдох при плавном опускании вниз.',
        'breathing_kk': 'Штанганы тартқанда тыныс шығарыңыз; төмен түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Rounding lumbar spine, standing up too vertical on each rep, jerking torso for momentum.',
        'common_mistakes_ru': 'Округление поясницы (горб), выпрямление корпуса вверх при рывке, бросок веса вниз.',
        'common_mistakes_kk': 'Белді бүкірейту, әр ретте денені тік көтеріп кету, салмақты екпінмен жұлып тарту.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Knee / Hip Level',
        'camera_height_ru': 'На уровне коленей/бедер',
        'camera_height_kk': 'Тізе / жамбас деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full lateral profile including feet, hips, spine, and barbell path',
        'body_visibility_ru': 'Полный боковой профиль: стопы, таз, позвоночник и штанга',
        'body_visibility_kk': 'Бүйірлік көрініс: табан, жамбас, омыртқа және штанга қозғалысы',
        'camera_instructions_en': 'Place camera 90 degrees to the side at hip height to evaluate flat back alignment and elbow travel.',
        'camera_instructions_ru': 'Установите камеру строго сбоку на уровне бедер для контроля нейтрали позвоночника.',
        'camera_instructions_kk': 'Омыртқаның түзулігін бақылау үшін камераны дәл бүйір жақтан жамбас деңгейіне қойыңыз.',
        'youtube_id': '6TSP13ndbJg',
        'video_url': 'https://www.youtube.com/watch?v=6TSP13ndbJg',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 7,
        'category_id': 3,
        'category_name': 'Lats',
        'slug': 'lat_pulldown',
        'name': 'Wide-Grip Lat Pulldown',
        'name_en': 'Wide-Grip Lat Pulldown',
        'name_ru': 'Тяга верхнего блока к груди',
        'name_kk': 'Жоғарғы блокты кеудеге тарту',
        'target_muscles': 'Latissimus Dorsi, Teres Major',
        'target_muscles_en': 'Latissimus Dorsi (Outer & Lower)',
        'target_muscles_ru': 'Широчайшие мышцы спины',
        'target_muscles_kk': 'Арқаның жалпақ бұлшықеттері',
        'secondary_muscles_en': 'Biceps Brachii, Rhomboids, Lower Traps',
        'secondary_muscles_ru': 'Бицепсы, ромбовидные, низ трапеции',
        'secondary_muscles_kk': 'Бицепстер, ромб тәрізді, төменгі трапеция',
        'equipment': 'Cables',
        'equipment_en': 'Cable Lat Pulldown Machine',
        'equipment_ru': 'Тренажер тяги верхнего блока',
        'equipment_kk': 'Жоғарғы блок тренажеры',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Guided vertical pulling machine isolating latissimus dorsi width and developing scapular control.',
        'description_en': 'Premier vertical pulling machine exercise for widening the lats with scalable load.',
        'description_ru': 'Классическое упражнение на тренажере для формирования V-образной спины и ширины широчайших.',
        'description_kk': 'Арқаның V-тәрізді енін кеңейтуге және бұлшықеттерді дамытуға арналған классикалық жаттығу.',
        'starting_position_en': 'Sit with thighs secure under pads. Grip bar with wide overhand grip. Chest proud, slight 10-15° lean back.',
        'starting_position_ru': 'Сядьте, зафиксировав бедра под валиками. Хват широкий сверху. Расправьте грудь, отклонитесь на 10-15°.',
        'starting_position_kk': 'Сандарды тіреуіш астына бекітіп отырыңыз. Қол кең ұсталған. Кеудені көтеріп, 10-15° артқа шалқайыңыз.',
        'instructions_en': '1. Depress shoulder blades down first.\n2. Pull bar smoothly down to upper chest/collarbone, driving elbows down and back.\n3. Squeeze lats hard at bottom for 1 second.\n4. Control the ascent until arms and lats are fully stretched overhead.',
        'instructions_ru': '1. Опустите плечи и лопатки вниз.\n2. Тяните рукоять к верхней части груди, направляя локти вниз и назад.\n3. Зафиксируйте пиковое сокращение внизу на 1 секунду.\n4. Медленно верните рукоять вверх до полного растяжения спины.',
        'instructions_kk': '1. Алдымен жауырынды төмен қарай жиырыңыз.\n2. Шынтақты төмен бағыттап, тұтқаны кеуденің жоғарғы жағына тартыңыз.\n3. Төменгі нүктеде арқаны 1 секунд қатайтыңыз.\n4. Қолдар мен арқа толық созылғанша тұтқаны баяу жоғары көтеріңіз.',
        'breathing_en': 'Exhale as you pull the bar to chest; inhale as you release bar upward.',
        'breathing_ru': 'Выдох при тяге вниз к груди; вдох при подъеме рук вверх.',
        'breathing_kk': 'Төмен тартқанда тыныс шығарыңыз; жоғары жібергенде тыныс алыңыз.',
        'common_mistakes_en': 'Leaning back excessively (>45° turning it into a row), pulling behind neck, letting shoulders rise into ears.',
        'common_mistakes_ru': 'Сильный наклон назад (>45°), превращающий тягу в горизонтальную; тяга за голову; подъем плеч к ушам.',
        'common_mistakes_kk': 'Артқа тым қатты шалқаю (>45°), желкеге қарай тарту, иықты құлаққа жақындату.',
        'camera_angle_en': 'Side or Front View (45°)',
        'camera_angle_ru': 'Вид сбоку или спереди под 45°',
        'camera_angle_kk': 'Бүйір немесе алдыңғы 45° бұрыш',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Upper body, bar, and pulley cable must be framed',
        'body_visibility_ru': 'Корпус, перекладина и трос блока должны быть в кадре',
        'body_visibility_kk': 'Дене, тұтқа және тренажер тросы толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from a 45-degree angle to observe elbow descent and chest contact.',
        'camera_instructions_ru': 'Установите камеру сбоку-спереди под углом 45° для контроля угла локтей и амплитуды.',
        'camera_instructions_kk': 'Шынтақ бұрышы мен қозғалыс ауқымын көру үшін камераны 45° бұрышпен қойыңыз.',
        'youtube_id': 'CAwf7n6Luuc',
        'video_url': 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
        'ideal_rom_degrees': 120.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 8,
        'category_id': 4,
        'category_name': 'Upper Back',
        'slug': 'face_pull',
        'name': 'Cable Face Pull',
        'name_en': 'Cable Face Pull',
        'name_ru': 'Тяга каната к лицу (Face Pull)',
        'name_kk': 'Канатты бетке тарту (Face Pull)',
        'target_muscles': 'Rear Deltoids, Rhomboids, Rotator Cuff',
        'target_muscles_en': 'Rear Deltoids, Rhomboids, External Rotators, Traps',
        'target_muscles_ru': 'Задние дельты, ромбовидные, вращательная манжета, трапеции',
        'target_muscles_kk': 'Артқы дельталар, ромб тәрізді, айналдырушы манжета, трапеция',
        'secondary_muscles_en': 'Mid & Lower Trapezius, Biceps',
        'secondary_muscles_ru': 'Средняя и нижняя трапеция, бицепсы',
        'secondary_muscles_kk': 'Ортаңғы және төменгі трапеция, бицепстер',
        'equipment': 'Cables',
        'equipment_en': 'Cable Machine & Rope Attachment',
        'equipment_ru': 'Блочный тренажер и канатная рукоять',
        'equipment_kk': 'Блоктық тренажер және арқан тұтқасы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Superior postural corrective movement strengthening upper back, rotator cuff, and posterior deltoids.',
        'description_en': 'Key posture-correcting exercise building rear delts, upper back thickness, and shoulder health.',
        'description_ru': 'Лучшее упражнение для коррекции осанки, укрепления задней дельты и здоровья плечевых суставов.',
        'description_kk': 'Дене түзулігін жақсартуға, артқы дельта мен иық буындарының саулығын арттыруға арналған жаттығу.',
        'starting_position_en': 'Set pulley at eye/forehead level with rope attachment. Step back, hold rope with thumbs pointing backward.',
        'starting_position_ru': 'Установите блок на уровне глаз. Возьмитесь за канат так, чтобы большие пальцы смотрели назад, отойдите на шаг.',
        'starting_position_kk': 'Блокты көз деңгейіне қойыңыз. Арқаннан ұстап, бас бармақты артқа қаратып, бір қадам артқа шегініңіз.',
        'instructions_en': '1. Pull rope towards bridge of nose or forehead.\n2. Externally rotate shoulders by driving hands back past your ears.\n3. Squeeze shoulder blades and hold for 1 full second.\n4. Slowly return weight with full eccentric control.',
        'instructions_ru': '1. Тяните канат к уровню переносицы/лба.\n2. В конце движения разворачивайте плечи наружу, уводя кисти за уши (двойной бицепс).\n3. Максимально сведите лопатки и удержите 1 секунду.\n4. Плавно вернитесь в исходное положение.',
        'instructions_kk': '1. Арқанды мұрын немесе маңдай деңгейіне қарай тартыңыз.\n2. Қозғалыс соңында иықты сыртқа айналдырып, қолды құлақтан асырыңыз.\n3. Жауырынды жиырып, 1 секунд ұстап тұрыңыз.\n4. Бастапқы қалыпқа баяу қайтыңыз.',
        'breathing_en': 'Exhale on the pull and external rotation; inhale as arms extend forward.',
        'breathing_ru': 'Выдох при тяге к лицу; вдох при выпрямлении рук.',
        'breathing_kk': 'Бетке тартқанда тыныс шығарыңыз; қолды созғанда тыныс алыңыз.',
        'common_mistakes_en': 'Using excessive body momentum, pulling down into chest rather than face, dropping elbows below wrists.',
        'common_mistakes_ru': 'Тяга корпусом с раскачкой, тяга вниз к груди вместо лица, опускание локтей ниже запястий.',
        'common_mistakes_kk': 'Денемен екпін беру, бетке емес кеудеге тарту, шынтақты білектен төмен түсіру.',
        'camera_angle_en': 'Side or Front 45° View',
        'camera_angle_ru': 'Вид сбоку или спереди под 45°',
        'camera_angle_kk': 'Бүйір немесе алдыңғы 45° бұрыш',
        'camera_height_en': 'Eye / Shoulder Level',
        'camera_height_ru': 'На уровне глаз/плеч',
        'camera_height_kk': 'Көз / иық деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Head, shoulders, arms, and pulley cable must be clearly framed',
        'body_visibility_ru': 'Голова, плечи, руки и трос тренажера должны быть видны',
        'body_visibility_kk': 'Бас, иық, қолдар мен тренажер тросы толық көрінуі керек',
        'camera_instructions_en': 'Position camera at eye level from the side/front to verify external shoulder rotation.',
        'camera_instructions_ru': 'Установите камеру на уровне глаз для контроля внешней ротации плеч и положения локтей.',
        'camera_instructions_kk': 'Иықтың сыртқа айналуын және шынтақ деңгейін бақылау үшін камераны көз биіктігіне қойыңыз.',
        'youtube_id': 'rep-qVOkqgk',
        'video_url': 'https://www.youtube.com/watch?v=rep-qVOkqgk',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 9,
        'category_id': 5,
        'category_name': 'Lower Back',
        'slug': 'back_hyperextension',
        'name': '45° Back Hyperextension',
        'name_en': '45° Back Hyperextension',
        'name_ru': 'Гиперэкстензия на римском стуле 45°',
        'name_kk': '45° римдік орындықта гиперэкстензия',
        'target_muscles': 'Erector Spinae, Glutes, Hamstrings',
        'target_muscles_en': 'Erector Spinae (Lower Back), Gluteus Maximus',
        'target_muscles_ru': 'Разгибатели спины (поясница), большая ягодичная',
        'target_muscles_kk': 'Арқа жазғыштары (бел), үлкен бөксе бұлшықеті',
        'secondary_muscles_en': 'Hamstrings',
        'secondary_muscles_ru': 'Бицепсы бедер',
        'secondary_muscles_kk': 'Санның артқы бұлшықеттері',
        'equipment': 'Machines',
        'equipment_en': '45° Hyperextension Bench',
        'equipment_ru': 'Скамья для гиперэкстензии 45°',
        'equipment_kk': '45° гиперэкстензия орындығы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Direct lumbar spine and posterior chain strengthening exercise promoting spinal resilience.',
        'description_en': 'Direct lower back strengthening drill reinforcing spinal extension and posterior chain resilience.',
        'description_ru': 'Одно из лучших упражнений для укрепления поясничного отдела спины, ягодиц и профилактики травм.',
        'description_kk': 'Бел бұлшықеттерін, бөксе мен омыртқа саулығын нығайтуға арналған ең тиімді жаттығу.',
        'starting_position_en': 'Position hips against pad with top edge just below hip crease. Lock ankles under bottom rollers.',
        'starting_position_ru': 'Отрегулируйте подушку чуть ниже сгиба бедер. Зафиксируйте щиколотки под валиками, руки на груди.',
        'starting_position_kk': 'Жастықшаны жамбас бүгілуінен сәл төмен орнатыңыз. Толарсақты бекітіп, қолды кеудеге қойыңыз.',
        'instructions_en': '1. Hinge forward at hips with a flat neutral back.\n2. Lower torso until hips reach 90° flexion.\n3. Engage glutes and erectors to raise torso until body forms a straight line.\n4. Pause at peak without hyperextending backward.',
        'instructions_ru': '1. Плавно наклонитесь вперед в тазобедренных суставах с ровной спиной.\n2. Опуститесь до угла 90° в тазу.\n3. Напряжением ягодиц и поясницы поднимите корпус до прямой линии с ногами.\n4. Задержитесь в верхней точке, избегая избыточного переразгибания назад.',
        'instructions_kk': '1. Арқаны түзу ұстап, жамбастан алға қарай баяу еңкейіңіз.\n2. Жамбас 90° бүгілгенше төмендеңіз.\n3. Бөксе мен бел бұлшықеттерін жиырып, денені түзу сызыққа дейін көтеріңіз.\n4. Артқа шамадан тыс қайқыймай, жоғарғы нүктеде тоқтаңыз.',
        'breathing_en': 'Inhale as you lower forward; exhale as you raise your torso.',
        'breathing_ru': 'Вдох при наклоне вперед; выдох при подъеме корпуса.',
        'breathing_kk': 'Алға еңкейгенде тыныс алыңыз; көтерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Hyperextending and arching backward excessively at the top, rounding lumbar spine into a hump.',
        'common_mistakes_ru': 'Чрезмерное закидывание корпуса назад вверху (переразгибание поясницы), сильное скручивание спины горбом.',
        'common_mistakes_kk': 'Жоғарыда белді шамадан тыс артқа қайқайту, омыртқаны бүкірейту.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Bench Height',
        'camera_height_ru': 'На уровне скамьи',
        'camera_height_kk': 'Орындық деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full bench, legs, and spine angle must be in frame',
        'body_visibility_ru': 'Скамья, ноги и линия позвоночника должны быть четко видны',
        'body_visibility_kk': 'Орындық, аяқтар және омыртқа сызығы толық көрінуі керек',
        'camera_instructions_en': 'Place camera 90° to the side to verify straight-line lockout without lumbar hyperextension.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля прямой линии тела в верхней точке.',
        'camera_instructions_kk': 'Белдің шамадан тыс қайқыймауын бақылау үшін камераны бүйір жақтан қойыңыз.',
        'youtube_id': 'ph3pddpKzzw',
        'video_url': 'https://www.youtube.com/watch?v=ph3pddpKzzw',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    }
]
