# -*- coding: utf-8 -*-
# Part 1: Chest, Back, Lats, Upper Back, Lower Back

EXERCISES_PART1 = [
    # --- CHEST ---
    {
        'id': 1,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'barbell_bench_press',
        'name': 'Barbell Bench Press',
        'name_en': 'Barbell Bench Press',
        'name_ru': 'Жим штанги лежа',
        'name_kk': 'Жатып штанганы сығу',
        'target_muscles': 'Pectoralis Major, Anterior Deltoids, Triceps',
        'target_muscles_en': 'Pectoralis Major (Sternal & Clavicular)',
        'target_muscles_ru': 'Большая грудная мышца (стернальная и ключичная части)',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті (төс және бұғана бөліктері)',
        'secondary_muscles_en': 'Anterior Deltoids, Triceps Brachii, Serratus Anterior',
        'secondary_muscles_ru': 'Передние дельты, трицепс, передняя зубчатая мышца',
        'secondary_muscles_kk': 'Алдыңғы дельталар, трицепс, алдыңғы тісті бұлшықет',
        'equipment': 'Barbell',
        'equipment_en': 'Barbell & Bench',
        'equipment_ru': 'Штанга и скамья',
        'equipment_kk': 'Штанга және орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'The premier upper body horizontal pressing movement developing chest mass and pushing strength.',
        'description_en': 'The foundational upper-body horizontal pressing strength and hypertrophy movement.',
        'description_ru': 'Базовое многосуставное жимовое движение для развития максимальной силы и объема грудных мышц.',
        'description_kk': 'Кеуде бұлшықеттерінің күші мен көлемін арттыруға арналған негізгі көпбуынды жим жаттығуы.',
        'starting_position_en': 'Lie flat on bench, eyes under bar. Plant feet firmly on floor, retract scapulae, grip bar slightly wider than shoulder width.',
        'starting_position_ru': 'Лягте на скамью, глаза под грифом. Стопы плотно прижаты к полу, лопатки сведены и опущены, хват чуть шире плеч.',
        'starting_position_kk': 'Орындыққа жатыңыз, көз штанга деңгейінде. Табан еденде нық, жауырын жиылған, қол иықтан сәл кеңірек.',
        'instructions_en': '1. Unrack bar with arms locked over mid-chest.\n2. Inhale, brace core, and lower bar in a slight arc to lower chest (nipple line).\n3. Keep elbows tucked at 45-70 degrees.\n4. Press bar powerfully back up to starting lockout.',
        'instructions_ru': '1. Снимите гриф и зафиксируйте над серединой груди.\n2. Сделайте вдох, напрягите кор и плавно опустите гриф к нижней части груди.\n3. Локти держите под углом 45-70 градусов к корпусу.\n4. Мощно выжмите гриф вверх до полного выпрямления рук.',
        'instructions_kk': '1. Штанганы тіреуіштен алып, кеуде үстінде тік ұстаңыз.\n2. Тыныс алып, штанганы кеуденің төменгі тұсына баяу түсіріңіз.\n3. Шынтақты денеге 45-70 градус бұрышпен бағыттаңыз.\n4. Қолды толық жазып, штанганы жоғары қарай күшпен итеріңіз.',
        'breathing_en': 'Inhale deeply during descent; exhale forcefully through the sticking point on ascent.',
        'breathing_ru': 'Глубокий вдох при опускании штанги; мощный выдох при выжимании веса вверх.',
        'breathing_kk': 'Штанганы түсіргенде терең тыныс алыңыз; жоғары көтергенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Flaring elbows out to 90°, bouncing bar off sternum, raising hips/glutes off the bench, loose wrists.',
        'common_mistakes_ru': 'Разведение локтей на 90° в стороны, отбив грифа от грудины, отрыв таза от скамьи, залом запястий.',
        'common_mistakes_kk': 'Шынтақты 90° жан-жаққа ашу, штанганы кеудеге ұрып алу, бөксеңізді орындықтан көтеру, білекті қайыру.',
        'camera_angle_en': 'Side View (45° or 90°)',
        'camera_angle_ru': 'Вид сбоку (45° или 90°)',
        'camera_angle_kk': 'Бүйірден көрініс (45° немесе 90°)',
        'camera_height_en': 'Bench Height',
        'camera_height_ru': 'На уровне скамьи',
        'camera_height_kk': 'Орындық деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full torso, head, bench, and bar path must be clearly in frame',
        'body_visibility_ru': 'Весь корпус, голова, скамья и траектория грифа должны быть в кадре',
        'body_visibility_kk': 'Толық дене, бас, орындық және штанга қозғалысы кадрда анық көрінуі тиіс',
        'camera_instructions_en': 'Place camera 2.5-3m away at bench height from a 45-degree angle to track bar path and elbow flare.',
        'camera_instructions_ru': 'Установите камеру на расстоянии 2.5-3м под углом 45 градусов к скамье для отслеживания траектории штанги и локтей.',
        'camera_instructions_kk': 'Штанга мен шынтақ қозғалысын анықтау үшін камераны 45 градус бұрышпен 2.5-3 метр қашықтыққа қойыңыз.',
        'youtube_id': 'rT7DgCr-3pg',
        'video_url': 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 2,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'incline_dumbbell_press',
        'name': 'Incline Dumbbell Press',
        'name_en': 'Incline Dumbbell Press',
        'name_ru': 'Жим гантелей на наклонной скамье',
        'name_kk': 'Көлбеу орындықта гантельді сығу',
        'target_muscles': 'Clavicular Pectoralis, Anterior Deltoids',
        'target_muscles_en': 'Upper Pectoralis (Clavicular Head)',
        'target_muscles_ru': 'Верхняя часть грудных мышц (ключичная головка)',
        'target_muscles_kk': 'Кеуде бұлшықетінің жоғарғы бөлігі (бұғана басы)',
        'secondary_muscles_en': 'Anterior Deltoids, Triceps Brachii',
        'secondary_muscles_ru': 'Передние дельты, трицепс',
        'secondary_muscles_kk': 'Алдыңғы дельталар, трицепс',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells & Incline Bench',
        'equipment_ru': 'Гантели и наклонная скамья',
        'equipment_kk': 'Гантельдер және көлбеу орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Targeted upper pectoral builder allowing independent limb stabilization and deep stretch.',
        'description_en': 'Targeted upper pectoral exercise using an incline angle for balanced bilateral chest development.',
        'description_ru': 'Акцентированное упражнение для развития верхнего отдела груди с глубокой растяжкой и независимой работой рук.',
        'description_kk': 'Кеуденің жоғарғы бөлігін дамытуға және екі қолдың теңгерімді күшін арттыруға арналған жаттығу.',
        'starting_position_en': 'Set bench to 30-45 degrees. Sit with dumbbells resting on thighs, kick them up to shoulder level, and retract shoulder blades.',
        'starting_position_ru': 'Установите наклон скамьи 30-45°. Сядьте с гантелями на бедрах, закиньте их к плечам, сведите лопатки.',
        'starting_position_kk': 'Орындықты 30-45° көлбеу орнатыңыз. Гантельдерді иыққа көтеріп, жауырыныңызды жиырыңыз.',
        'instructions_en': '1. Press dumbbells up and slightly inward without clanking them together.\n2. Lower dumbbells under control until you feel a comfortable stretch in upper chest.\n3. Keep wrists directly stacked over elbows throughout.\n4. Repeat with uniform tempo.',
        'instructions_ru': '1. Выжмите гантели вверх и слегка навстречу друг другу без соударения.\n2. Плавно опустите гантели до ощущения комфортного растяжения в верхней части груди.\n3. Держите запястья строго над локтями.\n4. Повторите в плавном контролируемом темпе.',
        'instructions_kk': '1. Гантельдерді бір-біріне соқпай жоғары қарай сығыңыз.\n2. Кеуденің жоғарғы бөлігі созылғанша гантельдерді баяу түсіріңіз.\n3. Білектерді шынтақтың үстінде түзу ұстаңыз.\n4. Бірқалыпты ырғақпен қайталаңыз.',
        'breathing_en': 'Inhale on the eccentric lowering phase; exhale on the concentric press.',
        'breathing_ru': 'Вдох при опускании гантелей; выдох при подъеме.',
        'breathing_kk': 'Төмен түсіргенде тыныс алыңыз; жоғары көтергенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Bench angle too steep (>45°) turning it into a shoulder press, dropping elbows too low, banging dumbbells at the top.',
        'common_mistakes_ru': 'Слишком большой угол наклона (>45°), перегружающий дельты; чрезмерное опускание локтей; стук гантелей вверху.',
        'common_mistakes_kk': 'Орындықты тым тік қойып иыққа салмақ түсіру (>45°); шынтақты тым төмен түсіру; гантельдерді соғу.',
        'camera_angle_en': 'Side or 45° Front View',
        'camera_angle_ru': 'Вид сбоку или спереди под 45°',
        'camera_angle_kk': 'Бүйір немесе алдыңғы 45° бұрыштан',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Upper body, arms, and bench angle must be clearly visible',
        'body_visibility_ru': 'Верхняя часть тела, руки и наклонная скамья должны быть в кадре',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі, қолдар және орындық анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera at chest level from a 45-degree angle to observe pressing line and depth.',
        'camera_instructions_ru': 'Поставьте камеру на уровне груди под углом 45° для контроля амплитуды и траектории движения.',
        'camera_instructions_kk': 'Қозғалыс ауқымы мен траекториясын бақылау үшін камераны кеуде деңгейіне 45° бұрышпен қойыңыз.',
        'youtube_id': '8iPEnn-ltC8',
        'video_url': 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 3,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'cable_chest_fly',
        'name': 'Cable Chest Flyes',
        'name_en': 'Cable Chest Flyes',
        'name_ru': 'Сведение рук в кроссовере на грудь',
        'name_kk': 'Кроссоверде қолды қосу (кеуде)',
        'target_muscles': 'Pectoralis Major (Sternal & Inner)',
        'target_muscles_en': 'Pectoralis Major (Inner & Mid Sternal)',
        'target_muscles_ru': 'Большая грудная мышца (стернальная часть)',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті (ортаңғы бөлігі)',
        'secondary_muscles_en': 'Anterior Deltoids, Biceps (Short Head)',
        'secondary_muscles_ru': 'Передняя дельта, короткая головка бицепса',
        'secondary_muscles_kk': 'Алдыңғы дельта, бицепстің қысқа басы',
        'equipment': 'Cables',
        'equipment_en': 'Cable Machine / Dual Pulleys',
        'equipment_ru': 'Блочный тренажер (кроссовер)',
        'equipment_kk': 'Блоктық тренажер (кроссовер)',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Continuous-tension isolation exercise providing maximal chest peak contraction and stretch.',
        'description_en': 'Isolation movement delivering continuous resistance throughout full chest adduction.',
        'description_ru': 'Изолированное упражнение с постоянным натяжением для максимального пикового сокращения грудных мышц.',
        'description_kk': 'Кеуде бұлшықеттерін толық созуға және қатайтуға арналған тұрақты қарсылықты оқшауланған жаттығу.',
        'starting_position_en': 'Set pulleys at chest/shoulder height. Step forward into a staggered stance with a slight forward torso lean.',
        'starting_position_ru': 'Установите блоки на высоте плеч/груди. Сделайте шаг вперед в разножку, слегка наклоните корпус.',
        'starting_position_kk': 'Блоктарды иық деңгейіне қойыңыз. Бір аяқты алға қойып, денені сәл алға еңкейтіңіз.',
        'instructions_en': '1. Maintain a slight, fixed bend in your elbows.\n2. Bring hands together in a wide hugging arc across your chest.\n3. Squeeze pectorals firmly at peak meeting point for 1 second.\n4. Open arms with control until a deep stretch is achieved.',
        'instructions_ru': '1. Зафиксируйте легкий изгиб в локтях на протяжении всего подхода.\n2. Сводите рукояти по широкой дуге перед грудью, словно обнимаете большое дерево.\n3. Задержитесь и прожмите грудные мышцы в точке сведения на 1 секунду.\n4. Плавно разведите руки до глубокого растяжения.',
        'instructions_kk': '1. Шынтақтағы аздаған бүгілісті жаттығу соңына дейін сақтаңыз.\n2. Кеуде тұсында қолдарды доға бойымен алға қарай қосыңыз.\n3. Қолдар қосылған кезде кеудені 1 секунд қатайтыңыз.\n4. Кеуде толық созылғанша қолды баяу екі жаққа ашыңыз.',
        'breathing_en': 'Exhale as you bring hands together; inhale as you open arms wide.',
        'breathing_ru': 'Выдох при сведении рук; вдох при разведении.',
        'breathing_kk': 'Қолды қосқанда тыныс шығарыңыз; ашқанда тыныс алыңыз.',
        'common_mistakes_en': 'Bending and extending elbows into a press, using body swing momentum, overextending shoulders backward.',
        'common_mistakes_ru': 'Превращение сведения в жим со сгибанием локтей, раскачка корпусом, чрезмерный увод локтей назад за спину.',
        'common_mistakes_kk': 'Қозғалысты жимге айналдырып шынтақты бүгу, денемен тербелу, иықты артқа тым қатты қайыру.',
        'camera_angle_en': 'Front View (0°) or 45° Angle',
        'camera_angle_ru': 'Вид спереди (0°) или под углом 45°',
        'camera_angle_kk': 'Алдыңғы көрініс (0°) немесе 45° бұрыш',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full upper body, cable attachments, and arm wingspan must be visible',
        'body_visibility_ru': 'Верхняя часть корпуса, кабели и размах рук должны быть полностью видны',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі, кабельдер мен қолдың созылуы толық көрінуі тиіс',
        'camera_instructions_en': 'Position camera directly in front to check bilateral arm symmetry and arc consistency.',
        'camera_instructions_ru': 'Установите камеру спереди для проверки симметрии сведения и контроля траектории обеих рук.',
        'camera_instructions_kk': 'Екі қолдың біркелкі қозғалысын бақылау үшін камераны тікелей алдыңыздан қойыңыз.',
        'youtube_id': 'Iwe6AmxVf7o',
        'video_url': 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
        'ideal_rom_degrees': 100.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 4,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'pec_deck_fly',
        'name': 'Pec Deck Machine Flye',
        'name_en': 'Pec Deck Machine Flye',
        'name_ru': 'Сведение рук в тренажере Бабочка (Pec Deck)',
        'name_kk': 'Тренажерде қолды қосу (Көбелек / Pec Deck)',
        'target_muscles': 'Pectoralis Major',
        'target_muscles_en': 'Pectoralis Major (Sternal & Costal)',
        'target_muscles_ru': 'Большая грудная мышца',
        'target_muscles_kk': 'Үлкен кеуде бұлшықеті',
        'secondary_muscles_en': 'Anterior Deltoids',
        'secondary_muscles_ru': 'Передние дельты',
        'secondary_muscles_kk': 'Алдыңғы дельталар',
        'equipment': 'Machines',
        'equipment_en': 'Pec Deck Machine',
        'equipment_ru': 'Тренажер Бабочка',
        'equipment_kk': 'Көбелек тренажеры',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Guided machine flye providing stable, safe chest hypertrophy isolation without stabilizer fatigue.',
        'description_en': 'Guided isolation machine isolating chest fibers without excessive shoulder stabilizer demand.',
        'description_ru': 'Безопасное изолированное упражнение на тренажере с заданной траекторией для глубокой проработки груди.',
        'description_kk': 'Кеуде бұлшықеттерін қауіпсіз және тиімді қатайтуға арналған арнайы тренажер жаттығуы.',
        'starting_position_en': 'Adjust seat so handles align with mid-chest. Sit back firmly against the pad with feet planted.',
        'starting_position_ru': 'Отрегулируйте сиденье так, чтобы рукояти были на уровне середины груди. Плотно прижмите спину.',
        'starting_position_kk': 'Тұтқалар кеуденің ортасына сәйкес келетіндей орындықты реттеңіз. Арқаны нық басып отырыңыз.',
        'instructions_en': '1. Grip handles with elbows slightly bent.\n2. Bring handles together in front of your chest under smooth control.\n3. Hold peak contraction for 1 second.\n4. Slowly return handles until chest is comfortably stretched.',
        'instructions_ru': '1. Возьмитесь за рукояти, слегка согнув руки в локтях.\n2. Плавно сведите рукояти перед собой силой грудных мышц.\n3. Зафиксируйте пиковое сокращение на 1 секунду.\n4. Медленно вернитесь назад до приятного растяжения.',
        'instructions_kk': '1. Тұтқаларды ұстап, шынтақты сәл бүгіңіз.\n2. Кеуде бұлшықетінің күшімен тұтқаларды алға қарай жиырыңыз.\n3. 1 секунд толық қатайтылған күйде ұстаңыз.\n4. Кеуде созылғанша баяу артқа қайтыңыз.',
        'breathing_en': 'Exhale on contraction; inhale on return stretch.',
        'breathing_ru': 'Выдох при сведении; вдох при разведении.',
        'breathing_kk': 'Қосқанда тыныс шығарыңыз; ашқанда тыныс алыңыз.',
        'common_mistakes_en': 'Lifting shoulders toward ears, letting weight stack slam, losing back contact with pad.',
        'common_mistakes_ru': 'Подъем плеч к ушам, резкий бросок весового стека, отрыв спины от спинки тренажера.',
        'common_mistakes_kk': 'Иықты көтеру, салмақты тастай салу, арқаны тіреуіштен ажырату.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Upper torso, shoulders, and machine arms in full view',
        'body_visibility_ru': 'Верхняя часть туловища, плечи и рычаги тренажера в кадре',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі, иық пен тренажер тұтқалары анық көрінуі керек',
        'camera_instructions_en': 'Frame from the front to evaluate bilateral chest squeeze and steady tempo.',
        'camera_instructions_ru': 'Установите камеру спереди для контроля плавности и симметрии сведения рук.',
        'camera_instructions_kk': 'Қозғалыстың бірқалыптылығын бақылау үшін камераны алдыңыздан қойыңыз.',
        'youtube_id': 'eGjt4lk6g34',
        'video_url': 'https://www.youtube.com/watch?v=eGjt4lk6g34',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 5,
        'category_id': 1,
        'category_name': 'Chest',
        'slug': 'dips_chest',
        'name': 'Chest Dips',
        'name_en': 'Chest Dips',
        'name_ru': 'Отжимания на брусьях с акцентом на грудь',
        'name_kk': 'Брусьяда сығылу (кеудеге бағытталған)',
        'target_muscles': 'Lower Pectoralis Major, Triceps',
        'target_muscles_en': 'Pectoralis Major (Lower & Sternal)',
        'target_muscles_ru': 'Нижняя и стернальная часть грудных мышц',
        'target_muscles_kk': 'Кеуде бұлшықетінің төменгі бөлігі',
        'secondary_muscles_en': 'Triceps Brachii, Anterior Deltoids',
        'secondary_muscles_ru': 'Трицепс, передняя дельта',
        'secondary_muscles_kk': 'Трицепс, алдыңғы дельта',
        'equipment': 'Bodyweight',
        'equipment_en': 'Dip Bars / Parallel Bars',
        'equipment_ru': 'Параллельные брусья',
        'equipment_kk': 'Параллель брустар',
        'difficulty': 'Advanced',
        'difficulty_en': 'Advanced',
        'difficulty_ru': 'Продвинутый',
        'difficulty_kk': 'Жоғары',
        'description': 'Advanced bodyweight compound movement building lower chest thickness and pushing power.',
        'description_en': 'Potent multi-joint compound movement developing lower chest mass and lock-out strength.',
        'description_ru': 'Мощное базовое упражнение с собственным весом для прокачки низа груди и трицепсов.',
        'description_kk': 'Кеуденің төменгі бөлігі мен трицепсті дамытуға арналған қуатты базалық жаттығу.',
        'starting_position_en': 'Mount dip bars with straight arms. Lean torso forward 20-30 degrees, bend knees slightly, and keep elbows angled outward.',
        'starting_position_ru': 'Примите упор на брусьях на прямых руках. Наклоните корпус вперед на 20-30°, согните колени, локти чуть шире.',
        'starting_position_kk': 'Брусьяға түзу қолмен сүйеніп тұрыңыз. Денені 20-30° алға еңкейтіп, тізені сәл бүгіңіз.',
        'instructions_en': '1. Maintain the forward torso lean throughout the rep.\n2. Lower body smoothly until shoulders descend below elbow level (90° elbow bend).\n3. Feel a deep stretch in lower chest.\n4. Press back up powerfully without standing fully vertical.',
        'instructions_ru': '1. Сохраняйте наклон корпуса вперед на протяжении всего повторения.\n2. Плавно опускайтесь вниз до угла 90° в локтях.\n3. Почувствуйте растяжение в нижней части груди.\n4. Мощно выжмите себя вверх, сохраняя наклон.',
        'instructions_kk': '1. Жаттығу бойы денені алға еңкейткен күйде ұстаңыз.\n2. Шынтақ 90° бүгілгенше денеңізді баяу төмен түсіріңіз.\n3. Кеуденің төменгі бөлігі созылғанын сезініңіз.\n4. Денені жоғары қарай күшпен итеріп бастапқы қалыпқа келіңіз.',
        'breathing_en': 'Inhale on the way down; exhale as you press up.',
        'breathing_ru': 'Вдох при опускании; выдох при выжимании тела вверх.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; жоғары итерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Staying too upright (shifts tension solely to triceps), dropping too fast, half-range reps, swinging legs.',
        'common_mistakes_ru': 'Вертикальное положение корпуса (уводит нагрузку в трицепс), резкое падение вниз, неполная амплитуда, раскачка.',
        'common_mistakes_kk': 'Денені тік ұстап трицепске салмақ түсіру, тез құлап түсу, жартылай орындау, аяқпен сермелу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Mid-Dip Bar Height',
        'camera_height_ru': 'На высоте брусьев',
        'camera_height_kk': 'Брустар биіктігінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full upper body, dip station, and torso angle must be framed',
        'body_visibility_ru': 'Корпус, брусья и угол наклона тела должны быть четко в кадре',
        'body_visibility_kk': 'Дене, брустар және еңкею бұрышы кадрда анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera directly at the side to monitor elbow depth and forward torso angle.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля глубины опускания локтей и угла наклона торса.',
        'camera_instructions_kk': 'Төмен түсу тереңдігі мен дененің еңкеюін бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': '2z8JmcrW-As',
        'video_url': 'https://www.youtube.com/watch?v=2z8JmcrW-As',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
]
