# -*- coding: utf-8 -*-
# Part 4 Legs: Glutes, Quads, Hamstrings, Adductors, Calves, Tibialis

EXERCISES_LEGS = [
    {
        'id': 22,
        'category_id': 18,
        'category_name': 'Glutes',
        'slug': 'barbell_hip_thrust',
        'name': 'Barbell Hip Thrust',
        'name_en': 'Barbell Hip Thrust',
        'name_ru': 'Ягодичный мостик со штангой от скамьи',
        'name_kk': 'Орындықтан штангамен бөксе көтеру',
        'target_muscles': 'Gluteus Maximus',
        'target_muscles_en': 'Gluteus Maximus',
        'target_muscles_ru': 'Большая ягодичная мышца',
        'target_muscles_kk': 'Үлкен бөксе бұлшықеті',
        'secondary_muscles_en': 'Hamstrings, Quadriceps, Core',
        'secondary_muscles_ru': 'Бицепсы бедер, квадрицепсы, кор',
        'secondary_muscles_kk': 'Санның артқы жағы, квадрицепс, кор',
        'equipment': 'Barbell',
        'equipment_en': 'Barbell & Bench (with pad)',
        'equipment_ru': 'Штанга и скамья (с подушкой)',
        'equipment_kk': 'Штанга және орындық (жастықшасымен)',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'High-load glute hypertrophy and hip extension movement.',
        'description_en': 'The gold standard exercise for maximum gluteus maximus hypertrophy and hip extension power.',
        'description_ru': 'Золотой стандарт для развития максимальной силы, объема и формы ягодичных мышц.',
        'description_kk': 'Бөксе бұлшықеттерінің күші мен көлемін арттыруға арналған ең үздік базалық жаттығу.',
        'starting_position_en': 'Sit on floor with upper back against bench (lower shoulder blades on edge). Roll padded barbell over hips. Feet flat shoulder-width.',
        'starting_position_ru': 'Сядьте спиной к скамье (край скамьи под лопатками). Положите штангу на таз. Стопы на ширине плеч.',
        'starting_position_kk': 'Арқаңызды орындыққа тіреп отырыңыз. Штанганы жамбас үстіне қойыңыз. Табан иық енінде.',
        'instructions_en': '1. Keep chin tucked and gaze forward at your knees.\n2. Drive through heels and extend hips upward until thighs and torso form a flat horizontal bridge.\n3. Squeeze glutes hard at top lockout for 1-2 seconds with posterior pelvic tilt.\n4. Lower hips under control until almost touching floor.',
        'instructions_ru': '1. Прижмите подбородок к груди, взгляд вперед перед собой.\n2. Мощно оттолкнитесь пятками и поднимите таз вверх до горизонтального моста.\n3. В верхней точке максимально сожмите ягодицы на 1-2 секунды.\n4. Плавно опустите таз вниз, контролируя движение.',
        'instructions_kk': '1. Иекті кеудеге жақындатып, алға қараңыз.\n2. Өкшемен күшпен итеріліп, дене көлденең түзу сызық болғанша жамбасты көтеріңіз.\n3. Жоғарғы нүктеде бөксені 1-2 секунд қатайтып ұстаңыз.\n4. Жамбасты баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale as you drive hips up to lockout; inhale as hips descend.',
        'breathing_ru': 'Выдох при подъеме таза вверх; вдох при опускании.',
        'breathing_kk': 'Жамбасты көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Hyperextending lumbar spine at top looking at ceiling, placing feet too close or too far away, lifting heels.',
        'common_mistakes_ru': 'Прогиб в пояснице вверху с запрокидыванием головы, неправильная постановка стоп, отрыв пяток.',
        'common_mistakes_kk': 'Белді қайқайту, басты артқа шалқайту, өкшені көтеру.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Bench / Hip Height',
        'camera_height_ru': 'На уровне скамьи/бедер',
        'camera_height_kk': 'Орындық / жамбас деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Bench, hips, knees, and feet must be completely in frame',
        'body_visibility_ru': 'Скамья, таз, колени и стопы должны быть полностью видны',
        'body_visibility_kk': 'Орындық, жамбас, тізе және табан анық көрінуі керек',
        'camera_instructions_en': 'Position camera from the side to check for full 180° hip extension without lumbar hyperextension.',
        'camera_instructions_ru': 'Установите камеру сбоку для проверки полной горизонтали таза и отсутствия прогиба в пояснице.',
        'camera_instructions_kk': 'Жамбастың көлденең түзулігін бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'SEdqd1n0cvg',
        'video_url': 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
        'ideal_rom_degrees': 180.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 23,
        'category_id': 18,
        'category_name': 'Glutes',
        'slug': 'bulgarian_split_squat',
        'name': 'Bulgarian Split Squat',
        'name_en': 'Bulgarian Split Squat',
        'name_ru': 'Болгарские сплит-приседания',
        'name_kk': 'Болгарлық сплит-отыру',
        'target_muscles': 'Glutes, Quadriceps',
        'target_muscles_en': 'Gluteus Maximus, Quadriceps',
        'target_muscles_ru': 'Большая ягодичная, квадрицепс',
        'target_muscles_kk': 'Үлкен бөксе, квадрицепс',
        'secondary_muscles_en': 'Hamstrings, Adductors, Core',
        'secondary_muscles_ru': 'Бицепс бедра, приводящие, кор',
        'secondary_muscles_kk': 'Санның артқы жағы, жанастырушы, кор',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells & Bench',
        'equipment_ru': 'Гантели и скамья',
        'equipment_kk': 'Гантельдер және орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Elite unilateral strength and hypertrophy movement correcting limb imbalances and building single-leg power.',
        'description_en': 'High-yield unilateral leg builder developing single-leg strength, glute hypertrophy, and hip stability.',
        'description_ru': 'Мощнейшее одностороннее упражнение для гипертрофии ягодиц, ног и устранения мышечного дисбаланса.',
        'description_kk': 'Аяқтардың бұлшықет теңгерімсіздігін жоюға және бөксе көлемін арттыруға арналған жаттығу.',
        'starting_position_en': 'Stand 2-3 feet in front of a bench. Place top of rear foot on bench. Hold dumbbells at sides. Torso upright with slight forward tilt.',
        'starting_position_ru': 'Встаньте спиной к скамье на расстоянии шага. Положите подъем задней ноги на скамью. Гантели в руках по бокам.',
        'starting_position_kk': 'Орындықтан бір қадам алға тұрыңыз. Артқы аяқтың үстін орындыққа қойыңыз. Гантельдер қолда, дене түзу.',
        'instructions_en': '1. Descend under control by bending front knee until front thigh is parallel to floor.\n2. Allow front knee to travel slightly forward naturally over toes.\n3. Drive through midfoot and heel of front foot to return to top.\n4. Complete all reps on one leg before switching.',
        'instructions_ru': '1. Плавно опуститесь вниз, сгибая переднее колено до параллели бедра с полом.\n2. Сохраняйте основной вес на передней ноге.\n3. Мощно оттолкнитесь пяткой и серединой стопы передней ноги для подъема.\n4. Выполните все повторения на одну ногу, затем смените сторону.',
        'instructions_kk': '1. Алдыңғы тізені бүгіп, сан еденге параллель болғанша баяу отырыңыз.\n2. Барлық салмақты алдыңғы аяқта ұстаңыз.\n3. Алдыңғы аяқтың өкшесімен күшпен итеріліп, жоғары көтеріліңіз.\n4. Бір аяқпен толық орындап, сосын екінші аяққа ауысыңыз.',
        'breathing_en': 'Inhale on the descent; exhale as you drive back to the top.',
        'breathing_ru': 'Вдох при движении вниз; выдох при подъеме вверх.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; жоғары көтерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Knee caving inward (valgus collapse), leaning too far backward loading the rear leg, bouncing off the bench.',
        'common_mistakes_ru': 'Завал переднего колена внутрь, сильное отклонение назад с перегрузкой задней ноги, отскок от скамьи.',
        'common_mistakes_kk': 'Тізенің ішке қарай майысуы, артқы аяққа тым қатты салмақ салу, орындықтан серпілу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Knee Height',
        'camera_height_ru': 'На уровне коленей',
        'camera_height_kk': 'Тізе деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full body, bench, and both legs must be visible',
        'body_visibility_ru': 'Все тело, скамья и обе ноги должны быть в кадре',
        'body_visibility_kk': 'Толық дене, орындық және қос аяқ анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side to check front knee depth and vertical shin angle.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля глубины приседа и угла наклона голени.',
        'camera_instructions_kk': 'Отыру тереңдігін көру үшін камераны бүйірден тізе деңгейіне қойыңыз.',
        'youtube_id': '2C-uNgKwPLE',
        'video_url': 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 24,
        'category_id': 20,
        'category_name': 'Hamstrings',
        'slug': 'nordic_hamstring_curl',
        'name': 'Nordic Hamstring Curl',
        'name_en': 'Nordic Hamstring Curl',
        'name_ru': 'Нордические сгибания на бицепс бедра (Nordic Curl)',
        'name_kk': 'Норвегиялық аяқ бүгу (Nordic Curl)',
        'target_muscles': 'Hamstrings (Semitendinosus, Biceps Femoris)',
        'target_muscles_en': 'Hamstrings (Eccentric Overload)',
        'target_muscles_ru': 'Бицепс бедра (эксцентрическая нагрузка)',
        'target_muscles_kk': 'Санның артқы бұлшықеті (эксцентрикалық күш)',
        'secondary_muscles_en': 'Glutes, Gastrocnemius, Core',
        'secondary_muscles_ru': 'Ягодицы, икроножные, кор',
        'secondary_muscles_kk': 'Бөксе, балтыр, кор',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight / Partner / Ankle Strap',
        'equipment_ru': 'Свой вес / помощь партнера / фиксатор',
        'equipment_kk': 'Өз салмағы / серіктес көмегі / бекіткіш',
        'difficulty': 'Advanced',
        'difficulty_en': 'Advanced',
        'difficulty_ru': 'Продвинутый',
        'difficulty_kk': 'Жоғары',
        'description': 'The most scientifically validated exercise for preventing hamstring strain injuries and building eccentric strength.',
        'description_en': 'Gold standard eccentric hamstring exercise scientifically proven to drastically reduce hamstring injuries.',
        'description_ru': 'Научно доказанное лучшее упражнение для защиты бицепса бедра от надрывов и максимальной эксцентрической силы.',
        'description_kk': 'Санның артқы бұлшықетін жарақаттан қорғауға арналған ғылыми дәлелденген үздік жаттығу.',
        'starting_position_en': 'Kneel on a padded mat with ankles securely anchored by partner or heavy strap. Torso upright, hips fully extended.',
        'starting_position_ru': 'Встаньте на колени на мягкий коврик, щиколотки надежно зафиксированы. Корпус и бедра образуют прямую линию.',
        'starting_position_kk': 'Тізерлеп төсенішке тұрыңыз, толарсақ мықтап бекітілген. Дене мен сан бір түзу сызықта.',
        'instructions_en': '1. Squeeze glutes and hamstrings, keeping hips locked straight.\n2. Lower torso forward toward floor as slowly as possible using solely hamstring resistance.\n3. Catch yourself with hands when hamstrings reach failure.\n4. Lightly push off the floor and return to start.',
        'instructions_ru': '1. Сожмите ягодицы и пресс, зафиксировав таз в прямом положении.\n2. Максимально медленно опускайте тело вперед к полу, сопротивляясь силой бицепсов бедер.\n3. В конце движения мягко поймайте себя руками на пол.\n4. Легким толчком рук помогите себе вернуться в исходную позицию.',
        'instructions_kk': '1. Бөксе мен корды қатайтып, жамбасты бүкпей түзу ұстаңыз.\n2. Санның артқы бұлшықеттерінің күшімен денені барынша баяу алға түсіріңіз.\n3. Соңында қолмен еденге жұмсақ тіреліңіз.\n4. Қолмен сәл итеріліп, бастапқы қалыпқа оралыңыз.',
        'breathing_en': 'Inhale deeply at the top; exhale with slow control as you descend.',
        'breathing_ru': 'Глубокий вдох вверху; контролируемый выдох при опускании вперед.',
        'breathing_kk': 'Жоғарыда терең тыныс алыңыз; төмен түскенде баяу тыныс шығарыңыз.',
        'common_mistakes_en': 'Bending at the hips (breaking neutral hip line), dropping too fast without resistance, hyperextending neck.',
        'common_mistakes_ru': 'Сгибание в тазобедренных суставах (излом прямой линии тела), быстрое падение вперед без сопротивления.',
        'common_mistakes_kk': 'Жамбастан бүгіліп түзулікті бұзу, салмақты ұстамай тез құлап түсу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Knee / Floor Level',
        'camera_height_ru': 'На уровне коленей/пола',
        'camera_height_kk': 'Тізе / еден деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full lateral body from ankles to head must be in frame',
        'body_visibility_ru': 'Вся боковая линия тела от щиколоток до головы в кадре',
        'body_visibility_kk': 'Толарсақтан басқа дейінгі бүйірлік түзу сызық көрінуі керек',
        'camera_instructions_en': 'Position camera sideways to monitor rigid hip extension during eccentric descent.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля прямой линии бедер и туловища.',
        'camera_instructions_kk': 'Жамбастың бүгілмей түзу түсуін бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'd86sX_V3zP0',
        'video_url': 'https://www.youtube.com/watch?v=d86sX_V3zP0',
        'ideal_rom_degrees': 80.0,
        'normative_cadence_seconds': 4.0,
        'analysis_supported': False,
    }
]
