# -*- coding: utf-8 -*-
# Part 5: Full Body, Cardio, Mobility

EXERCISES_PART5 = [
    # --- FULL BODY ---
    {
        'id': 25,
        'category_id': 24,
        'category_name': 'Full Body',
        'slug': 'kettlebell_swing',
        'name': 'Russian Kettlebell Swing',
        'name_en': 'Russian Kettlebell Swing',
        'name_ru': 'Махи гирей двумя руками (Kettlebell Swing)',
        'name_kk': 'Екі қолмен гир сермеу (Kettlebell Swing)',
        'target_muscles': 'Glutes, Hamstrings, Core, Back',
        'target_muscles_en': 'Glutes, Hamstrings, Core, Posterior Chain',
        'target_muscles_ru': 'Ягодицы, бицепсы бедер, мышцы кора, спина',
        'target_muscles_kk': 'Бөксе, санның артқы жағы, кор, арқа',
        'secondary_muscles_en': 'Shoulders, Forearms, Quadriceps',
        'secondary_muscles_ru': 'Плечи, предплечья, квадрицепсы',
        'secondary_muscles_kk': 'Иық, білек, квадрицепс',
        'equipment': 'Kettlebells',
        'equipment_en': 'Kettlebell',
        'equipment_ru': 'Гиря',
        'equipment_kk': 'Гир',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Explosive hip hinge movement generating maximum posterior chain power and athletic conditioning.',
        'description_en': 'Explosive hip hinge developing posterior chain power, hip snap speed, and cardiovascular conditioning.',
        'description_ru': 'Мощное взрывное тазово-доминантное упражнение для развития взрывной силы бедер и кардиовыносливости.',
        'description_kk': 'Жамбастың жарылыс күшін және төзімділікті дамытатын негізгі функционалды жаттығу.',
        'starting_position_en': 'Stand with feet slightly wider than shoulder-width, kettlebell on floor 1 foot in front. Hinge hips back, grip handle.',
        'starting_position_ru': 'Стопы чуть шире плеч, гиря на полу впереди на расстоянии шага. Наклонитесь в тазу, спина прямая, возьмитесь за дужку.',
        'starting_position_kk': 'Аяқ иықтан сәл кеңірек, гир алдыңызда бір қадам жерде. Жамбастан еңкейіп, тұтқасынан ұстаңыз.',
        'instructions_en': '1. Hike kettlebell back between upper thighs like a football snap.\n2. Drive hips forward explosively, snapping glutes into full vertical lockout.\n3. Let kettlebell float to chest/eye level under hip momentum (arms act only as loose ropes).\n4. Guide kettlebell back into hinge as it falls.',
        'instructions_ru': '1. Замахнитесь гирей назад между бедрами (как в американском футболе).\n2. Мощно разогните таз вперед, сжав ягодицы в конечной вертикальной точке.\n3. Позвольте гире взлететь до уровня груди по инерции (руки расслаблены как тросы).\n4. Подхватите гирю бедрами при обратном движении.',
        'instructions_kk': '1. Гирді аяқтың арасынан артқа қарай сермеңіз.\n2. Жамбасты алға қарай күшпен итеріп, бөксені тік қалыпта қатайтыңыз.\n3. Гир екпінмен кеуде деңгейіне дейін көтерілуі керек (қолдар тек бағыттайды).\n4. Гир төмен түскенде жамбаспен қайта сермеңіз.',
        'breathing_en': 'Inhale deeply on the back hike; exhale sharply and forcefully on the explosive hip snap.',
        'breathing_ru': 'Вдох при замахе назад; резкий мощный выдох при взрывном разгибании таза.',
        'breathing_kk': 'Артқа сермегенде тыныс алыңыз; алға күшпен итергенде қатты тыныс шығарыңыз.',
        'common_mistakes_en': 'Squatting instead of hinging hips, lifting with shoulders/arms instead of hips, rounding lower back.',
        'common_mistakes_ru': 'Приседание вместо тазового наклона (хинджа), подъем гири руками и плечами, скругление поясницы.',
        'common_mistakes_kk': 'Еңкеюдің орнына отырып қалу, гирді жамбаспен емес қолмен тарту, белді бүкірейту.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Hip Level',
        'camera_height_ru': 'На уровне бедер',
        'camera_height_kk': 'Жамбас деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full body from feet to overhead arc must be in frame',
        'body_visibility_ru': 'Все тело от стоп до траектории гири должно быть в кадре',
        'body_visibility_kk': 'Аяқтан гир траекториясына дейінгі толық дене көрінуі керек',
        'camera_instructions_en': 'Position camera sideways to monitor hip hinge depth, neutral spine, and full hip snap lockout.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля глубины наклона и полного выпрямления таза.',
        'camera_instructions_kk': 'Жамбастың толық ашылуын бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'sSESeQAir2M',
        'video_url': 'https://www.youtube.com/watch?v=sSESeQAir2M',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 1.5,
        'analysis_supported': False,
    },
    # --- CARDIO ---
    {
        'id': 26,
        'category_id': 25,
        'category_name': 'Cardio',
        'slug': 'jumping_jacks',
        'name': 'Rhythmic Jumping Jacks',
        'name_en': 'Rhythmic Jumping Jacks',
        'name_ru': 'Прыжки Джампинг Джек (Jumping Jacks)',
        'name_kk': 'Джампинг Джек секіру жаттығуы (Jumping Jacks)',
        'target_muscles': 'Cardiovascular System, Calves, Deltoids',
        'target_muscles_en': 'Cardiovascular Endurance, Calves, Deltoids',
        'target_muscles_ru': 'Сердечно-сосудистая система, икры, дельты',
        'target_muscles_kk': 'Жүрек-қан тамырлары, балтыр, дельталар',
        'secondary_muscles_en': 'Adductors, Abductors, Core',
        'secondary_muscles_ru': 'Приводящие и отводящие мышцы бедра, кор',
        'secondary_muscles_kk': 'Сан бұлшықеттері, кор',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight',
        'equipment_ru': 'Свой вес',
        'equipment_kk': 'Өз салмағы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Rhythmic full-body warm-up and conditioning drill.',
        'description_en': 'Classic full-body cardiovascular warm-up drill enhancing elasticity, rhythm, and heart rate.',
        'description_ru': 'Классическое кардио-упражнение для разминки, повышения пульса и координации всего тела.',
        'description_kk': 'Денені қыздыруға, жүрек соғысын реттеуге және серпімділікті арттыруға арналған жаттығу.',
        'starting_position_en': 'Stand upright with feet together, arms resting relaxed at sides. Tall athletic posture.',
        'starting_position_ru': 'Встаньте прямо, стопы вместе, руки свободно опущены вдоль корпуса.',
        'starting_position_kk': 'Түзу тұрыңыз, аяқтар бірге, қолдар дене жанында еркін түсірілген.',
        'instructions_en': '1. Jump feet out wider than shoulder-width while raising arms overhead in a wide arc.\n2. Land lightly and springily on the balls of your feet with knees soft.\n3. Immediately jump feet back together while bringing arms back down.\n4. Maintain a continuous, brisk rhythm.',
        'instructions_ru': '1. В прыжке расставьте ноги шире плеч, одновременно поднимая руки через стороны над головой.\n2. Приземляйтесь мягко на носки со слегка согнутыми коленями.\n3. Вторым прыжком вернитесь в исходное положение.\n4. Сохраняйте непрерывный бодрый темп.',
        'instructions_kk': '1. Секіріп аяқты иықтан кең қойып, қолды екі жақпен жоғары көтеріңіз.\n2. Тізені сәл бүгіп, аяқтың ұшына жұмсақ түсіңіз.\n3. Қайта секіріп, аяқ пен қолды бастапқы қалыпқа жинаңыз.\n4. Үздіксіз ырғақты сақтаңыз.',
        'breathing_en': 'Maintain steady, continuous rhythmic breathing synchronized with jumps.',
        'breathing_ru': 'Ритмичное ровное дыхание в такт прыжкам.',
        'breathing_kk': 'Секіру ырғағымен бірге бірқалыпты тыныс алыңыз.',
        'common_mistakes_en': 'Landing flat-footed with loud impact, stiff locked knees, flailing arms without control.',
        'common_mistakes_ru': 'Жесткое приземление на всю стопу (удар по суставам), прямые колени, раскоординированные взмахи.',
        'common_mistakes_kk': 'Өкшемен қатты түсу, тізені бүкпеу, қолды ретсіз сермеу.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.5 - 3.5 meters',
        'camera_distance_ru': '2.5 - 3.5 метра',
        'camera_distance_kk': '2.5 - 3.5 метр',
        'body_visibility_en': 'Full standing body from feet to overhead arm clap must be in frame',
        'body_visibility_ru': 'Все тело в полный рост с вытянутыми вверх руками должно быть в кадре',
        'body_visibility_kk': 'Аяқтан жоғары созылған қолдарға дейінгі толық дене көрінуі керек',
        'camera_instructions_en': 'Position camera in front to track jumping cadence, symmetry, and foot spread width.',
        'camera_instructions_ru': 'Установите камеру спереди для контроля темпа, ритма и синхронности движений.',
        'camera_instructions_kk': 'Секіру ырғағы мен қол-аяқ қозғалысын көру үшін камераны алдыңыздан қойыңыз.',
        'youtube_id': 'iSSAk4XCsRA',
        'video_url': 'https://www.youtube.com/watch?v=iSSAk4XCsRA',
        'ideal_rom_degrees': 180.0,
        'normative_cadence_seconds': 1.0,
        'analysis_supported': False,
    },
    # --- MOBILITY ---
    {
        'id': 27,
        'category_id': 26,
        'category_name': 'Mobility',
        'slug': 'worlds_greatest_stretch',
        'name': 'Worlds Greatest Stretch',
        'name_en': "World's Greatest Stretch",
        'name_ru': "Величайшая растяжка в мире (World's Greatest Stretch)",
        'name_kk': "Әлемдегі ең үздік созылу жаттығуы (World's Greatest Stretch)",
        'target_muscles': 'Thoracic Spine, Hip Flexors, Hamstrings',
        'target_muscles_en': 'Thoracic Spine, Hip Flexors, Hamstrings, Adductors',
        'target_muscles_ru': 'Грудной отдел позвоночника, сгибатели бедра, бицепс бедра',
        'target_muscles_kk': 'Кеуде омыртқасы, жамбас бұлшықеттері, санның артқы жағы',
        'secondary_muscles_en': 'Glutes, Shoulders, Calves',
        'secondary_muscles_ru': 'Ягодицы, плечи, икры',
        'secondary_muscles_kk': 'Бөксе, иықтар, балтыр',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight / Mat',
        'equipment_ru': 'Свой вес / коврик',
        'equipment_kk': 'Өз салмағы / төсеніш',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Multi-planar full body mobility dynamic sequence.',
        'description_en': 'The pinnacle full-body dynamic mobility flow opening hips, ankles, and thoracic spine rotation.',
        'description_ru': 'Лучший комплексный комплекс динамической растяжки для раскрытия тазобедренных суставов и мобильности грудного отдела.',
        'description_kk': 'Жамбас буындары мен кеуде омыртқасының қозғалғыштығын ашатын ең үздік кешенді созылу жаттығуы.',
        'starting_position_en': "Start in a high plank. Step right foot forward outside right hand into a deep runner's lunge.",
        'starting_position_ru': 'Начните в упоре лежа. Сделайте широкий шаг правой ногой вперед к внешней стороне правой ладони.',
        'starting_position_kk': 'Қолға сүйеніп тұрыңыз. Оң аяқпен оң қолдың сырт жағына қарай кең қадам жасаңыз.',
        'instructions_en': '1. Drop right elbow down inside right instep, holding for a deep hip flexor stretch.\n2. Rotate chest and right arm up toward the ceiling, gazing at your hand.\n3. Return hand to floor, shift hips backward to straighten front leg into a hamstring stretch.\n4. Return to plank and repeat on opposite side.',
        'instructions_ru': '1. Опустите правый локоть вниз к внутренней части стопы, почувствуйте растяжение бедер.\n2. Разверните грудную клетку и правую руку вверх к потолку, взгляд за рукой.\n3. Опустите руку на пол, отведите таз назад и выпрямите переднюю ногу (растяжка задней поверхности).\n4. Вернитесь в планку и повторите на левую сторону.',
        'instructions_kk': '1. Оң шынтақты оң табанның ішкі жағына түсіріп, жамбасты созыңыз.\n2. Кеудені және оң қолды жоғары төбеге қарай бұрып, қолға қараңыз.\n3. Қолды еденге қойып, жамбасты артқа жылжытып, алдыңғы аяқты созыңыз.\n4. Планкаға оралып, екінші жаққа қайталаңыз.',
        'breathing_en': 'Inhale deeply as you rotate and open upward; exhale as you reach down and stretch back.',
        'breathing_ru': 'Глубокий вдох при развороте вверх; выдох при опускании локтя и растяжке ноги.',
        'breathing_kk': 'Жоғары бұрылғанда тыныс алыңыз; төмен созылғанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Rushing through positions, letting back knee collapse heavily onto floor, avoiding deep breathing.',
        'common_mistakes_ru': 'Спешка без фиксации точек, падение заднего колена на пол, задержка дыхания.',
        'common_mistakes_kk': 'Асығыс жасау, артқы тізені еденге құлату, тынысты ұстау.',
        'camera_angle_en': 'Side or 45° View',
        'camera_angle_ru': 'Вид сбоку или под 45°',
        'camera_angle_kk': 'Бүйір немесе 45° бұрыштан',
        'camera_height_en': 'Floor Level',
        'camera_height_ru': 'На уровне пола',
        'camera_height_kk': 'Еден деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Full lunge position, arms, and thoracic rotation must be captured',
        'body_visibility_ru': 'Положение выпада, руки и поворот грудного отдела должны быть видны',
        'body_visibility_kk': 'Кең қадам, қолдар және дененің бұрылуы толық көрінуі керек',
        'camera_instructions_en': 'Position camera at low level to verify hip sink depth and vertical thoracic arm reach.',
        'camera_instructions_ru': 'Установите камеру на уровне пола для контроля глубины выпада и угла раскрытия грудной клетки.',
        'camera_instructions_kk': 'Қадам тереңдігі мен қолдың ашылуын көру үшін камераны еден биіктігіне қойыңыз.',
        'youtube_id': '8z5R4x6YV4s',
        'video_url': 'https://www.youtube.com/watch?v=8z5R4x6YV4s',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 5.0,
        'analysis_supported': False,
    }
]
