# -*- coding: utf-8 -*-
# Part 3: Biceps, Triceps, Forearms

EXERCISES_PART3 = [
    # --- BICEPS ---
    {
        'id': 15,
        'category_id': 10,
        'category_name': 'Biceps',
        'slug': 'barbell_bicep_curl',
        'name': 'Barbell Bicep Curl',
        'name_en': 'Barbell Bicep Curl',
        'name_ru': 'Подъем штанги на бицепс стоя',
        'name_kk': 'Тұрып штанганы бицепске көтеру',
        'target_muscles': 'Biceps Brachii (Long & Short Head)',
        'target_muscles_en': 'Biceps Brachii',
        'target_muscles_ru': 'Двуглавая мышца плеча (бицепс)',
        'target_muscles_kk': 'Қолдың екі басты бұлшықеті (бицепс)',
        'secondary_muscles_en': 'Brachialis, Forearm Flexors',
        'secondary_muscles_ru': 'Плечевая мышца, сгибатели предплечья',
        'secondary_muscles_kk': 'Иық бұлшықеті, білек бұлшықеттері',
        'equipment': 'Barbell',
        'equipment_en': 'Barbell / EZ Bar',
        'equipment_ru': 'Штанга / EZ-гриф',
        'equipment_kk': 'Штанга / EZ-гриф',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'High-overload bilateral arm flexion movement for maximal bicep hypertrophy and arm power.',
        'description_en': 'Fundamental bilateral arm flexion builder allowing maximal overload for bicep mass.',
        'description_ru': 'Главное базовое упражнение для наращивания максимальной массы и силы двуглавой мышцы плеча.',
        'description_kk': 'Бицепстің күші мен көлемін арттыруға арналған негізгі штанга жаттығуы.',
        'starting_position_en': 'Stand upright holding barbell with underhand shoulder-width grip. Arms straight, elbows pinned to sides.',
        'starting_position_ru': 'Встаньте ровно, удерживая штангу хватом снизу на ширине плеч. Локти зафиксированы по бокам.',
        'starting_position_kk': 'Түзу тұрыңыз, штанганы астынан иық енінде ұстаңыз. Шынтақты денеге жабыстырыңыз.',
        'instructions_en': '1. Curl the barbell up toward shoulder height by flexing at the elbows.\n2. Keep upper arms completely stationary.\n3. Squeeze biceps hard at top contraction for 1 second.\n4. Lower the bar smoothly under a 3-second eccentric tempo.',
        'instructions_ru': '1. Сгибая руки в локтях, поднимите штангу по дуге к уровню плеч.\n2. Сохраняйте плечевые кости строго неподвижными.\n3. Максимально сожмите бицепсы в верхней точке на 1 секунду.\n4. Плавно опустите гриф вниз за 3 секунды.',
        'instructions_kk': '1. Шынтақты бүгіп, штанганы иық деңгейіне қарай көтеріңіз.\n2. Қолдың жоғарғы бөлігін қозғалтпай ұстаңыз.\n3. Жоғарғы нүктеде бицепсті 1 секунд қатайтыңыз.\n4. Штанганы 3 секунд ішінде баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale as you curl the bar up; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при подъеме штанги; вдох при плавном опускании.',
        'breathing_kk': 'Штанганы көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Swinging torso back and forth, drifting elbows forward, incomplete extension at the bottom.',
        'common_mistakes_ru': 'Раскачивание корпусом назад, увод локтей вперед, неполное разгибание рук внизу.',
        'common_mistakes_kk': 'Денемен алға-артқа тербелу, шынтақты алға жылжыту, төменде қолды толық жазбау.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Full torso, elbows, and barbell arc must be captured',
        'body_visibility_ru': 'Корпус, локти и траектория движения штанги должны быть видны',
        'body_visibility_kk': 'Дене, шынтақтар және штанга қозғалысы анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera from the side to monitor upper-arm stillness and torso momentum.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля неподвижности локтей и отсутствия раскачки спиной.',
        'camera_instructions_kk': 'Шынтақтың қозғалмай тұрғанын және дененің тербелмеуін көру үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'ykJmrZ5v0Oo',
        'video_url': 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
        'ideal_rom_degrees': 120.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    {
        'id': 16,
        'category_id': 10,
        'category_name': 'Biceps',
        'slug': 'hammer_curl',
        'name': 'Dumbbell Hammer Curl',
        'name_en': 'Dumbbell Hammer Curl',
        'name_ru': 'Молотковые сгибания с гантелями (Hammer Curls)',
        'name_kk': 'Балға тәрізді гантель көтеру (Hammer Curls)',
        'target_muscles': 'Brachialis, Brachioradialis, Biceps',
        'target_muscles_en': 'Brachialis, Brachioradialis (Forearms)',
        'target_muscles_ru': 'Плечевая мышца (брахиалис), плечелучевая мышца',
        'target_muscles_kk': 'Иық бұлшықеті (брахиалис), иық-кәрі жілік бұлшықеті',
        'secondary_muscles_en': 'Biceps Brachii, Wrist Stabilizers',
        'secondary_muscles_ru': 'Бицепс, стабилизаторы кисти',
        'secondary_muscles_kk': 'Бицепс, білек тұрақтандырғыштары',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells',
        'equipment_ru': 'Гантели',
        'equipment_kk': 'Гантельдер',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Neutral-grip arm flexion building arm thickness, brachialis height, and grip strength.',
        'description_en': 'Neutral-grip flexion drill maximizing brachialis recruitment for overall upper arm thickness.',
        'description_ru': 'Сгибания рук нейтральным хватом для прокачки плечелучевой мышцы и визуальной толщины рук.',
        'description_kk': 'Қолдың қалыңдығы мен ұстау күшін арттыруға арналған бейтарап ұстаумен жасалатын жаттығу.',
        'starting_position_en': 'Stand tall with dumbbells held at sides with neutral palms-facing-inward grip. Arms extended.',
        'starting_position_ru': 'Встаньте ровно, удерживая гантели по бокам нейтральным хватом (ладони смотрят друг на друга).',
        'starting_position_kk': 'Түзу тұрыңыз, гантельдерді бейтарап қалыпта ұстаңыз (алақандар бір-біріне қараған).',
        'instructions_en': '1. Keep palms facing inward throughout the entire repetition.\n2. Curl dumbbells upward toward shoulders.\n3. Squeeze forearms and brachialis at the top.\n4. Lower smoothly with 2-second resistance.',
        'instructions_ru': '1. Сохраняйте нейтральный хват (ладони внутрь) на всем протяжении движения.\n2. Поднимите гантели к плечам силой рук.\n3. Зафиксируйте пиковое напряжение вверху.\n4. Плавно опустите гантели вниз за 2 секунды.',
        'instructions_kk': '1. Алақанды ішке қаратқан күйде жаттығу соңына дейін сақтаңыз.\n2. Гантельдерді иыққа қарай көтеріңіз.\n3. Жоғарғы нүктеде бұлшықеттерді қатайтыңыз.\n4. 2 секундта баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale on the curl upward; inhale as dumbbells descend.',
        'breathing_ru': 'Выдох при подъеме гантелей; вдох при опускании.',
        'breathing_kk': 'Гантельді көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Twisting wrists, swinging hips for momentum, dropping dumbbells rapidly.',
        'common_mistakes_ru': 'Разворот кистей (супинация), раскачка бедрами, резкий бросок веса вниз.',
        'common_mistakes_kk': 'Білекті бұру, жамбаспен екпін беру, гантельді тез тастай салу.',
        'camera_angle_en': 'Front or 45° Side View',
        'camera_angle_ru': 'Вид спереди или сбоку под 45°',
        'camera_angle_kk': 'Алдыңғы немесе 45° бүйір көрініс',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Upper body, arms, and dumbbells in frame',
        'body_visibility_ru': 'Верхняя часть корпуса, руки и гантели в кадре',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі, қолдар және гантельдер көрінуі керек',
        'camera_instructions_en': 'Position camera from the side/front to monitor neutral wrist alignment and arm stillness.',
        'camera_instructions_ru': 'Установите камеру под углом 45° для контроля нейтрального положения кистей.',
        'camera_instructions_kk': 'Білектің түзулігін бақылау үшін камераны 45° бұрышпен қойыңыз.',
        'youtube_id': 'zC3nLlEvin4',
        'video_url': 'https://www.youtube.com/watch?v=zC3nLlEvin4',
        'ideal_rom_degrees': 115.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    # --- TRICEPS ---
    {
        'id': 17,
        'category_id': 11,
        'category_name': 'Triceps',
        'slug': 'tricep_pushdown',
        'name': 'Cable Tricep Pushdown',
        'name_en': 'Cable Tricep Pushdown',
        'name_ru': 'Разгибание рук на блоке на трицепс (с канатом)',
        'name_kk': 'Блокта қолды жазу (трицепс / канат)',
        'target_muscles': 'Triceps Brachii (Lateral & Medial Heads)',
        'target_muscles_en': 'Triceps Brachii (Lateral & Medial Heads)',
        'target_muscles_ru': 'Трицепс (латеральная и медиальная головки)',
        'target_muscles_kk': 'Трицепс (сыртқы және ортаңғы бастары)',
        'secondary_muscles_en': 'Forearm Extensors, Core Stabilizers',
        'secondary_muscles_ru': 'Предплечья, мышцы кора',
        'secondary_muscles_kk': 'Білек, кор тұрақтандырғыштары',
        'equipment': 'Cables',
        'equipment_en': 'Cable Machine & Rope Attachment',
        'equipment_ru': 'Блочный тренажер и канатная рукоять',
        'equipment_kk': 'Блоктық тренажер және арқан тұтқасы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Isolated elbow extension for arm development.',
        'description_en': 'Classic triceps isolation movement providing sustained tension and horseshoe definition.',
        'description_ru': 'Базовое изолирующее упражнение для прорисовки и накачки всех головок трицепса.',
        'description_kk': 'Трицепсті толық созуға және қатайтуға арналған негізгі оқшауланған жаттығу.',
        'starting_position_en': 'Stand upright with a slight forward lean. Grip rope attachment with elbows bent at 90° and tucked into sides.',
        'starting_position_ru': 'Встаньте ровно с легким наклоном вперед. Локти согнуты под 90° и плотно прижаты к ребрам.',
        'starting_position_kk': 'Сәл алға еңкейіп түзу тұрыңыз. Шынтақ 90° бүгілген және денеге жабыстырылған.',
        'instructions_en': '1. Keep elbows pinned to your sides throughout.\n2. Extend arms downward until fully locked out.\n3. Flare rope ends outward slightly at the bottom for peak contraction.\n4. Return smoothly to 90° elbow flexion.',
        'instructions_ru': '1. Зафиксируйте локти неподвижно по бокам корпуса.\n2. Разгибайте руки вниз до полного выпрямления в локтях.\n3. В нижней точке разведите концы каната в стороны для максимального пика.\n4. Плавно вернитесь в исходное положение (угол 90° в локтях).',
        'instructions_kk': '1. Шынтақты денеге қозғалтпай жабыстырып ұстаңыз.\n2. Қолды төмен қарай толық жазылғанша созыңыз.\n3. Төменгі нүктеде арқанды екі жаққа сәл ашып, трицепсті қатайтыңыз.\n4. Шынтақты 90° бүгіп баяу бастапқы қалыпқа қайтыңыз.',
        'breathing_en': 'Exhale as you push down to extension; inhale as arms return upward.',
        'breathing_ru': 'Выдох при разгибании рук вниз; вдох при сгибании вверх.',
        'breathing_kk': 'Төмен жазғанда тыныс шығарыңыз; жоғары бүккенде тыныс алыңыз.',
        'common_mistakes_en': 'Letting elbows drift forward and backward, using body weight to lean over the bar, half-reps.',
        'common_mistakes_ru': 'Хождение локтей вперед-назад, наваливание всем весом тела на рукоять, неполное разгибание.',
        'common_mistakes_kk': 'Шынтақты алға-артқа жылжыту, бүкіл салмақпен үстіне құлау, қолды толық жазбау.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Chest / Hip Height',
        'camera_height_ru': 'На уровне груди/бедер',
        'camera_height_kk': 'Кеуде / жамбас деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Full torso, elbows, and cable path must be framed',
        'body_visibility_ru': 'Корпус, положение локтей и трос тренажера должны быть видны',
        'body_visibility_kk': 'Дене, шынтақ қалпы және тренажер тросы толық көрінуі керек',
        'camera_instructions_en': 'Position camera from the side to monitor elbow stillness and complete arm extension lockout.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля фиксации локтей и полного разгибания рук.',
        'camera_instructions_kk': 'Шынтақтың қозғалмауын және қолдың толық жазылуын көру үшін камераны бүйірден қойыңыз.',
        'youtube_id': '2-LAMcpzODU',
        'video_url': 'https://www.youtube.com/watch?v=2-LAMcpzODU',
        'ideal_rom_degrees': 110.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 18,
        'category_id': 11,
        'category_name': 'Triceps',
        'slug': 'skull_crushers',
        'name': 'EZ Bar Skull Crushers',
        'name_en': 'EZ Bar Skull Crushers',
        'name_ru': 'Французский жим лежа со штангой (Skull Crushers)',
        'name_kk': 'Жатып француз жимі (Skull Crushers)',
        'target_muscles': 'Triceps Brachii (Long & Medial Heads)',
        'target_muscles_en': 'Triceps Brachii (Long Head Focus)',
        'target_muscles_ru': 'Длинная и медиальная головки трицепса',
        'target_muscles_kk': 'Трицепстің ұзын және ортаңғы бастары',
        'secondary_muscles_en': 'Anterior Deltoids, Forearms',
        'secondary_muscles_ru': 'Передняя дельта, предплечья',
        'secondary_muscles_kk': 'Алдыңғы дельта, білектер',
        'equipment': 'Barbell',
        'equipment_en': 'EZ Bar & Flat Bench',
        'equipment_ru': 'EZ-штанга и горизонтальная скамья',
        'equipment_kk': 'EZ-штанга және жазық орындық',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Premier triceps mass builder targeting the long head under deep overhead stretch.',
        'description_en': 'Classic lying triceps extension isolating the long head with maximum eccentric stretch.',
        'description_ru': 'Эффективное упражнение для максимального растяжения и развития длинной головки трицепса.',
        'description_kk': 'Трицепстің ұзын басын терең созуға және күшейтуге арналған классикалық жаттығу.',
        'starting_position_en': 'Lie on flat bench holding EZ bar with narrow overhand grip. Arms extended with a slight backward 10-15° angle.',
        'starting_position_ru': 'Лягте на скамью, удерживая EZ-гриф узким хватом. Руки выпрямлены и слегка наклонены назад (10-15°).',
        'starting_position_kk': 'Орындыққа жатып, EZ-штанганы жіңішке ұстаңыз. Қолды түзу ұстап, сәл артқа 10-15° еңкейтіңіз.',
        'instructions_en': '1. Keep upper arms stationary angled back.\n2. Bend elbows to lower the bar toward your forehead or crown of head.\n3. Feel a deep stretch in the triceps.\n4. Extend elbows powerfully back to the angled starting position.',
        'instructions_ru': '1. Удерживайте плечевые кости неподвижными под небольшим углом назад.\n2. Сгибая только локти, опустите гриф к макушке головы.\n3. Почувствуйте глубокое растяжение в трицепсах.\n4. Разгибая локти, мощно верните гриф в исходную точку.',
        'instructions_kk': '1. Қолдың жоғарғы бөлігін артқа қарай қозғалтпай ұстаңыз.\n2. Тек шынтақты бүгіп, штанганы маңдайға немесе төбеге қарай түсіріңіз.\n3. Трицепстің созылғанын сезініңіз.\n4. Шынтақты жазып, бастапқы қалыпқа күшпен қайтыңыз.',
        'breathing_en': 'Inhale as bar lowers to forehead; exhale as you extend arms.',
        'breathing_ru': 'Вдох при опускании штанги к голове; выдох при выпрямлении рук.',
        'breathing_kk': 'Штанганы түсіргенде тыныс алыңыз; қолды жазғанда тыныс шығарыңыз.',
        'common_mistakes_en': 'Flaring elbows outward, turning movement into a close-grip press by moving shoulders, dropping bar too fast.',
        'common_mistakes_ru': 'Разведение локтей в стороны, превращение в жим узким хватом, резкое падение штанги к лицу.',
        'common_mistakes_kk': 'Шынтақты жан-жаққа ашу, жаттығуды жимге айналдыру, штанганы бетке қарай тез құлату.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Bench Height',
        'camera_height_ru': 'На уровне скамьи',
        'camera_height_kk': 'Орындық деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Head, bench, arms, and barbell path must be in frame',
        'body_visibility_ru': 'Голова, скамья, руки и траектория штанги должны быть видны',
        'body_visibility_kk': 'Бас, орындық, қолдар және штанга анық көрінуі керек',
        'camera_instructions_en': 'Position camera sideways at bench height to observe elbow angle and bar path control.',
        'camera_instructions_ru': 'Установите камеру сбоку на уровне скамьи для контроля угла локтей и траектории штанги.',
        'camera_instructions_kk': 'Шынтақ бұрышы мен штанга қозғалысын бақылау үшін камераны орындық биіктігіне қойыңыз.',
        'youtube_id': 'd_KZxkY_0cM',
        'video_url': 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
        'ideal_rom_degrees': 100.0,
        'normative_cadence_seconds': 3.0,
        'analysis_supported': False,
    },
    # --- FOREARMS ---
    {
        'id': 19,
        'category_id': 12,
        'category_name': 'Forearms',
        'slug': 'farmer_carry',
        'name': 'Heavy Farmer Carry',
        'name_en': 'Heavy Farmer Carry',
        'name_ru': 'Прогулка фермера с гантелями / гирями',
        'name_kk': 'Фермер жүрісі (гантельмен / гирмен)',
        'target_muscles': 'Forearm Flexors, Grip Strength, Trapezius',
        'target_muscles_en': 'Forearm Flexors, Grip Strength, Trapezius',
        'target_muscles_ru': 'Сгибатели предплечья, сила хвата, трапеции',
        'target_muscles_kk': 'Білек бүккіштері, ұстау күші, трапеция',
        'secondary_muscles_en': 'Core Stabilizers, Glutes, Calves',
        'secondary_muscles_ru': 'Мышцы кора, ягодицы, икры',
        'secondary_muscles_kk': 'Кор тұрақтандырғыштары, бөксе, балтыр',
        'equipment': 'Dumbbells',
        'equipment_en': 'Heavy Dumbbells / Kettlebells',
        'equipment_ru': 'Тяжелые гантели / гири',
        'equipment_kk': 'Ауыр гантельдер / гирлер',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Functional loaded carry testing whole-body postural endurance, crushing grip strength, and core stability.',
        'description_en': 'Functional loaded carry building crushing grip strength, scapular endurance, and whole-body core stability.',
        'description_ru': 'Фундаментальное функциональное упражнение для развития железного хвата, трапеций и стабильности кора.',
        'description_kk': 'Қолдың мықты ұстау күшін, трапецияны және дененің тұрақтылығын дамытатын функционалды жаттығу.',
        'starting_position_en': 'Stand between two heavy dumbbells/kettlebells. Deadlift weights up safely with flat back. Stand upright with tall posture.',
        'starting_position_ru': 'Встаньте между тяжелыми гантелями. Безопасно поднимите их с прямой спиной. Выпрямитесь, расправьте плечи.',
        'starting_position_kk': 'Ауыр гантельдердің ортасында тұрып, арқаны түзу ұстап көтеріңіз. Иықты жазып тік тұрыңыз.',
        'instructions_en': '1. Maintain a tall posture with shoulders down and back.\n2. Walk forward in a straight line with controlled, deliberate strides.\n3. Keep core rigidly braced and prevent side-to-side torso sway.\n4. Walk for prescribed distance or 30-45 seconds.',
        'instructions_ru': '1. Держите осанку идеально ровной, плечи расправлены и опущены.\n2. Идите вперед ровным шагом по прямой линии.\n3. Держите пресс напряженным, избегая раскачивания корпуса в стороны.\n4. Пройдите намеченную дистанцию или 30-45 секунд под нагрузкой.',
        'instructions_kk': '1. Денені түзу ұстап, иықты артқа қарай жиырыңыз.\n2. Түзу сызық бойымен нық, баяу қадамдармен алға жүріңіз.\n3. Дененің екі жаққа шайқалмауын қадағалап, корды қатайтыңыз.\n4. Белгіленген қашықтықты немесе 30-45 секунд бойы жүріңіз.',
        'breathing_en': 'Breathe steadily in short, controlled diaphragmatic breaths while keeping core braced.',
        'breathing_ru': 'Короткое контролируемое дыхание животом при постоянном напряжении пресса.',
        'breathing_kk': 'Кор қатайтылған күйде бірқалыпты және ырғақты тыныс алыңыз.',
        'common_mistakes_en': 'Slouching shoulders forward, wobbling torso, taking rushed uncontrolled running steps.',
        'common_mistakes_ru': 'Сутулость плеч вперед, боковая раскачка туловища, слишком быстрые семенящие шаги.',
        'common_mistakes_kk': 'Иықты алға бүкірейту, дененің шайқалуы, асығыс жүгіріп кету.',
        'camera_angle_en': 'Front or Side Tracking View',
        'camera_angle_ru': 'Вид спереди или сбоку',
        'camera_angle_kk': 'Алдыңғы немесе бүйір көрініс',
        'camera_height_en': 'Hip Height',
        'camera_height_ru': 'На уровне бедер',
        'camera_height_kk': 'Жамбас деңгейінде',
        'camera_distance_en': '3.0 - 4.5 meters',
        'camera_distance_ru': '3.0 - 4.5 метра',
        'camera_distance_kk': '3.0 - 4.5 метр',
        'body_visibility_en': 'Full standing body and walking corridor must be in frame',
        'body_visibility_ru': 'Все тело в полный рост и траектория ходьбы должны быть в кадре',
        'body_visibility_kk': 'Толық дене және жүру жолы анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera at hip height with wide field of view to analyze upright postural symmetry.',
        'camera_instructions_ru': 'Установите камеру на уровне бедер с широким обзором для оценки симметрии осанки при ходьбе.',
        'camera_instructions_kk': 'Жүру кезіндегі дене түзулігін көру үшін камераны жамбас биіктігіне қойыңыз.',
        'youtube_id': 'Fkzk_RqlXP0',
        'video_url': 'https://www.youtube.com/watch?v=Fkzk_RqlXP0',
        'ideal_rom_degrees': 180.0,
        'normative_cadence_seconds': 30.0,
        'analysis_supported': False,
    }
]
