# -*- coding: utf-8 -*-
# Part 2: Shoulders, Delts, Traps, Neck

EXERCISES_PART2 = [
    # --- LATERAL DELTS ---
    {
        'id': 10,
        'category_id': 8,
        'category_name': 'Lateral Delts',
        'slug': 'dumbbell_lateral_raise',
        'name': 'Dumbbell Lateral Raise',
        'name_en': 'Dumbbell Lateral Raise',
        'name_ru': 'Махи гантелями в стороны',
        'name_kk': 'Гантельді екі жаққа көтеру',
        'target_muscles': 'Lateral Deltoids',
        'target_muscles_en': 'Lateral Deltoids (Middle Head)',
        'target_muscles_ru': 'Средняя дельтовидная мышца',
        'target_muscles_kk': 'Ортаңғы дельта бұлшықеті',
        'secondary_muscles_en': 'Anterior Deltoids, Upper Trapezius, Supraspinatus',
        'secondary_muscles_ru': 'Передняя дельта, верх трапеции, надостная мышца',
        'secondary_muscles_kk': 'Алдыңғы дельта, жоғарғы трапеция',
        'equipment': 'Dumbbells',
        'equipment_en': 'Dumbbells',
        'equipment_ru': 'Гантели',
        'equipment_kk': 'Гантельдер',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Premier isolation drill building broad shoulder width and deltoid capping.',
        'description_en': 'Premier deltoid isolation exercise building lateral shoulder width and 3D silhouette.',
        'description_ru': 'Главное изолирующее упражнение для расширения плеч и акцентированной накачки средних дельт.',
        'description_kk': 'Иықты кеңейтуге және ортаңғы дельтаны қатайтуға арналған негізгі жаттығу.',
        'starting_position_en': 'Stand with feet hip-width, slight forward torso tilt (10°), holding dumbbells at sides with neutral grip.',
        'starting_position_ru': 'Стопы на ширине таза, легкий наклон корпуса вперед (10°), гантели по бокам, руки слегка согнуты в локтях.',
        'starting_position_kk': 'Аяқ жамбас енінде, денені 10° сәл алға еңкейтіңіз, гантельдер дене жанында, шынтақ сәл бүгілген.',
        'instructions_en': '1. Lead with elbows and raise arms out to sides in scapular plane (slight 20-30° forward angle).\n2. Lift until dumbbells reach shoulder height (parallel to floor).\n3. Pause briefly at peak contraction.\n4. Lower with 2-second control without letting dumbbells slam together.',
        'instructions_ru': '1. Поднимайте руки через стороны, ведя движение локтями в плоскости лопаток (чуть вперед на 20-30°).\n2. Поднимите гантели до уровня плеч параллельно полу.\n3. Зафиксируйте пиковое напряжение на доли секунды.\n4. Плавно опустите за 2 секунды, не сводя гантели вплотную перед собой.',
        'instructions_kk': '1. Шынтақты жетекші етіп, қолды екі жаққа қарай көтеріңіз (сәл алға 20-30°).\n2. Гантельдер иық деңгейіне жеткенше көтеріңіз.\n3. Жоғарғы нүктеде бұлшықетті қатайтыңыз.\n4. Гантельдерді 2 секундта баяу төмен түсіріңіз.',
        'breathing_en': 'Exhale as you raise the dumbbells; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при подъеме гантелей через стороны; вдох при плавном опускании.',
        'breathing_kk': 'Гантельді көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Swinging torso/using leg drive, raising above shoulder plane shrugging traps, bent wrists pointing up.',
        'common_mistakes_ru': 'Импульс ногами и раскачка корпусом, задирание рук выше плеч со шрагами трапеции, кисти выше локтей.',
        'common_mistakes_kk': 'Денемен және аяқпен серпілу, қолды иықтан асыра көтеріп трапецияға салмақ түсіру, білекті шынтақтан жоғары көтеру.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.2 - 3.0 meters',
        'camera_distance_ru': '2.2 - 3.0 метра',
        'camera_distance_kk': '2.2 - 3.0 метр',
        'body_visibility_en': 'Full upper body and full arm wingspan must be in frame',
        'body_visibility_ru': 'Верхняя часть корпуса и полный размах обеих рук должны быть в кадре',
        'body_visibility_kk': 'Дененің жоғарғы бөлігі мен екі қолдың созылуы толық көрінуі керек',
        'camera_instructions_en': 'Position camera directly in front to track bilateral arm abduction height and shoulder symmetry.',
        'camera_instructions_ru': 'Установите камеру спереди для проверки высоты подъема и симметрии обоих локтей.',
        'camera_instructions_kk': 'Екі қолдың көтерілу биіктігі мен симметриясын бақылау үшін камераны тікелей алдыңыздан қойыңыз.',
        'youtube_id': '3VcKaXpzqRo',
        'video_url': 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
        'ideal_rom_degrees': 85.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 11,
        'category_id': 7,
        'category_name': 'Front Delts',
        'slug': 'pike_pushup',
        'name': 'Pike Push-up',
        'name_en': 'Pike Push-up',
        'name_ru': 'Отжимания домиком (Pike Push-up)',
        'name_kk': 'Бұрыш жасап сығылу (Pike Push-up)',
        'target_muscles': 'Anterior Deltoids, Triceps',
        'target_muscles_en': 'Anterior Deltoids, Clavicular Pectoralis',
        'target_muscles_ru': 'Передние дельты, верх груди',
        'target_muscles_kk': 'Алдыңғы дельталар, кеуденің жоғарғы жағы',
        'secondary_muscles_en': 'Triceps Brachii, Upper Trapezius, Serratus Anterior',
        'secondary_muscles_ru': 'Трицепсы, верх трапеции, зубчатые мышцы',
        'secondary_muscles_kk': 'Трицепстер, жоғарғы трапеция',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight',
        'equipment_ru': 'Свой вес',
        'equipment_kk': 'Өз салмағы',
        'difficulty': 'Intermediate',
        'difficulty_en': 'Intermediate',
        'difficulty_ru': 'Средний',
        'difficulty_kk': 'Орташа',
        'description': 'Calisthenics overhead pressing progression developing front delt strength and handstand foundation.',
        'description_en': 'Bodyweight vertical pressing movement targeting front deltoids and scapular upward rotation.',
        'description_ru': 'Эффективное упражнение с собственным весом для прокачки передних дельт и подготовки к стойке на руках.',
        'description_kk': 'Алдыңғы дельтаны қатайтуға және қолмен тұруға дайындалуға арналған өз салмағымен жасалатын жаттығу.',
        'starting_position_en': 'Assume downward dog position: hands shoulder-width, hips piked high toward ceiling, head between arms.',
        'starting_position_ru': 'Примите позу собаки мордой вниз: ладони на ширине плеч, таз высоко поднят, ноги прямые, голова между руками.',
        'starting_position_kk': 'Иттің төмен қараған қалпын қабылдаңыз: алақан иық енінде, жамбас жоғары көтерілген, бас қолдар арасында.',
        'instructions_en': '1. Lower crown of head forward and down in a tripod triangle ahead of your hands.\n2. Descend until forehead lightly taps the floor.\n3. Push back and up diagonally to return to the piked start position.\n4. Keep hips elevated throughout.',
        'instructions_ru': '1. Опускайте голову вперед по диагонали перед ладонями, образуя треугольник.\n2. Коснитесь лбом пола под контролем.\n3. Вытолкните себя назад и вверх по диагонали в исходную позу домика.\n4. Держите таз высоко поднятым на протяжении всего движения.',
        'instructions_kk': '1. Басты алақандардың алдына қарай диагональ бойынша түсіріңіз.\n2. Маңдай еденге жеңіл тигенше төмендеңіз.\n3. Қолмен күшпен итеріліп, бастапқы бұрыш қалпына қайтыңыз.\n4. Жамбасты үнемі жоғары көтеріп ұстаңыз.',
        'breathing_en': 'Inhale on the diagonal descent; exhale as you push back up.',
        'breathing_ru': 'Вдох при опускании головы к полу; выдох при диагональном выталкивании вверх.',
        'breathing_kk': 'Төмен түскенде тыныс алыңыз; жоғары итерілгенде тыныс шығарыңыз.',
        'common_mistakes_en': 'Letting hips drop into a standard push-up, flaring elbows out, craning neck backwards.',
        'common_mistakes_ru': 'Опускание таза вниз (превращение в обычные отжимания), разведение локтей в стороны.',
        'common_mistakes_kk': 'Жамбасты төмен түсіріп кәдімгі сығылуға айналдыру, шынтақты жан-жаққа ашу.',
        'camera_angle_en': 'Side View (90°)',
        'camera_angle_ru': 'Вид сбоку (90°)',
        'camera_angle_kk': 'Бүйірден көрініс (90°)',
        'camera_height_en': 'Floor / Knee Level',
        'camera_height_ru': 'На уровне пола/коленей',
        'camera_height_kk': 'Еден / тізе деңгейінде',
        'camera_distance_en': '2.5 - 3.2 meters',
        'camera_distance_ru': '2.5 - 3.2 метра',
        'camera_distance_kk': '2.5 - 3.2 метр',
        'body_visibility_en': 'Full piked body from hands to feet must be captured',
        'body_visibility_ru': 'Все тело от ладоней до стоп в позе домика должно быть в кадре',
        'body_visibility_kk': 'Қолдан аяққа дейінгі толық дене көрінуі тиіс',
        'camera_instructions_en': 'Place camera sideways at low angle to track hip elevation angle and head descent path.',
        'camera_instructions_ru': 'Установите камеру сбоку для контроля высоты таза и траектории опускания головы.',
        'camera_instructions_kk': 'Жамбас биіктігі мен бастың түсу траекториясын бақылау үшін камераны бүйірден қойыңыз.',
        'youtube_id': 'sposDXWEB0A',
        'video_url': 'https://www.youtube.com/watch?v=sposDXWEB0A',
        'ideal_rom_degrees': 90.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 12,
        'category_id': 9,
        'category_name': 'Rear Delts',
        'slug': 'rear_delt_fly',
        'name': 'Rear Delt Machine Flye',
        'name_en': 'Rear Delt Machine Flye',
        'name_ru': 'Разведение рук в тренажере на задние дельты (Reverse Pec Deck)',
        'name_kk': 'Тренажерде қолды артқа ашу (артқы дельта)',
        'target_muscles': 'Rear Deltoids, Rhomboids',
        'target_muscles_en': 'Posterior Deltoids (Rear Head)',
        'target_muscles_ru': 'Задняя часть дельтовидной мышцы',
        'target_muscles_kk': 'Артқы дельта бұлшықеті',
        'secondary_muscles_en': 'Infraspinatus, Teres Minor, Middle Trapezius',
        'secondary_muscles_ru': 'Подостная мышца, малая круглая, средняя трапеция',
        'secondary_muscles_kk': 'Ортаңғы трапеция, дөңгелек бұлшықет',
        'equipment': 'Machines',
        'equipment_en': 'Reverse Pec Deck Machine',
        'equipment_ru': 'Тренажер обратная бабочка',
        'equipment_kk': 'Кері көбелек тренажеры',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Pure isolated rear delt abduction providing clean tension without lower back stabilization fatigue.',
        'description_en': 'Pure isolated posterior shoulder abduction building round 3D delts and scapular stability.',
        'description_ru': 'Изолированное упражнение для прицельной прокачки задних пучков дельт с надежной фиксацией корпуса.',
        'description_kk': 'Артқы дельтаны оқшаулап қатайтуға арналған ыңғайлы және тиімді тренажер жаттығуы.',
        'starting_position_en': 'Sit facing the machine pad with chest pressed firmly against it. Hold horizontal handles with arms nearly straight.',
        'starting_position_ru': 'Сядьте лицом к тренажеру, плотно прижмите грудь к подушке. Возьмитесь за рукояти на уровне плеч.',
        'starting_position_kk': 'Тренажерге қарап отырып, кеудені нық басыңыз. Тұтқаларды иық деңгейінде ұстаңыз.',
        'instructions_en': '1. Keep a soft bend in elbows.\n2. Drive handles outward and backward horizontally using rear delts.\n3. Squeeze shoulder blades together at end range for 1 second.\n4. Return smoothly to starting position before weights touch.',
        'instructions_ru': '1. Сохраняйте легкий изгиб в локтях.\n2. Разводите рукояти назад силой задних дельт строго в горизонтальной плоскости.\n3. Прожмите задние дельты в конечной точке на 1 секунду.\n4. Плавно вернитесь вперед, не допуская соударения весовых плиток.',
        'instructions_kk': '1. Шынтақты сәл бүгілген күйде ұстаңыз.\n2. Тұтқаларды артқа қарай көлденең жазықтықта ашыңыз.\n3. Артқы нүктеде бұлшықеттерді 1 секунд қатайтыңыз.\n4. Салмақты соқпай, баяу алға қайтыңыз.',
        'breathing_en': 'Exhale on the flye backward; inhale as arms return forward.',
        'breathing_ru': 'Выдох при разведении рук назад; вдох при возврате вперед.',
        'breathing_kk': 'Артқа ашқанда тыныс шығарыңыз; алға қайтқанда тыныс алыңыз.',
        'common_mistakes_en': 'Shrugging shoulders upward, bending elbows past 90 degrees turning it into a row, bouncing weight stack.',
        'common_mistakes_ru': 'Подъем плеч к ушам (подключение трапеции), сильное сгибание локтей (превращение в тягу).',
        'common_mistakes_kk': 'Иықты көтеру, шынтақты тым қатты бүгу, салмақты екпінмен жұлу.',
        'camera_angle_en': 'Back or Side View',
        'camera_angle_ru': 'Вид сзади или сбоку',
        'camera_angle_kk': 'Артқы немесе бүйір көрініс',
        'camera_height_en': 'Chest Height',
        'camera_height_ru': 'На уровне груди',
        'camera_height_kk': 'Кеуде деңгейінде',
        'camera_distance_en': '2.0 - 2.8 meters',
        'camera_distance_ru': '2.0 - 2.8 метра',
        'camera_distance_kk': '2.0 - 2.8 метр',
        'body_visibility_en': 'Back, rear shoulders, and machine levers must be framed',
        'body_visibility_ru': 'Спина, задняя поверхность плеч и рычаги тренажера в кадре',
        'body_visibility_kk': 'Арқа, артқы иық және тренажер тұтқалары анық көрінуі керек',
        'camera_instructions_en': 'Position camera behind athlete to observe bilateral rear deltoid contraction and horizontal plane.',
        'camera_instructions_ru': 'Установите камеру сзади для контроля одновременного отведения обоих плеч.',
        'camera_instructions_kk': 'Екі иықтың бірдей артқа ашылуын көру үшін камераны арт жағыңыздан қойыңыз.',
        'youtube_id': 'v_ZoxM3Lw0E',
        'video_url': 'https://www.youtube.com/watch?v=v_ZoxM3Lw0E',
        'ideal_rom_degrees': 80.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 13,
        'category_id': 13,
        'category_name': 'Traps',
        'slug': 'barbell_shrug',
        'name': 'Barbell Shrug',
        'name_en': 'Barbell Shrug',
        'name_ru': 'Шраги со штангой стоя',
        'name_kk': 'Штангамен шраги (трапеция)',
        'target_muscles': 'Upper Trapezius, Levator Scapulae',
        'target_muscles_en': 'Upper Trapezius',
        'target_muscles_ru': 'Верхняя часть трапециевидной мышцы',
        'target_muscles_kk': 'Трапецияның жоғарғы бөлігі',
        'secondary_muscles_en': 'Forearm Flexors, Grip, Mid Trapezius',
        'secondary_muscles_ru': 'Предплечья, сила хвата, средняя трапеция',
        'secondary_muscles_kk': 'Білек, ұстау күші, ортаңғы трапеция',
        'equipment': 'Barbell',
        'equipment_en': 'Barbell',
        'equipment_ru': 'Штанга',
        'equipment_kk': 'Штанга',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Direct scapular elevation exercise developing neck and upper back muscle mass and neck stability.',
        'description_en': 'High-load scapular elevation builder strengthening upper traps and neck support.',
        'description_ru': 'Базовое движение для изолированного развития верхней части трапеции и укрепления шеи.',
        'description_kk': 'Жоғарғы трапецияны және мойын бұлшықеттерін күшейтуге арналған негізгі жаттығу.',
        'starting_position_en': 'Stand tall holding barbell at thigh level with overhand grip shoulder-width apart. Neutral neck, eyes forward.',
        'starting_position_ru': 'Встаньте прямо, удерживая штангу на уровне бедер хватом на ширине плеч. Спина прямая, взгляд вперед.',
        'starting_position_kk': 'Түзу тұрыңыз, штанганы иық енінде ұстап сан тұсында ұстаңыз. Арқа түзу, алға қараңыз.',
        'instructions_en': '1. Elevate shoulders straight up toward your ears in a pure vertical vector.\n2. Squeeze traps at top of contraction for 1.5 seconds.\n3. Lower bar smoothly under control to full stretch.\n4. Do NOT roll shoulders in circles.',
        'instructions_ru': '1. Поднимайте плечи строго вертикально вверх к ушам.\n2. Максимально сожмите трапеции в верхней точке и задержитесь на 1.5 секунды.\n3. Плавно опустите плечи вниз до полного растяжения.\n4. Категорически избегайте вращения плечами по кругу.',
        'instructions_kk': '1. Иықты тік жоғары қарай құлаққа қарай көтеріңіз.\n2. Жоғарғы нүктеде трапецияны 1.5 секунд қатты жиырыңыз.\n3. Штанганы баяу төмен түсіріңіз.\n4. Иықты дөңгелетіп айналдырмаңыз.',
        'breathing_en': 'Exhale as you elevate shoulders; inhale as you lower the weight.',
        'breathing_ru': 'Выдох при подъеме плеч вверх; вдох при опускании.',
        'breathing_kk': 'Иықты көтергенде тыныс шығарыңыз; түсіргенде тыныс алыңыз.',
        'common_mistakes_en': 'Rolling shoulders in circles (injures rotator cuff), bending elbows into a curl, using knee bounce.',
        'common_mistakes_ru': 'Вращение плечами по кругу (травмирует плечевые суставы), сгибание рук в локтях, помощь ногами.',
        'common_mistakes_kk': 'Иықты дөңгелетіп айналдыру (буынға зиян), шынтақты бүгу, аяқпен серпілу.',
        'camera_angle_en': 'Front View (0°)',
        'camera_angle_ru': 'Вид спереди (0°)',
        'camera_angle_kk': 'Алдыңғы көрініс (0°)',
        'camera_height_en': 'Chest / Shoulder Height',
        'camera_height_ru': 'На уровне груди/плеч',
        'camera_height_kk': 'Кеуде / иық деңгейінде',
        'camera_distance_en': '2.0 - 3.0 meters',
        'camera_distance_ru': '2.0 - 3.0 метра',
        'camera_distance_kk': '2.0 - 3.0 метр',
        'body_visibility_en': 'Head, neck, shoulders, and bar must be in frame',
        'body_visibility_ru': 'Голова, шея, плечи и гриф штанги должны быть видны',
        'body_visibility_kk': 'Бас, мойын, иық және штанга анық көрінуі керек',
        'camera_instructions_en': 'Position camera directly in front to observe equal vertical elevation of both shoulders.',
        'camera_instructions_ru': 'Установите камеру спереди для проверки симметричного подъема обоих плеч.',
        'camera_instructions_kk': 'Екі иықтың бірдей биіктікке көтерілуін бақылау үшін камераны алдыңыздан қойыңыз.',
        'youtube_id': 'g6qbq4Sq138',
        'video_url': 'https://www.youtube.com/watch?v=g6qbq4Sq138',
        'ideal_rom_degrees': 30.0,
        'normative_cadence_seconds': 2.5,
        'analysis_supported': False,
    },
    {
        'id': 14,
        'category_id': 14,
        'category_name': 'Neck',
        'slug': 'neck_isometric_flexion_extension',
        'name': 'Isometric Neck Strengthening',
        'name_en': 'Isometric Neck Strengthening',
        'name_ru': 'Изометрическое укрепление мышц шеи',
        'name_kk': 'Мойын бұлшықеттерін изометриялық нығайту',
        'target_muscles': 'Sternocleidomastoid, Splenius Capitis',
        'target_muscles_en': 'Sternocleidomastoid, Cervical Extensors',
        'target_muscles_ru': 'Грудино-ключично-сосцевидная, разгибатели шеи',
        'target_muscles_kk': 'Мойынды бұрушы және жазушы бұлшықеттер',
        'secondary_muscles_en': 'Upper Trapezius, Scalenes',
        'secondary_muscles_ru': 'Верх трапеции, лестничные мышцы',
        'secondary_muscles_kk': 'Жоғарғы трапеция, баспалдақты бұлшықеттер',
        'equipment': 'Bodyweight',
        'equipment_en': 'Bodyweight / Hand Resistance',
        'equipment_ru': 'Свой вес / сопротивление руками',
        'equipment_kk': 'Өз салмағы / қол қарсылығы',
        'difficulty': 'Beginner',
        'difficulty_en': 'Beginner',
        'difficulty_ru': 'Начинающий',
        'difficulty_kk': 'Бастаушы',
        'description': 'Safe multi-directional neck stability drill enhancing cervical resilience and impact protection for athletes.',
        'description_en': 'Safe isometric cervical conditioning protecting against impact and stabilizing neck posture.',
        'description_ru': 'Безопасное статическое укрепление шейного отдела для защиты от травм и коррекции положения головы.',
        'description_kk': 'Мойын омыртқасын жарақаттан қорғауға және бастың түзулігін қалыптастыруға арналған қауіпсіз жаттығу.',
        'starting_position_en': 'Sit tall with neutral spine and level chin. Place palm against forehead (flexion) or back of head (extension).',
        'starting_position_ru': 'Сядьте прямо, подбородок параллелен полу. Приложите ладонь ко лбу (сгибание) или к затылку (разгибание).',
        'starting_position_kk': 'Түзу отырыңыз, иек еденге параллель. Алақанды маңдайға немесе желкеге қойыңыз.',
        'instructions_en': '1. Press head gently into palm while matching with equal hand resistance (no head movement).\n2. Maintain steady contraction for 6-10 seconds.\n3. Relax for 3 seconds and repeat across flexion, extension, and lateral vectors.\n4. Keep breathing calmly.',
        'instructions_ru': '1. Плавно давите головой в ладонь, удерживая голову абсолютно неподвижной силой рук.\n2. Удерживайте статическое напряжение 6-10 секунд.\n3. Расслабьтесь на 3 секунды и повторите вперед, назад и в стороны.\n4. Дышите ровно без задержки дыхания.',
        'instructions_kk': '1. Басты қозғалтпай, алақанға қарай бірқалыпты күшпен басыңыз.\n2. Статикалық күшті 6-10 секунд ұстап тұрыңыз.\n3. 3 секунд демалып, алға, артқа және бүйірге қайталаңыз.\n4. Бірқалыпты тыныс алыңыз.',
        'breathing_en': 'Maintain slow, continuous rhythmic diaphragmatic breathing throughout the hold.',
        'breathing_ru': 'Спокойное непрерывное дыхание животом без натуживания.',
        'breathing_kk': 'Күш түскенде тынысты тоқтатпай, баяу әрі терең тыныс алыңыз.',
        'common_mistakes_en': 'Jerking forcefully, holding breath, forcing neck through extreme painful angles.',
        'common_mistakes_ru': 'Резкие рывки шеей, задержка дыхания (эффект Вальсальвы), чрезмерное давление руками.',
        'common_mistakes_kk': 'Мойынды жұлқып қозғалту, тынысты тоқтату, шамадан тыс қатты басу.',
        'camera_angle_en': 'Front or Side View',
        'camera_angle_ru': 'Вид спереди или сбоку',
        'camera_angle_kk': 'Алдыңғы немесе бүйір көрініс',
        'camera_height_en': 'Eye / Head Height',
        'camera_height_ru': 'На уровне глаз/головы',
        'camera_height_kk': 'Көз / бас деңгейінде',
        'camera_distance_en': '1.5 - 2.5 meters',
        'camera_distance_ru': '1.5 - 2.5 метра',
        'camera_distance_kk': '1.5 - 2.5 метр',
        'body_visibility_en': 'Head, neck, and shoulders must be clearly framed',
        'body_visibility_ru': 'Голова, шея и плечевой пояс должны быть четко в кадре',
        'body_visibility_kk': 'Бас, мойын және иықтар анық көрінуі тиіс',
        'camera_instructions_en': 'Position camera at head level to monitor cervical neutrality throughout isometric hold.',
        'camera_instructions_ru': 'Установите камеру на уровне головы для проверки неподвижности шеи.',
        'camera_instructions_kk': 'Мойынның қозғалмай түзу тұрғанын бақылау үшін камераны бас биіктігіне қойыңыз.',
        'youtube_id': 'Y4p7Z1R17fI',
        'video_url': 'https://www.youtube.com/watch?v=Y4p7Z1R17fI',
        'ideal_rom_degrees': 0.0,
        'normative_cadence_seconds': 10.0,
        'analysis_supported': False,
    }
]
